const english = {
  app_name: "Cookie",
  anonymous: "Anonymous",
  app_email_1: "Have you recorded your data?",
  app_email_2: "Enter your email address and click send.",
  app_email_3: "Get your username and password to always be able to return to the game!",
  app_email_4: "Send",
  app_email_5: "Your Email",
  app_settings_title: "Settings",
  app_settings_music: "Music",
  app_settings_music_bg: "Play minimized",
  app_settings_sounds: "Sounds",
  app_settings_rain: "Cookie Rain speed",
  app_settings_notify: "Notifications",
  app_settings_wishes: "Wishes (in profile)",
  app_settings_extra: "Extra options",
  app_welcome_1: "Hello!",
  app_welcome_2: "Registration is complete",
  app_welcome_3: "Login:",
  app_welcome_4: "Password:",
  app_welcome_5: "We store your data on this device as long as it exists, you won't lose your progress!",
  app_welcome_6: "OK, play!",
  app_welcome_7: "Already have a login?",
  app_welcome_8: "Enter your details to continue the game!",
  app_welcome_9: "Enter data!",
  app_welcome_10: "Log into the game",
  app_welcome_11: "Login",
  app_welcome_12: "Password",
  app_welcome_13: "Enter",
  city_buildings_bank_1: "City Bank",
  city_buildings_bank_2: "Level:",
  city_buildings_bank_3: "Determines the number of prize tickets in the rating of city residents who have scored the required number of points",
  city_buildings_bank_4: "Characteristics",
  city_buildings_bank_5: "Requirement",
  city_buildings_bank_6: "Now:",
  city_buildings_bank_7: "points",
  city_buildings_bank_8: "Next:",
  city_buildings_brickyard_1: "Brick Factory",
  city_buildings_brickyard_2: "Produces the bricks required for the construction and improvement of city buildings",
  city_buildings_brickyard_3: "Production",
  city_buildings_brickyard_4: "Select amount:",
  city_buildings_brickyard_5: "TOTAL:",
  city_buildings_brickyard_6: "Produce",
  city_buildings_brickyard_7: "Production limit:",
  city_buildings_brickyard_8: "pcs.",
  city_buildings_brickyard_9: "Production Details",
  city_buildings_brickyard_10: "The cost of a brick",
  city_buildings_brickyard_11: "Reset the limit",
  city_buildings_brickyard_12: "once a day",
  city_buildings_brickyard_13: "Production stopped",
  city_buildings_brickyard_14: "Daily limit reached",
  city_buildings_brickyard_15: "Improvement",
  city_buildings_buildings_1: "Added to the building ",
  city_buildings_cafe_1: "Cafe",
  city_buildings_cafe_2: "Increases the number of falling cookies in the Cookie Rain",
  city_buildings_cafe_3: "Current increase:",
  city_buildings_cafe_4: "After improvement:",
  city_buildings_cafe_5: "pcs.",
  city_buildings_candy_factory_1: "Candy Factory",
  city_buildings_candy_factory_2: "Allows you to increase the running time of Boosters when activated",
  city_buildings_candy_factory_3: "Time increase:",
  city_buildings_candy_factory_4: "min.",
  city_buildings_city_hall_1: "City Hall",
  city_buildings_city_hall_2: "Manages the maximum number of residents (participants) in the city",
  city_buildings_city_hall_3: "Current limit:",
  city_buildings_city_hall_4: "residents",
  city_buildings_city_hall_5: "After improvement:",
  city_buildings_mill_1: "Mill",
  city_buildings_mill_2: "Increases the chance of high-level cookies dropping during the Cookie Rain",
  city_buildings_mill_3: "Chance increased:",
  city_buildings_mill_4: "by",
  city_buildings_success_1: "Construction completed!",
  city_buildings_success_2: "The building level has been raised to",
  city_buildings_success_3: "",
  city_buildings_success_4: "Efficiency increased!",
  city_buildings_success_5: "Great!",
  city_buildings_success_6: "Production limit",
  city_buildings_success_7: "Limit of residents in the city:",
  city_buildings_success_8: "Awards and requirements",
  city_buildings_success_9: "Requirement",
  city_buildings_success_10: "points",
  city_buildings_success_11: "Cookies in the Cookie Rain:",
  city_buildings_success_12: "The chance of a cookie falling of an increased level:",
  city_buildings_success_13: "Booster operating time:",
  city_buildings_success_14: "Building not found!",
  city_buildings_upgrade_1: "Improvement",
  city_buildings_upgrade_2: "The maximum level has been reached",
  city_buildings_upgrade_3: "Cookies required",
  city_buildings_upgrade_4: "Bricks required",
  city_buildings_upgrade_5: "Buy",
  city_buildings_upgrade_6: "Produce",
  city_buildings_upgrade_7: "Add",
  city_buildings_upgrade_8: "Not enough cookies!",
  city_buildings_upgrade_9: "Not enough bricks!",
  city_buildings_upgrade_10: "Waiting for bricks",
  city_buildings_upgrade_11: "Waiting for cookies",
  city_buildings_upgrade_12: "Progress:",
  city_chat_1: "Your message...",
  city_chat_2: "A new message in the city chat!",
  city_chat_3: "A few new city chat messages!",
  city_city_panel_1: "You haven't joined the city yet",
  city_city_panel_2: "Your balance",
  city_city_panel_3: "bricks",
  city_city_panel_4: "cookies",
  city_city_panel_5: "online:",
  city_control_changes_1: "Avatar - choose an image for your city. Some of them, you will be able to unlock later.",
  city_control_changes_2: "View and select",
  city_control_changes_3: "Name - censored, attractive and memorable name of your city",
  city_control_changes_4: "Description - censored, a brief description of your city, you can not fill in.",
  city_control_changes_5: "Accessibility - choose the type of social accessibility of your city.",
  city_control_changes_6: "Public",
  city_control_changes_7: "- visible to everyone in the list of random cities;",
  city_control_changes_8: "- any player can join your city;",
  city_control_changes_9: "Private",
  city_control_changes_10: "- not visible in the list of random cities;",
  city_control_changes_11: "- the player joins the city only after your approval;",
  city_control_changes_12: "cookies",
  city_control_changes_13: "Sale, left: ",
  city_control_control_1: "After leaving, you will not be able to enter another city for a day!",
  city_control_control_2: "You are the mayor of this city and you cannot leave your city while there are other residents in it!",
  city_control_control_3: "Leave the city",
  city_control_control_4: "Here you can leave the city in which you are currently a resident.\nIf you leave the city, you will lose all its advantages.",
  city_control_control_5: "Leave this city",
  city_control_logo_1: "Setting",
  city_control_logo_2: "up an avatar",
  city_control_logo_3: "Random",
  city_control_logo_4: "Save",
  city_control_members_1: "Residents of the city",
  city_control_members_2: "In a week",
  city_control_members_3: "All time",
  city_control_members_4: "Open a profile",
  city_control_members_5: "Kick out of town",
  city_control_notes_1: "Write here everything you want, for example greetings, news, rules, instructions, wishes. This text will be seen by all residents of your city.",
  city_control_notes_2: "City rules",
  city_control_notes_3: "To write",
  city_control_notes_4: "Cancel",
  city_control_notes_5: "Save",
  city_control_requests_1: "None",
  city_control_requests_2: "Applications for membership",
  city_control_requests_3: "the application is approved",
  city_control_summary_1: "City summary",
  city_control_summary_2: "Information",
  city_control_summary_3: "Mayor:",
  city_control_summary_4: "Residents in the city:",
  city_control_summary_5: "Date of foundation:",
  city_control_summary_6: "of",
  city_control_summary_7: "Activity for the week",
  city_control_summary_8: "Points received:",
  city_control_summary_9: "Merges made:",
  city_control_summary_10: "Buildings",
  city_control_summary_11: "Level:",
  city_control_summary_12: "Bricks:",
  city_control_summary_13: "Cookies:",
  city_control_summary_14: "d.",
  city_control_summary_15: "max",
  city_header_1: "Chat",
  city_help_page_1: "1. What is a city?",
  city_help_page_2: "This is a social mechanic that allows you to team up with other players and get good bonuses.",
  city_help_page_3: "2. What can I do in the city?",
  city_help_page_4: "Chat, improve city buildings, compete with other residents and cities for bonuses. The list will grow.",
  city_help_page_5: "3. Why improve buildings?",
  city_help_page_6: "Each building gives its own unique bonus.",
  city_help_page_7: "For example, the Cafe increases the number of cookies falling during a Cookie Rain, and the Candy Factory increases the duration of the Rocket Booster.",
  city_help_page_8: "4. How to improve buildings?",
  city_help_page_9: "Buildings are improved for cookies and bricks.",
  city_help_page_10: "Bricks are the city's currency, bought for silver at a brick factory.",
  city_help_page_11: "The cost of bricks for all players is equal and is measured in hours of income.",
  city_help_page_12: "5. Who is the mayor?",
  city_help_page_13: "The mayor is the creator of the city.",
  city_help_page_14: "He can change the avatar, name, description and privacy of the city.",
  city_help_page_15: "In his right to receive and expel residents.",
  city_help_page_16: "He sees the contribution of every resident.",
  city_help_page_17: "The role of mayor cannot be transferred to another resident.",
  city_help_page_18: "6. Why do we need a rating of residents?",
  city_help_page_19: "The most active residents receive tickets to the Wheel of Fortune after each end of the week.",
  city_help_page_20: "Prizes and requirements depend on the level of improvement of the bank.",
  city_help_page_21: "To get tickets to the Wheel of Fortune, you need to score at least 100 contribution points.",
  city_help_page_22: "The top 3 residents receive increased prizes.",
  city_help_page_23: "7. How to score points for the rating of residents?",
  city_help_page_24: "The points are summed up from the number of bricks and cookies invested in building improvements.",
  city_help_page_25: "For 1 brick - 1 point.",
  city_help_page_26: "For 1 cookie - 10 points.",
  city_help_page_27: "8. Why do I need a rating of cities?",
  city_help_page_28: "The rating is based on the sum of the connections of cookies among all residents of the city.",
  city_help_page_29: "Allows you to increase the population of your city and attract the most active players.",
  city_help_page_30: "Help",
  city_help_page_31: "FAQ",
  city_leaders_1: "Weekly",
  city_leaders_2: "Monthly",
  city_leaders_3: "Total",
  city_leaders_4: "Rating of cities",
  city_members_1: "Rating of residents",
  city_members_2: "Rating rules",
  city_members_rules_1: "Rules",
  city_members_rules_2: "The rating is based on the points (points) that residents can receive\r\nfor active play and support of your city.",
  city_members_rules_3: "What you can get points for:",
  city_members_rules_4: "- adding bricks to the building",
  city_members_rules_5: "1 brick =",
  city_members_rules_6: "point",
  city_members_rules_7: "- bringing cookies into the building",
  city_members_rules_8: "1 cookie =",
  city_members_rules_9: "points",
  city_members_rules_10: "In the weekly ranking, residents have a chance to get valuable prizes.",
  city_members_rules_11: "To increase the number of prizes, upgrade the City Bank.",
  city_no_items_1: "Some error, please try again later",
  city_no_items_2: "The list is empty :(",
  city_overview_page_1: "Private",
  city_overview_page_2: "Public",
  city_overview_page_3: "Description",
  city_overview_page_4: "Join",
  city_overview_page_5: "Send a request",
  city_overview_page_6: "Information about the city",
  city_overview_page_7: "Information",
  city_overview_page_8: "Type:",
  city_overview_page_9: "Residents:",
  city_overview_page_10: "Founded:",
  city_overview_page_11: "d.",
  city_overview_page_12: "Buildings",
  city_overview_page_13: "City Hall:",
  city_overview_page_14: "level",
  city_overview_page_15: "City Bank:",
  city_overview_page_16: "Cafe:",
  city_overview_page_17: "Confectionery factory:",
  city_overview_page_18: "Mill:",
  city_overview_page_19: "of",
  city_overview_page_20: "Brick Factory:",
  city_search_buttons_1: "Accept",
  city_search_buttons_2: "Join",
  city_search_buttons_3: "Submit an application",
  city_search_buttons_4: "Cancel",
  city_search_buttons_5: "You are invited",
  city_search_random_1: "Random cities",
  city_search_random_2: "Your applications",
  city_search_search_1: "Create a city",
  city_search_search_panel_1: "Nothing found",
  city_search_search_panel_2: "Enter something and click find",
  city_search_search_panel_3: "Search for cities",
  city_search_search_panel_4: "Find",
  city_search_search_panel_5: "Title...",
  city_tutorial_free_panel_1: "Probably, there are no free cities yet.",
  city_tutorial_free_panel_2: "Create your own city for free!",
  city_tutorial_free_panel_3: "Join a city that you like or create your own with cookies!",
  city_tutorial_free_panel_4: "Free cities",
  city_tutorial_free_panel_5: "Join",
  city_tutorial_hints_1: "Ok",
  city_tutorial_tutorial_1: "Create your own city",
  city_welcome_page_1: "Welcome",
  city_welcome_page_2: "to your own city!",
  city_welcome_page_3: "Now you are the mayor, the owner of the city",
  city_welcome_page_4: "Invite players to your place, chat with the residents of the city, improve buildings and get bonuses in the game.\nAchieve leading positions in the ranking of other cities!",
  city_welcome_page_5: "The time has come for a great leader. Make your city the best!",
  city_welcome_page_6: "Go!",
  city_welcome_page_7: "to the city of",
  city_welcome_page_8: "Upgrade buildings for in-game bonuses,\ninteract with fellow residents in the chat, \nand engage in city-to-city competitions",
  city_welcome_page_9: "Be a model city resident. :)",
  cookies_shop_item_1: "Create the",
  cookies_shop_item_2: " level",
  cookies_shop_item_buy: "Buy for:",
  cookies_shop_item_sec: "/sec",
  cookies_shop_title: "Shop",
  crush_btn: "Open",
  extra_menu_battle: "Battle",
  extra_menu_my_city: "My city",
  free_cookies_1: "Complete the tasks and return daily to collect rewards!",
  free_cookies_2: "Make reposts and get for every new player who comes in on your links",
  free_cookies_3: "Just for first-time app users who manage to crush at least three fortune cookies",
  free_cookies_4: "Invite your friends and claim cookies when they start playing!",
  free_cookies_5: "for everyone!",
  free_cookies_6: "Just for first-time app users who manage to crush at least three fortune cookies",
  free_cookies_get: "Get",
  free_cookies_gifts: "Gifts",
  free_cookies_in_day: "daily",
  free_cookies_invite: "Invite friends",
  free_cookies_perform: "Do it!",
  free_cookies_promo: "Your promo codes",
  free_cookies_promo_codes_active: "Active until ",
  free_cookies_promo_codes_copy: "Copy to clipboard",
  free_cookies_promo_codes_send: "Send to PM",
  free_cookies_promo_codes_title: "Your promo codes",
  free_cookies_received: "Received",
  free_cookies_story: "Share in the story",
  free_cookies_wall: "Share on your wall",
  free_cookies_share: "Share game",
  game_Free: "For free",
  game_rain_enabled: "Enabled!",
  game_for_prize: "Prize!",
  game_rain: "Cookie Rain",
  game_rocket: "Booster",
  game_sale: "Sale",
  game_shop: "Market",
  game_battle_leaders_1: "The best for today",
  game_battle_leaders_2: "Prize",
  game_battle_lobby_close: "close",
  game_battle_lobby_connection: "Connection...",
  game_battle_lobby_duel: "Battle",
  game_battle_lobby_go: "Go!",
  game_battle_lobby_training: "Training battle",
  game_battle_merge_1: "Merge the cookies as quickly, overtake the opponent by merges.",
  game_battle_merge_2: "Win his bet!",
  game_battle_merge_3: "Choose a bet for the game:",
  game_battle_merge_cookie: "Cookie",
  game_battle_result_1: "Once again!",
  game_battle_result_close: "close",
  game_battle_result_cookie: "cookie",
  game_battle_result_draw_mess: "You returned:",
  game_battle_result_draw_title: "Draw!",
  game_battle_result_loss_mess: "You've lost:",
  game_battle_result_loss_title: "Loss!",
  game_battle_result_win_mess: "You received:",
  game_battle_result_win_title: "Win!",
  game_battle_select_rival_1: "Search for an opponent",
  game_battle_select_rival_2: "on the server",
  game_battle_select_rival_3: "cancel",
  game_battle_tutorial_next: "Next",
  game_battle_tutorial_res_1: "Congratulations, you won! It's time to play with a real opponent!",
  game_battle_tutorial_res_2: "Victory!",
  game_battle_tutorial_res_3: "It's okay! Try to complete the training again!",
  game_battle_tutorial_res_4: "Defeat!",
  game_battle_tutorial_res_5: "A draw!",
  game_battle_tutorial_res_6: "close",
  game_battle_tutorial_res_7: "The training is over!",
  game_battle_tutorial_res_8: "Back",
  game_cookie_rain_layer_1: "It's time to merge",
  game_cookie_rain_layer_2: "cookies!",
  game_cookie_rain_layer_3: "Make room",
  game_cookie_rain_layer_4: "for Cookie Rain",
  game_cost: "Cost",
  game_counter_soft_1: "From the booster",
  game_counter_soft_sec: "/s",
  game_leagues: "Leagues",
  game_leagues_tutorial_1: 'Congratulations!\nYou unlocked the Leagues!',
  game_leagues_tutorial_2: 'This is a competition with other players for',
  game_leagues_tutorial_2_1: 'cookie prizes',
  game_leagues_tutorial_3: 'Okay',
  game_leagues_tutorial_4: 'By pairing cookies you get',
  game_leagues_tutorial_4_1: 'merge points',
  game_leagues_tutorial_5: 'Other players are active and earning their merge points too.',
  game_leagues_tutorial_6: 'I understand',
  game_leagues_tutorial_7: 'The League tournaments lasts one week, this timer shows the',
  game_leagues_tutorial_7_1: 'remaining time',
  game_leagues_tutorial_8: 'Be among the',
  game_leagues_tutorial_8_1: 'top ten',
  game_leagues_tutorial_8_2: 'players in your League.',
  game_leagues_tutorial_9: 'Get',
  game_leagues_tutorial_9_1: 'cookies',
  game_leagues_tutorial_9_2: 'and move on to the next,',
  game_leagues_tutorial_9_3: 'awesome tournament',
  game_leagues_tutorial_10: 'Start Baking!',
  game_main_am_unlock_rain: 'Need a level 5 cookie!',
  game_main_am_unlock_rocket: 'Level 6 cookie required!',
  game_main_am_unlock_income: 'Unlocked at level 7!',
  game_main_am_unlock_plates: 'Level 8 cookie required!',
  game_main_biggest_1: "Congratulations!",
  game_main_biggest_2: "New cookie level unlocked!",
  game_main_biggest_3: "Great!",
  game_main_left_menu_1: "City",
  game_main_left_menu_2: "Battle",
  game_main_left_menu_3: "League",
  game_main_left_menu_4: "Market",
  game_main_left_menu_leagues: 'To unlock the Leagues,\nget a level 7 cookie!',
  game_main_left_menu_city: 'Cities will be available\nafter level 10 cookie!',
  game_main_rain_3: "Trigger a rain of cookies on your game table",
  game_main_rain_4: "Start",
  game_main_rocket_1: "Activate turbo income for a few hours",
  game_main_rocket_2: "Activate",
  game_main_tab_1: "Improvements",
  game_main_tab_2: "Fast Buy",
  game_main_sack_take: 'Claim',
  game_main_tutor_1: "Merge similar cookies",
  game_main_tutor_2: "Buy some cookies for the table",
  game_main_tutor_3: "Get a level 4 cookie",
  game_main_tutor_4: "Hi!",
  game_main_tutor_5: "The objective of the game is",
  game_main_tutor_6: "merge cookies",
  game_main_tutor_7: "to unlock cool new cookies!",
  game_main_tutor_8: "Let's start merging and see what happens.",
  game_main_tutor_9: "Go!",
  game_main_tutor_10: "Buy!",
  game_main_tutor_11: "Great! But there is nothing left to merge.",
  game_main_tutor_12: "We need",
  game_main_tutor_13: "to buy more",
  game_main_tutor_14: "cookies on the table to continue playing!",
  game_main_tutor_15: "Let's buy them through the fast buy menu.",
  game_main_tutor_16: "Go!",
  game_main_tutor_17: "Coins!",
  game_main_tutor_18: "Each cookie on the table",
  game_main_tutor_19: "earns",
  game_main_tutor_20: "coins.",
  game_main_tutor_21: "The higher the cookie level, the more coins it",
  game_main_tutor_22: "earns per second",
  game_main_tutor_23: "Merge the purchased cookies to unlock a new cookie level!",
  game_main_tutor_24: "Ok!",
  game_main_tutor_25: "Great!",
  game_main_tutor_26: "Keep playing, buy and merge cookies, unlock new levels.",
  game_main_tutor_27: "Complete tasks and get",
  game_main_tutor_28: "rewards",
  game_main_tutor_29: ", use various improvements!",
  game_main_tutor_30: "Unlock the",
  game_main_tutor_31: "Leagues",
  game_main_tutor_32: "and compete for",
  game_main_tutor_33: "prizes",
  game_main_tutor_34: " with other players!",
  game_main_tutor_35: "Play!",
  game_income: 'Offline Income',
  game_income_max: "Maximum level",
  game_income_description: "Earn more silver even while you're away from the game!",
  game_income_level: "Level",
  game_income_upgrade: "Upgrade",
  game_income_prize: "Prize!",
  game_leagues_1: " winners get cookies",
  game_leagues_2: " winners move to a new League tournament and get cookies",
  game_leagues_3: "League relegation zone",
  game_plates_footer_1: "Upgrade the plates to increase the income generated by the cookies placed on them!",
  game_plates_footer_2: "Place your best cookies on the upgraded plates!",
  game_plates_footer_done: "Done",
  game_plates_plates_sale: "Sale ends in:",
  invite_invite_1: "It looks like all your friends are already playing the cookie",
  invite_invite_2: "Some error has occurred, please try again later",
  invite_invite_3: "Call your friends and get a reward when they start playing and open at least three cookies",
  invite_invite_title: "Post",
  invite_list_item_invite: "Invite",
  invite_list_item_invited: "Invited",
  league_bronze: "Bronze League",
  league_gold: "Golden League",
  league_platinum: "Platinum League",
  league_ruby: "Ruby League",
  league_silver: "Silver League",
  loading_1: "loading your data",
  main_ad_video_rb_view: "Watch ad!",
  main_ad_video_rb_limit: "Inactive\nuntil next day",
  main_ad_video_rb_popup: "The reward for advertising will be available a little later!",
  main_app_banner_1: "Bake more cookies!",
  main_app_banner_2: "you have promo codes",
  main_app_banner_3: "Use them before the deadline!",
  main_crush_button_text_1: "Crush more",
  main_crush_button_text_2: "Crush for",
  main_crush_tutorial_1: "Congratulations!",
  main_crush_tutorial_2: "This is your prediction.",
  main_crush_tutorial_3: "Ok",
  main_crush_tutorial_4: "Come tomorrow",
  main_crush_tutorial_5: "and get a free cookie",
  main_crush_tutorial_6: "once a day!",
  main_crush_tutorial_7: "Do you want to get",
  main_crush_tutorial_8: "free cookies now?",
  main_crush_tutorial_9: "Come in here!",
  main_crush_tutorial_10: "Be sure to come into the game.",
  main_crush_tutorial_11: "You can also get",
  main_crush_tutorial_12: "free cookies there!",
  main_crush_tutorial_13: "Tomorrow a new prediction",
  main_crush_tutorial_14: "will be waiting for you,",
  main_crush_tutorial_15: "subscribe so as not to forget!",
  main_crush_tutorial_16: "Subscribe",
  main_crush_tutorial_17: "Ok",
  main_footer_dating: "Dating",
  main_footer_free_cookies: "Free cookies",
  main_footer_game: "Game",
  main_footer_hint: "Cookies!",
  main_footer_profile: "Profile",
  main_footer_rating: "Rating",
  main_free_timer_text_1: "Free",
  main_free_timer_text_2: "Get",
  main_main_cookie_text_1: "Do you like the prediction?",
  main_share_buttons_invite: "Invite a friend",
  main_share_buttons_published: "Published",
  main_share_buttons_story: "Share to story",
  main_share_buttons_wall: "Share on your wall",
  main_share_buttons_share: "Share Fortune",
  modals_battle_help_1: "Welcome to the PvP battle mode with a real player.",
  modals_battle_help_2: "In this mode, you must make more cookie merges in less time than your opponent.",
  modals_battle_help_3: "At the start, 3500 silver is given and the opportunity to use a Cookie Rain for one cookie from your bet.",
  modals_battle_help_4: "You and your opponent place a bet and start the battle. If you win, you get back what's left of your bet and the opponent's full bet.",
  modals_battle_help_5: "If you lose, you lose your bet, the opponent takes it for himself.",
  modals_battle_help_6: "Good luck in the battles!",
  modals_battle_help_ok: "Ok",
  modals_battle_help_title: "Battles: Help",
  modals_bonus_spwp_1: "Congratulations!",
  modals_bonus_spwp_2: "New players have come through your links:",
  modals_bonus_spwp_3: "Reward:",
  modals_bonus_spwp_4: "Great!",
  modals_bonus_spwp_5: "Get",
  modals_bonus_spwp_title: "Reward for invited guests",
  modals_common_ok: "Ok",
  modals_common_title: "Information",
  modals_exit_battle_question: 'Exit the battle?',
  modals_exit_battle_description_1: 'The training battle will over',
  modals_exit_battle_description_2: 'You will lose the battle and also your cookies',
  modals_exit_battle_accept: 'Yes\nleave',
  modals_exit_battle_reject: 'No\nstay',
  modals_modal_no_bricks_1: "Oh no!",
  modals_modal_no_bricks_2: "You don't have enough",
  modals_modal_no_bricks_3: "Bricks are produced in cities, at a brick factory.",
  modals_modal_no_bricks_4: "Ok",
  modals_no_hard_hint_shop: "Come back tomorrow\nor top up your balance!",
  modals_no_hard_hint_no_shop: "Come back tomorrow\nand get free cookies!",
  modals_no_hard_offer_ad: "Get a cookie\nfor viewing ad",
  modals_no_hard_watch_ad: "Watch ad",
  modals_no_hard_no: "Oh no!",
  modals_no_hard_not_enough: "You need at least",
  modals_no_hard_ok: "Got it",
  modals_no_hard_shop: "Go to store",
  modals_offer_notify_1: "A free cookie will appear after a while.",
  modals_offer_notify_2: "Do I remind you of the appearance of a new one?",
  modals_offer_notify_ok: "Ok",
  modals_offline_1: "Lost connection with the server",
  modals_offline_ok: "OK",
  modals_offline_profit_1: "While you were gone,",
  modals_offline_profit_2: "your cookies earned",
  modals_offline_profit_3: "Offline Income time",
  modals_offline_profit_4: "0 h",
  modals_offline_profit_5: "Triple it!",
  modals_offline_profit_6: "Get 3x",
  modals_offline_profit_get: "Get",
  modals_offline_profit_hour: " h",
  modals_offline_profit_min: " m",
  modals_offline_profit_title: "Income",
  modals_ping_screen_back: "back",
  modals_ping_screen_connection: "Connection...",
  modals_promo_code_1: "Conditions of receipt",
  modals_promo_code_2: "Activate on",
  modals_promo_code_3: "Copy the promo code",
  modals_promo_code_4: "Activation period up to:",
  modals_promo_code_5: "All your gifts are here, in the section \"Your promo codes\"",
  modals_promo_code_6: "Free",
  modals_promo_code_7: "cookies",
  modals_promo_code_8: "Send to PM",
  modals_promo_code_9: "Continue",
  modals_promo_code_10: "Advertisement",
  modals_search_ads_1: "Advertising selection",
  modals_session_error_1: "It seems that you have already logged into the game on another device!",
  modals_session_error_2: "To continue playing here, click on the button below",
  modals_session_error_3: "Use this device",
  modals_session_error_oops: "Oops!",
  modals_technical_works_1: "Technical work is being carried out. The app is temporarily unavailable. We apologize.",
  modals_tester_settings_1: "Permanent crush cookie tutorial",
  modals_tester_settings_2: "Permanent tutorial in merge game",
  modals_tester_settings_3: "Production",
  modals_tester_settings_4: "Test",
  modals_tester_settings_6: "Close",
  modals_tester_settings_title: "Tests",
  modals_welcome_city_1: "The application is approved!",
  modals_welcome_city_2: "The mayor of the city has approved your request to join.",
  modals_welcome_city_3: "Hurry up to visit your city, find out about the bonuses you have received and chat with other residents!",
  modals_welcome_city_4: "To the city!",
  modals_wheel_prize_get: "Get",
  modals_wheel_prize_open: "Open!",
  modals_winner_gift_1: ", you got a gift! Congratulations!",
  modals_winner_gift_accept: "Accept",
  predict_download_1: "Exploring the horizons of tomorrow",
  predict_download_2: "Predicting the future",
  predict_download_3: "Deciphering the mysteries of time",
  predict_download_4: "Analyzing prospects",
  predict_download_5: "Unveiling tomorrow",
  predict_download_6: "Investigating paths forward",
  predict_download_7: "Parting the curtain of time",
  predict_download_8: "Gazing into the upcoming",
  predict_download_9: "Cracking the code of tomorrow",
  predict_download_10: "Studying celestial bodies",
  predict_download_11: "Gazing at cosmic expanses",
  predict_download_12: "Exploring the starry sky",
  predict_download_13: "Examining the cosmos",
  predict_download_14: "Inspecting the star map",
  predict_download_15: "Peering into the depths of the universe",
  predict_download_16: "Seeking answers from higher powers",
  predict_download_17: "Turning to the wisdom of the Universe",
  predict_download_18: "Engaging in dialogue with the divine",
  predict_download_19: "Investigating mystical knowledge",
  predict_download_20: "Connecting with the invisible world",
  predict_download_21: "Requesting prophecies",
  predict_download_22: "Listening to voices from above",
  predict_download_23: "Interpreting the signs of fate",
  predict_download_24: "Extracting wisdom from cosmic ether",
  predict_download_25: "Consulting the sages",
  predict_download_26: "Contemplating the eternal",
  predict_download_27: "Seeking advice from elder forces",
  predict_download_28: "Delving into the mysteries of magic",
  predict_download_29: "Turning to sources of wisdom",
  predict_download_30: "Asking questions to cosmic consciousness",
  profile_cookies_counter: "Your balance:",
  profile_gift_page_inventory: "Inventory",
  profile_gift_page_shop: "Shop",
  profile_item_friend_select: "Select",
  profile_item_shop_gift_hit: "hit",
  profile_no_items_1: "Alas, you haven't been given anything yet.",
  profile_no_items_2: "Make a gift to a friend and he will probably answer you!",
  profile_no_items_3: "Give to a friend",
  profile_no_items_4: "Alas, you have not yet received a free gift.",
  profile_no_items_5: "Random gifts can be obtained by opening predictions or winning them in the wheel of fortune",
  profile_no_items_6: "Also, you can choose any gift for cookies",
  profile_no_items_7: "Select",
  profile_no_items_8: "Alas, none of your friends are playing \"Fortune Cookie\" yet",
  profile_no_items_9: "Some error has occurred, please try again later",
  profile_no_items_10: "The list is empty :(",
  profile_no_items_11: "The search has not given any results",
  profile_open_gift_page_1: "Giver:",
  profile_open_gift_page_2: "Put it on showcase",
  profile_open_gift_page_3: "Accept",
  profile_page_1: "Open predictions:",
  profile_page_2: "Max cookie level:",
  profile_page_3: "Max league level:",
  profile_page_4: "Inventory",
  profile_page_5: "Save",
  profile_page_title: "Profile",
  profile_received_gift_1: "Sender:",
  profile_received_gift_put: "Put",
  profile_received_gift_showcase: "To the showcase",
  profile_received_gift_title: "Open a new gift",
  profile_received_page_1: "Received gifts",
  profile_select_friend_page_1: "Who is the gift for:",
  profile_select_friend_page_2: "Find a friend on the list",
  profile_send_gift_page_1: "Gift",
  profile_send_gift_page_send: "Send",
  profile_user_gifts_1: "Give to a friend",
  profile_user_gifts_2: "Give",
  profile_user_gifts_3: "Gifts received:",
  profile_user_gifts_watch: "View list",
  rating_1: "Find out the results in our",
  rating_2: "official group",
  rating_3: "Who ate more?",
  rating_all: "All time",
  rating_list_1: "No one is here yet",
  rating_list_2: "become the first",
  rating_list_3: "An error has occurred",
  rating_list_4: "no data received, try again later",
  rating_month: "Per month",
  rating_today: "Today",
  rating_week: "In a week",
  store_ad_1: "Something broke, we couldn't give you a reward.",
  store_ad_2: "Alas, you have closed the ad, try again.",
  store_ad_3: "Unfortunately, it was not possible to find an advertisement. Try again later.",
  store_ad_5: "There are no ads right now.",
  store_ad_6: "Try to check on the computer, it happens there more often.",
  store_ad_7: "Just don't forget to disable VPN and ad blocker",
  store_app_authorization_1: "Successful login!",
  store_app_authorization_2: "Welcome",
  store_app_authorization_3: "Do you like this game?",
  store_app_authorization_4: "Have you recorded your data?",
  store_app_authorization_5: "Incorrect Email",
  store_app_authorization_6: "Resending will be available later!",
  store_app_authorization_7: "Great! Your data has been successfully sent to ",
  store_city_buildings_brickyard_1: "Production completed: +",
  store_city_city_1: "Error creating a city. Write to support.",
  store_city_city_2: "Error changing the city. Write to support.",
  store_city_city_3: "Error deleting a city. Write to support.",
  store_city_city_4: "The player is already in another city.",
  store_city_city_5: "The name of the city is too short!",
  store_city_city_6: "Incorrect city name!",
  store_city_city_7: "Incorrect description of the city!",
  store_city_city_8: "Incorrect logo!",
  store_city_city_9: "You don't have enough cookies!",
  store_city_city_10: "You don't have enough bricks!",
  store_city_city_11: "Bad luck, there are still residents in the city!",
  store_city_city_12: "It's a shame, not a hooligan!",
  store_city_city_13: "The invitation already exists!",
  store_city_city_14: "Alas, the city is full!",
  store_city_city_15: "Oh, such a city no longer exists :(",
  store_city_city_16: "Production error!",
  store_city_city_17: "Building donate error!",
  store_city_city_18: "Failure! Unfortunately, this action has ended.",
  store_city_city_19: "Error:",
  store_city_control_1: "Create a city",
  store_city_control_2: "Establish a city",
  store_city_control_3: "Edit Cities",
  store_city_control_4: "Save edits",
  store_city_control_5: "The name of the city cannot be empty!",
  store_city_control_6: "Unknown error",
  store_city_control_7: "Changes have been saved successfully!",
  store_city_tutorial_1: "The buildings on the city map give you bonuses!",
  store_city_tutorial_2: "If you improve them, you will get even more game bonuses and rewards.",
  store_city_tutorial_3: "Here, you can view the ratings of every city resident.",
  store_city_tutorial_4: "Compete with fellow residents to earn rewards!",
  store_city_tutorial_5: "And here is the rating of other cities.",
  store_city_tutorial_6: "Residents should join forces to make their city the best!",
  store_city_tutorial_7: "You can always get more information in the help window.",
  store_city_tutorial_8: "Bricks are needed to improve the city.",
  store_city_tutorial_9: "To produce them, open a brick factory.",
  store_game_battle_1: "Bender",
  store_game_battle_2: "Rodriguez",
  store_game_core_1: "You don't have enough coins!",
  store_game_core_2: "Included is an increase in profit to",
  store_game_core_3: "for",
  store_game_core_4: "hours",
  store_game_core_5: "Profit increase to",
  store_game_core_6: " extended for another",
  store_game_core_7: "hours",
  store_game_core_8: "You can't delete the maximum one!",
  store_game_core_9: "You can't merge the maximum!",
  store_game_main_1: "Failure! You've run out of prizes.",
  store_game_main_2: "Failure! Unfortunately, this sale has ended.",
  store_game_main_3: "New cookie level unlocked! ",
  store_game_main_sack_reward: 'Reward successfully received! +',
  store_game_core_10: "There is no free space",
  store_game_tutorial_battle_1: "Welcome to the training battle, our training opponent will fight with you here!",
  store_game_tutorial_battle_2: "The playing field is presented in front of you.",
  store_game_tutorial_battle_3: "The goal of the game is to merge more cookies than your opponent within 60 seconds.",
  store_game_tutorial_battle_4: "Game play time and count of merges are shown above.",
  store_game_tutorial_battle_5: "Initially, you are given 3500 silver, for which you can buy a liver of level 1 at 100 silver for each.",
  store_game_tutorial_battle_6: "Start merge cookies!",
  store_game_tutorial_battle_7: "It's time to use the Cookie Rain!",
  store_game_tutorial_battle_8: "The Cookie Rain spends 1 cookie from your bet, thereby reducing the reward received, but it gives a good advantage over the opponent, making it easier to win.",
  store_main_main_loading: "loading...",
  store_profile_profile_1: "Write your comment on the gift",
  store_profile_profile_2: "Gifts",
  store_profile_profile_3: "Give",
  store_profile_profile_4: "The gift has been successfully sent!",
  store_profile_profile_5: "Give to a friend",
  store_profile_profile_6: "Give",
  store_profile_profile_7: "give",
  store_profile_profile_grade_1: "Common",
  store_profile_profile_grade_2: "Ordinary",
  store_profile_profile_grade_3: "Rare",
  store_profile_profile_grade_4: "Super rare!",
  store_rating_1: "Per day",
  store_rating_2: "From Monday",
  store_rating_3: "From the 1st",
  store_rating_4: "All time",
  store_shop_1: "We apologize, until the end of moderation, purchases are temporarily unavailable.",
  store_shop_2: "Something went wrong, please try again later.",
  store_shop_3: "Triple Offer",
  store_shop_4: "On your first purchase, get triple the cookies at the regular price!",
  store_shop_5: "Multiply cookies 3x",
  store_shop_6: "You don't have enough cookies!",
  store_shop_7: "Error. Please contact support!",
  store_shop_8: "on sale",
  store_shop_9: "bonus",
  store_shop_10: "and more",
  store_shop_11: "You received",
  store_shop_12: "Have a nice game!",
  store_shop_processing_popup: "Your purchase is still processing!",
  store_user_user_1: "Join a group",
  store_user_user_2: "Subscribe to game notifications",
  store_user_user_3: "Add to favorites",
  store_user_user_4: "Subscribe to game messages",
  store_user_user_5: "Write to the group \"Hello!\"",
  store_user_user_6: "Share on your wall",
  store_wheel_1: "Congratulations!",
  store_wheel_2: "Yippee!",
  store_wheel_3: "Super!",
  store_wheel_4: "Cool!",
  store_wheel_5: "Cool!",
  store_wheel_6: "Success!",
  store_wheel_7: "Fortune!",
  store_wheel_8: "Great!",
  store_wheel_9: "Perfectly!",
  store_wheel_10: "Amazing!",
  store_wheel_11: "Jackpot! ",
  store_wheel_12: "Silver income for 1 hour",
  store_wheel_13: "coins will be credited after entering the game",
  store_wheel_14: "Free Cookie Rain",
  store_wheel_15: "the won attempts are summed up",
  store_wheel_16: "Small prize: +",
  store_wheel_17: "+1 to the Offline Income level",
  store_wheel_18: "Silver income in 2 hours",
  store_wheel_19: "+50 merges in the game",
  store_wheel_20: "conquer the Leagues, get prizes",
  store_wheel_21: "Big Prize: +",
  store_wheel_22: "Free booster",
  store_wheel_23: "Silver income in 30 minutes",
  store_wheel_24: "A gift to the collection",
  store_wheel_25: "you can give it to someone",
  store_wheel_26: "Silver income in 4 hours",
  store_wheel_27: "Looks like you don't have any free tickets left!",
  welcome_but_proceed: "Continue",
  welcome_text: "Get a free cookie and find out when new ones appear!",
  wheel_1: "Try your luck, win the grand prize!",
  wheel_2: "Winners:",
  wheel_ad_play_button_1: "Spin",
  wheel_ad_play_button_2: "For free!",
  wheel_btn_1: "Spin!",
  wheel_btn_2: "The Wheel of Fortune is not yet available.",
  wheel_btn_3: "Come back tomorrow to play!",
  wheel_play_1: "Spin for",
  wheel_title: "Wheel of Fortune",
  wheel_winner_list_item_hour: " h.",
  wheel_winner_list_item_min: " min.",
  wheel_winner_list_item_sec: " sec.",
  wheel_winner_spin_1: "You have won",
  wheel_winner_spin_2: "Get",
  app_emo_status_title: 'Choose your emoji status!',
  app_emo_status_1: 'Appears to the right of your name and will be visible to everyone in ',
  app_emo_status_remove: 'remove status',
  app_emo_status_done: 'Done',
  app_loading_offline_title: 'Technical works' ,
  app_loading_offline_message: 'The application is under maintenance, we apologize.\n\nCome back to us a little later.' ,
  app_loading_agreement_header_1: 'Important!',
  app_loading_agreement_header_2: 'Before you start playing, please read and agree to:',
  app_loading_agreement_checkbox_default: 'I accept the terms of the agreement',
  app_loading_agreement_accept: 'Play',
  app_loading_agreement_decline: 'Leave the game',
  chapter_lvl: 'lvl.',
  chapter_level: 'level',
  chapter_difficulty_easy: 'Easy',
  chapter_difficulty_medium: 'Medium',
  chapter_difficulty_hard: 'Hard',
  chapter_until_refresh: 'Next update',
  chapter_chapter_rank: 'Rank:',
  chapter_chapter_ended: 'Ends in:',
  chapter_chapter_of: 'of',
  chapter_chapter_difficulty_1: 'Get',
  chapter_chapter_difficulty_2: ', to move to a new rank!',
  chapter_chapter_difficulty_3: ', to stay at this rank!',
  chapter_chapter_completed_1: 'This season\'s adventures is over!',
  chapter_chapter_completed_2: 'Come back a little later when the new season starts.',
  chapter_tasks_hourly: 'Gingerbread quests',
  chapter_tasks_daily: 'Daily quests',
  chapter_tasks_weekly: 'Weekly quests',
  chapter_hint_m1: 'Go to the game and buy some cookies for the table through the "Quick Buy" menu or at the "Market".',
  chapter_hint_m2: 'Merge two identical cookies on your game table.',
  chapter_hint_m3: 'Activate the Rocket Booster, which is located in the "Improvements" tab in the game.',
  chapter_hint_m4: 'Start the Cookie Rain in the game. It\'s in the "Improvements" tab.',
  chapter_hint_m5: 'Merge cookies in the game and level up your max cookie.',
  chapter_hint_m6: 'Improve your level of Offline Income in the game, located in the "Improvements" tab.',
  chapter_hint_m7: 'Go to the plates upgrade section ("Improvements" tab) and level up the plate',
  chapter_hint_m8: 'At the end of your League tournament, you must be in 20th place or higher.',
  chapter_hint_m9: 'Visit the game at intervals of more than 24 hours to increase the progress of the quest.',
  chapter_hint_m10: 'When you return to the game, take your offline income coins.',
  chapter_hint_m11: 'Find out your place in the gaming League, check your place again, it needs to change.',
  chapter_hint_m12: 'Start a Cookie Rain and make sure to catch every cookie that falls on the game table.',
  chapter_hint_m13: 'Place on your gaming table the required count of cookies with levels in order.',
  chapter_hint_m14: 'Your game table must contain the required number of cookies with levels in order, from your biggest cookie to the smallest.',
  chapter_hint_m15: 'Activate "prize" Rocket Booster, in cost, "Prize" must be indicated. It is located in the "Improvements" tab in the game.',
  chapter_hint_m16: 'Start a «prize» Cookie Rain in the game. The cost must indicate «Prize».',
  chapter_hint_c1: 'Go to your city and craft some bricks at the «Brick factory».',
  chapter_hint_c2: 'Visit your city, select any building on the map, then add cookies to it.',
  chapter_hint_c3: 'Look into your city, open any building on the map, then add bricks to it.',
  chapter_hint_c4: 'Use any action to get a certain number of points for the rating of the members of the city.',
  chapter_hint_c5: '',
  chapter_hint_c6: 'Return to the city, go to the chat tab and send any message to the city chat.',
  chapter_hint_c7: 'To increase progress, you must visit your city at intervals of more than 24 hours.',
  chapter_hint_f1: 'Open the battles in the game and fight any non-training battle.',
  chapter_hint_f2: 'Play the battle and finish it by defeating your opponent.',
  chapter_hint_f3: 'Play the battle, merge cookies and finish it with over 60 merges.',
  chapter_hint_f4: 'Participate in the battle and finish it with a cookie of at least level 7 on the battle table.',
  chapter_hint_f5: 'Play in different battles and buy cookies on the table for coins, each coin spent counts.',
  chapter_hint_p1: 'Get a prediction by crushing a cookie in any category.',
  chapter_hint_p2: 'Choose any fortune category, except for "Today" and crush the cookie.',
  chapter_hint_p3: 'Received any prediction and share it in any available form.',
  chapter_hint_p4: 'Open any prediction and rate it by clicking on the «Thumbs up» or «Thumbs down» button.',
  chapter_hint_q1: 'Complete any adventures quest and hit the «Take» button to earn experience stars.',
  chapter_hint_q2: 'Complete any «Gingerbread Quest» in the adventures by pressing the «Take» button',
  chapter_hint_q3: 'Press the «Take» button on any completed quest in «Daily quests» of adventures.',
  chapter_hint_q4: 'Complete any task and take experience stars to increasing your level.',
  chapter_hint_q5: 'Speed up the «Gingerbread Quests» with the «Speed Up» button, use all possible speedups per day to increase progress by one.',
  chapter_hint_d1: 'Open the «Wheel of Fortune» and spin it by trying your luck. The fact of torsion is taken into account.',
  chapter_hint_d2: 'Visit your profile section, from anywhere in the app.',
  chapter_hint_d3: 'Send a gift to someone using the buttons: in someone else\'s profile - «Gift» or in your profile - «Gift to a friend».',
  chapter_hint_d4: 'You can ask someone to send you a gift, for example: a friend, a member of the city, or send a gift yourself and wait for a response.',
  chapter_hint_d5: 'Watch any advertisement with a reward, for example: «Quest speedup, «Wheel of Fortune», «+1 cookie», etc.',
  chapter_hint_d6: 'Visit the app at intervals of more than 24 hours to increase your progress.',
  chapter_hint_d7: 'Don’t close the application for the required time. Stay with us a little longer.',
  chapter_hint_d8: 'Spend cookies for any purpose: bonuses, improvements, predictions ..., each cookie spent counts.',
  chapter_hint_d9: 'Get cookies on your balance, for example: in «Adventures», take «Free», win in the «Wheel of Fortune», etc., each cookie counts.',
  chapter_hint_w2: 'Spin the «Wheel of Fortune» using a free try for advertising. Rotation is taken into account only for advertising.',
  chapter_hint_w3: 'Try your luck in the «Wheel of Fortune». Win «Coins» to increase the progress of this task.',
  chapter_hint_w4: 'Open the «Wheel of Fortune», play, if you win the «Gift», the progress will be increased.',
  chapter_next_level_greetings: 'Congratulations!',
  chapter_next_level_proceed: 'Continue',
  chapter_next_level_reward: 'Your Reward',
  chapter_next_level_great: 'Great!',
  chapter_next_level_vip_active: 'Status active',
  chapter_next_level_vip_offer_1: 'Status will allow you',
  chapter_next_level_vip_offer_2: 'claim all rewards',
  chapter_next_level_missed: 'Missed rewards',
  chapter_next_level_more: 'more',
  chapter_next_level_get_vip_1: 'Get status',
  chapter_next_level_get_vip_2: 'to receive ',
  chapter_task_item_reward: 'Reward',
  chapter_task_item_take: 'Claim',
  chapter_task_item_completed: 'Completed',
  chapter_task_item_speedup: 'Speedup',
  chapter_task_item_next: 'Next quest in:',
  chapter_timer_d: 'd.',
  chapter_timer_h: 'h.',
  chapter_timer_m: 'm.',
  chapter_vip_reward_granted: 'Status received!',
  chapter_vip_reward_available: 'Available',
  chapter_vip_reward_missed: 'missed rewards',
  chapter_vip_reward_hint: 'While the status is active, you take receive rewards.',
  chapter_vip_reward_take: 'Receive!',
  chapter_refresh_title: 'Replacing a quest',
  chapter_refresh_message: 'If you don’t like this quest, you can replace it with another randomly selected one.',
  chapter_refresh_actions_1: 'Do you want to try your fortune?',
  chapter_refresh_button: 'Replace for',
  chapter_refresh_back: 'Back',
  city_control_members_term_s: ' s.',
  city_control_members_term_m: ' m.',
  city_control_members_term_h: ' h.',
  city_control_members_term_d: ' d.',
  city_control_requests_term_d: 'd.',
  free_cookies_promo_codes_empty_1: 'You don\'t have promo codes yet :(',
  free_cookies_promo_codes_empty_2: 'Open predictions to receive enjoyable gifts!',
  free_cookies_promo_codes_activate: 'Activate on',
  free_cookies_promo_codes_show_1: 'Show the code in the store',
  free_cookies_promo_codes_show_2: 'to pick up a gift',
  free_cookies_promo_codes_gift_1: 'Activate this promo code',
  free_cookies_promo_codes_gift_2: 'and receive a gift',
  free_cookies_promo_codes_condition: '[conditions]',
  game_counter_soft_vip: 'From VIP-status',
  game_battle_result_exit_title: 'Disqualification',
  game_battle_result_exit_message: 'You exited the battle early and lost:',
  game_task_tracker_season: 'The season is over. There are no quests yet.',
  game_task_tracker_until_next: 'Until the next quest:',
  game_market_title: 'Market',
  game_market_cookies: 'Cookies',
  game_market_coins: 'Coins',
  main_app_banner_promo: 'Promo code',
  main_app_banner_reward: 'Activation reward',
  main_categories_title_1: 'CHOOSE',
  main_categories_title_2: 'FORTUNE CATEGORY',
  main_categories_back: 'Back',
  main_crush_button_more_wishes: 'More wishes',
  main_crush_button_crush_wishes: 'Crush',
  main_crush_button_want_wishes: 'I want wishes!',
  main_crush_button_view_wishes: 'View list',
  main_crush_button_prize_crush: 'Crush',
  main_crush_button_prizes: 'Free count:',
  main_crush_tutorial_share_1: 'Share your fortune with your',
  main_crush_tutorial_share_2: 'friends by sending the',
  main_crush_tutorial_share_3: 'application widget to chats!',
  main_footer_promo: 'Your promo codes',
  main_footer_chapter_1: 'Quests',
  main_footer_chapter_2: 'adventures',
  main_main_cookie_complaint: '[complaint]',
  main_main_cookie_empty_wishes: 'No new wishes.',
  main_main_cookie_count_wishes: 'You have',
  main_share_buttons_sender: 'Who sent?',
  main_share_buttons_reveal: 'Reveal for',
  main_share_buttons_view_1: 'View',
  main_share_buttons_view_2: 'wishes',
  main_share_buttons_to_chat: 'Send to chat',
  modals_complaint_complaint: 'Complain',
  modals_complaint_attention: 'All wishes received from this sender will be deleted and he will not be able to send you new wishes.',
  modals_complaint_blocking_1: 'Block author',
  modals_complaint_blocking_2: 'and remove wishes',
  modals_onboarding_header_1: 'Open fortune cookies with friends through dialogues and chats',
  modals_onboarding_header_2: 'Your friends can share their predictions in the chat',
  modals_onboarding_content_1: 'Share received predictions through story and wall',
  modals_onboarding_content_2: 'And you can send yours back',
  modals_onboarding_ok: 'Good',
  modals_promo_code_bonus_1: 'Gift for activation:',
  modals_promo_code_bonus_ya_1: 'Get a gift for activating a promo code',
  modals_promo_code_bonus_ya_2: '(the period for issuing cookies is 4 days)',
  modals_promo_code_great: 'Great!',
  modals_promo_code_footer_btn_1: 'Your',
  modals_promo_code_footer_btn_2: 'promo codes',
  modals_tester_settings_tutor_mode: 'Test tutorial mode in game',
  modals_tester_settings_skip_ad: 'Skip rewarded ads',
  profile_profile_page_vip_until: 'Active until:',
  profile_profile_page_emo_status_1: 'Emoji',
  profile_profile_page_emo_status_2: 'status',
  profile_profile_page_register: 'Already with a Cookie:',
  shop_pack_item_page_sale: 'Sale',
  shop_pack_item_page_status: 'Status',
  shop_pack_item_page_until_vip: 'Active until',
  shop_pack_item_page_unsubscribe: 'Unsubscribe',
  shop_pack_item_page_unsubscribed: 'Unsubscribed',
  shop_pack_item_page_unavailable: 'While the VIP-status is active, this pack is not available.',
  shop_pack_item_page_cost: 'Price',
  shop_pack_item_page_privacy: 'By clicking button "Get / Receive", you agree with',
  shop_pack_item_page_agreement: 'User Agreement',
  shop_pack_item_page_processing: 'Purchase processing',
  shop_sales_container_bonus_success_1: 'Nice! Gift collected.',
  shop_sales_container_bonus_success_2: 'Visit the store frequently so you don\'t miss out on new gifts and promotions.',
  shop_sales_container_bonus_take: 'Claim',
  shop_sales_container_left: 'Remaining: ',
  shop_shop_page_title: 'Store',
  shop_shop_page_cookies: 'Cookies',
  shop_shop_page_vip: 'VIP Status',
  shop_shop_page_boosters: 'Boosters packs',
  shop_shop_page_hit: 'HIT',
  shop_shop_page_active: 'Active',
  wishes_received_empty_new: 'Crush the cookie to find out your first wish!',
  wishes_received_empty: 'Sorry, your wishlist is empty yet :(',
  wishes_received_more: 'More',
  wishes_received_list_1: 'Wishes',
  wishes_received_list_2: 'list',
  wishes_received_sender: '[who sent]',
  wishes_received_reveal: 'Reveal sender for',
  wishes_received_complaint: '[complaint]',
  wishes_wishes_hint: 'Enter wish text',
  wishes_wishes_todo_1: 'Write a',
  wishes_wishes_todo_2: 'sincere wish',
  wishes_wishes_result_1: 'Wish',
  wishes_wishes_result_2: 'for',
  wishes_wishes_result_3: 'Sent!',
  wishes_wishes_wish: 'Send wish',
  wishes_wishes_get_predict: 'Get a prediction',
  store_ad_limit: 'View limit reached!',
  store_ad_tests: 'Skip ads! The setting is enabled in tests.',
  store_ad_task_reward_error: 'Failed to find task to speedup!',
  store_ad_speed_count: 'Speedup used:',
  store_ad_survey_closed: 'Advertising survey failed, please try again later.',
  store_chapter_info_name: 'Adventures',
  store_chapter_wt: 'Received a non-existent quest id!',
  store_chapter_er_pr: 'Something went wrong with quest progress tracking!',
  store_chapter_task_ready: 'Quest ready!\nHurry to claim experience stars!',
  store_chapter_new_task: 'The new quest is now available!',
  store_chapter_sw: 'Hmm... Something went wrong! ',
  store_chapter_sb: 'Something broke! ',
  store_shop_eb_header: 'SALES',
  store_shop_eb_text: 'New sales and gifts coming soon. Come to the store often so you don\'t miss anything!',
  store_shop_buy_pack: 'Get this pack',
  store_shop_pack_contains: 'PACK CONTAINS',
  store_shop_vip_contains: 'ADVANTAGES',
  store_shop_vip_info_chapter: 'unlocks adventures rewards',
  store_shop_vip_info_free: '+1 free cookie per day',
  store_shop_vip_info_fc: '+1 cookie per day for social tasks',
  store_shop_vip_info_main_ad: '+5 rewarded ads per day',
  store_shop_vip_info_soft: 'x2 to coin income in the game',
  store_shop_vip_info_icon: 'VIP icon in rating',
  store_shop_vip_info_no_ad: 'disabling full-screen and banner ads',
  store_shop_receive_vip: 'Receive status',
  store_shop_prolong_vip: 'Prolong status',
  store_shop_prolonged_vip_1: 'Congratulations!\nYour VIP status has been successfully prolonged by',
  store_shop_prolonged_vip_2: 'days.\n\nHave a good game.',
  store_shop_received_vip_1: 'Congratulations!\nYou have received VIP status on',
  store_shop_received_vip_2: 'days.\n\nHave a good game.',
  store_shop_received_vip_3: 'Congratulations! You got:\n',
  store_shop_received_vip_4: 'days.\n\nHave a good game.',
  store_shop_bu_error: 'This gift has already been received!',
  store_shop_b_error: 'Something went wrong, it was not possible to take the gift.',
  store_shop_sbe: 'Something broke, please try again later.',
  store_shop_unsbce: 'Unsubscribe failed, something went wrong!',
  store_shop_unsbce_vk: 'Unsubscribe failed, VK error',
  store_shop_pack_bonus: ' (gift)',
  store_shop_pack_sale: ' (sale)',
  store_shop_pack_vip: 'VIP-status on ',
  store_wishes_category_name: 'Wishes',
  store_wishes_category_hint: 'Crush the cookie and find out what other people wish you',
  store_wishes_e_empty: 'Hmm, no more wishes!',
  store_wishes_e_bad: 'Please use the censored text for the wish!',
  store_wishes_e_no_user_1: 'Unfortunately,',
  store_wishes_e_no_user_2: 'haven\'t visited the cookie for a long time and it\'s not in the database!',
  store_wishes_e_already_sent: 'already received a wish from you today!',
  store_wishes_e_black: 'does not accept wishes from you!',
  store_wishes_e_no_hard: 'Not enough cookies!',
  store_wishes_e_def: 'Error! ',
  store_wishes_butt_e: 'Button not added, something went wrong',
  store_wishes_butt_suc: 'Now you can receive wishes!',
  store_wishes_butt_del: 'The button for sending wishes has been removed from the profile ;(',
  store_wishes_butt_ue: 'Button not added, some error has occurred!',
  store_wishes_e_sender_uid: 'You can\'t send a wish to yourself!',
  store_wishes_ue: 'Unknown error: ',
  store_wishes_complaint: 'Your complaint has been accepted, the author has blocked all his wishes, removed.',
  store_game_main_es: 'Save game failed!',
  store_game_main_esw: 'Something went wrong! ',
  store_game_main_esb: 'Something broke! ',
  store_game_plates_su: 'Plate successfully upgraded to x',
  store_main_no_prize: 'You\'ve run out of free predictions.',
  store_main_esw: 'Hmm, something went wrong, try again later or write us.',
  store_user_friends_evk: 'Error getting friends list!',
  store_user_status_not_allowed: 'Status not available :(',
  store_user_status_eu: 'Some error has occurred!',
  store_user_status_e_empty: 'No status available!',
  store_user_status_e_not_set: 'Install the status failed, something seems to have gone wrong.',
  store_user_status_e_not_select: 'Select status failed, something went wrong.',
  store_user_status_e_not_remove: 'It was not possible to remove the status, something went wrong.',
  store_user_recommend_app: 'Recommend app',
  store_user_reward_received: 'Hooray! Reward received:',
  store_user_esw_recommend: 'Something went wrong, contact support!',
  store_user_esb_recommend: 'Something broke, please try again later.',
  store_app_invite_text: 'I invite you to open fortune cookies.',
  store_app_invite_button: 'Get predictions',
  store_app_invite_title: 'Invite your friends to break cookies!',
  store_share_error: 'Oh! Something went wrong!',
  share_story_predict_title_1: 'The Cookie',
  share_story_predict_title_2: 'predicting for me:',
  share_story_special_title_1: 'Get daily',
  share_story_special_title_2: 'predictions',
  share_story_special_title_3: 'from a cookie',
  share_story_biggest_title_1: 'I have a new',
  share_story_biggest_title_2: 'cookie',
  share_story_biggest_title_3: 'level!',
  share_story_biggest_title_4: 'Cool game -',
  share_story_biggest_title_5: 'open the link!',
  share_story_special_button: 'Get your prediction',
  share_story_predict_button: 'Get your prediction',
  share_story_biggest_button: 'Play',
  share_wall_predict_title_1: 'The Cookie',
  share_wall_predict_title_2: 'predicted for me:',
  share_wall_special_title_1: 'Get daily',
  share_wall_special_title_2: 'predictions',
  share_wall_special_title_3: 'from a cookie',
  share_wall_biggest_title_1: 'I have a new',
  share_wall_biggest_title_2: 'cookie',
  share_wall_biggest_title_3: 'level!',
  share_wall_biggest_title_4: 'Cool game -',
  share_wall_biggest_title_5: 'open the link!',
  share_wall_special_footer_1: 'What fortune awaits you?',
  share_wall_special_footer_2: 'Hurry up, break open the cookie!',
  share_wall_predict_footer_1: 'What fortune awaits you today?',
  share_wall_predict_footer_2: 'Hurry up, break open the cookie!',
  share_wall_biggest_footer_1: 'Play game, merge cookies',
  share_wall_biggest_footer_2: 'Receive predictions',
  share_wall_biggest_footer_3: 'from Fortune Cookie!',
  share_wall_achievements_footer_1: 'Play game, get achievements',
  share_wall_achievements_footer_2: 'Receive predictions',
  share_wall_achievements_footer_3: 'from Fortune Cookie!',
  special_predict: 'You\'ll be happy',
  achievement_name_1: 'Fanboy',
  achievement_description_1: 'Log in to the app',
  achievement_hint_1: 'To increase your achievement progress - just log into the app, but not too often.',
  achievement_name_2: 'Baker',
  achievement_description_2: 'Claim "Offline Income"',
  achievement_hint_2: 'Get in the game and pick up the offline income that has accumulated while you\'ve been away.',
  achievement_name_3: 'Confectioner',
  achievement_description_3: 'Buy cookies for the table',
  achievement_hint_3: 'Go to the game and buy cookies for your game table, every cookie will be accounted for.',
  achievement_name_4: 'Сulinarian',
  achievement_description_4: 'Merge cookies together',
  achievement_hint_4: 'Merge identical cookies on your game table to increase your progress.',
  achievement_name_5: 'Unstoppable',
  achievement_description_5: 'Activate "Rocket Boosters"',
  achievement_hint_5: 'Activate the "Rocket boosters", it can be found in the "Improvements" tab in the game.',
  achievement_name_6: 'Thor',
  achievement_description_6: 'Start a "Cookie Rain"',
  achievement_hint_6: 'Start a "Cookie Rain" in the game. The button is located in the "Improvements" tab.',
  achievement_name_7: 'Potter',
  achievement_description_7: 'Upgrade the "Plates"',
  achievement_hint_7: 'Go to the plate upgrades section ("Improvements» tab) and upgrade your plate levels.',
  achievement_name_8: 'Oracle',
  achievement_description_8: 'Open fortunes',
  achievement_hint_8: 'Crush cookies in any category - get your predictions to increase achievement progress.',
  achievement_name_9: 'Reporter',
  achievement_description_9: 'Share everything',
  achievement_hint_9: 'Share on your page a prediction, a new cookie level, or an achievement received. No more than once in a few hours.',
  achievement_name_10: 'Santa Claus',
  achievement_description_10: 'Send gifts to others',
  achievement_hint_10: 'Send gifts to someone using the buttons: in someone else\'s profile - "Gift" or in your profile - "Gift to a friend".',
  achievement_name_11: 'Prize Segment',
  achievement_description_11: 'Spin the "Wheel of Fortune"',
  achievement_hint_11: 'Open the "Wheel of Fortune" and just spin it. Every spin counts.',
  achievement_name_12: 'Lucky Guy',
  achievement_description_12: 'Win a "Prize" with cookies',
  achievement_hint_12: 'Spin the "Wheel of Fortune" - if a Small Prize, Big Prize or Jackpot is hit, progress will be increased.',
  achievement_name_13: 'Big Score',
  achievement_description_13: 'Win a "Jackpot"',
  achievement_hint_13: 'Spin the "Wheel of Fortune", catch luck by the tail by winning the Jackpot.',
  achievement_name_14: 'Masonry Worker',
  achievement_description_14: 'Produce "Bricks"',
  achievement_hint_14: 'Create bricks at your town\'s "Brick Factory". Every brick will be accounted for.',
  achievement_name_15: 'Capitalist',
  achievement_description_15: 'Win cookies',
  achievement_hint_15: 'Play "Wheel of Fortune", win cookies and progress will be increased by the count of cookies.',
  achievement_name_16: 'Collector',
  achievement_description_16: 'Collect sacks of coins',
  achievement_hint_16: 'Show your wit and catch the sack falling on the game table, pick up its coins and your progress will be increased.',
  achievement_name_17: 'Adventurer',
  achievement_description_17: 'Reach level 45 in adventures',
  achievement_hint_17: 'Participate in "Adventures", get experience, level up to complete this achievement.',
  achievement_name_18: 'Finicky',
  achievement_description_18: 'Replace quests adventures',
  achievement_hint_18: 'Open "Adventures" and replace any quest you don\'t like.',
  achievement_name_19: 'Stargazer',
  achievement_description_19: 'Collect stars in adventures',
  achievement_hint_19: 'Complete any Adventure quests and hit the "Take" button to get experience stars.',
  achievement_name_20: 'Medallist',
  achievement_description_20: 'Become a prize winner of rating',
  achievement_hint_20: 'Open the predictions and earn any reward in the rating "Who ate more?", progress will increase after the "rewarding" is done.',
  achievements_congratulations_bronze: 'Bronze',
  achievements_congratulations_silver: 'Silver',
  achievements_congratulations_gold: 'Gold',
  achievements_congratulations_brilliant: 'Brilliant',
  achievements_page_title_other: 'Achievements',
  achievements_page_title_my: 'My achievements',
  achievements_page_all_progress: 'Overall progress',
  achievements_my_have: 'Have',
  achievements_my_take: 'Take',
  achievements_my_reward: 'Reward',
  achievements_my_from: 'out of',
  achievements_my_gallery: 'Gallery',
  achievements_my_slot: 'Spot',
  achievements_gallery_heading: 'Pick a spot',
  achievements_gallery_pick: 'Pick',
  achievements_gallery_switch: 'Switch',
  achievements_gallery_delete: 'Delete',
  achievements_gallery_show: 'show all',
  achievements_gallery_empty: 'Empty spot',
  achievements_congratulations_great: 'Great!',
  achievements_congratulations_achiev: 'achievement',
  achievements_congratulations_cool: 'Cool',
  achievements_congratulations_times: 'times',
  store_user_achievements_error: 'Achievements. Something went wrong! ',
  achievements_story_have: 'I HAVE',
  achievements_story_achievement: 'ACHIEVEMENT!',
  achievements_story_want: 'Want it too?',
  achievements_story_hurryup: 'Hurry up to play!',
  achievements_story_button: `Let's go for achievements`,
};

export {english};