const italian = {
  app_name: 'Biscotto',
  anonymous: 'Anonimo',
  request_error: 'Qualcosa è andato storto! ',
  request_failure: 'Si è rotto qualcosa! ',
  app_email_1: 'Hai registrato i tuoi dati?',
  app_email_2: 'Inserisci il tuo indirizzo e-mail e clicca su invia.',
  app_email_3: 'Ottieni il tuo login e la tua password per poter ritornare sempre al gioco!',
  app_email_4: 'Invia',
  app_email_5: 'La tua e-mail',
  app_settings_title: 'Impostazioni',
  app_settings_music: 'Musica',
  app_settings_music_bg: 'Riproduzione in modalità ridotta',
  app_settings_sounds: 'Suoni',
  app_settings_rain: 'Velocità di pioggia di biscotti',
  app_settings_notify: 'Notificazioni',
  app_settings_wishes: 'Desideri',
  app_settings_extra: 'Opzioni extra',
  app_settings_user_agreement: 'Accordo con l’utente',
  app_welcome_1: 'Ciao!',
  app_welcome_2: 'Registrazione completata',
  app_welcome_3: 'Login:',
  app_welcome_4: 'Password:',
  app_welcome_5: 'Memorizziamo i tuoi dati su questo dispositivo, finché esiste non perderai i tuoi progressi!',
  app_welcome_6: 'OK, giocare!',
  app_welcome_7: 'Hai già un login?',
  app_welcome_8: 'Inserisci i tuoi dati per continuare il gioco!',
  app_welcome_9: 'Inserire i dati!',
  app_welcome_10: 'Accedere al gioco',
  app_welcome_11: 'Login',
  app_welcome_12: 'Password',
  app_welcome_13: 'Entrare',
  city_buildings_bank_1: 'Banca della città',
  city_buildings_bank_2: 'Livello:',
  city_buildings_bank_3: 'Determina il numero di biglietti premio nella valutazione dei residenti della città che hanno totalizzato il numero di punti richiesto',
  city_buildings_bank_4: 'Caratteristiche',
  city_buildings_bank_5: 'Requisito',
  city_buildings_bank_6: 'Ora:',
  city_buildings_bank_7: 'punti',
  city_buildings_bank_8: 'Avanti:',
  city_buildings_brickyard_1: 'Fabbrica di mattoni',
  city_buildings_brickyard_2: 'Permette la produzione di mattoni necessari per la costruzione e il miglioramento degli edifici cittadini',
  city_buildings_brickyard_3: 'Produzione',
  city_buildings_brickyard_4: 'Selezionare l’importo:',
  city_buildings_brickyard_5: 'TOTALE:',
  city_buildings_brickyard_6: 'Produrre',
  city_buildings_brickyard_7: 'Limite di produzione:',
  city_buildings_brickyard_8: 'pz.',
  city_buildings_brickyard_9: 'Condizioni di produzione',
  city_buildings_brickyard_10: 'Il costo di un mattone',
  city_buildings_brickyard_11: 'Azzeramento del limite',
  city_buildings_brickyard_12: 'una volta al giorno',
  city_buildings_brickyard_13: 'Produzione interrotta',
  city_buildings_brickyard_14: 'il limite giornaliero è stato raggiunto',
  city_buildings_brickyard_15: 'Miglioramento',
  city_buildings_brickyard_balance: 'Totale monete',
  city_buildings_buildings_1: 'Aggiunto all’edificio ',
  city_buildings_cafe_1: 'Caffetteria',
  city_buildings_cafe_2: 'Aumenta il numero di biscotti che cadono nella pioggia di biscotti',
  city_buildings_cafe_3: 'Incremento attuale:',
  city_buildings_cafe_4: 'Dopo il miglioramento:',
  city_buildings_cafe_5: 'pz.',
  city_buildings_candy_factory_1: 'Fabbrica di dolci',
  city_buildings_candy_factory_2: 'Permette di aumentare il tempo di funzionamento dei Booster quando viene attivato',
  city_buildings_candy_factory_3: 'Aumento del tempo:',
  city_buildings_candy_factory_4: 'min.',
  city_buildings_city_hall_1: 'Municipio',
  city_buildings_city_hall_2: 'Responsabile del numero massimo di residenti (partecipanti) nella città',
  city_buildings_city_hall_3: 'Limite corrente:',
  city_buildings_city_hall_4: 'residenti',
  city_buildings_city_hall_5: 'Dopo il miglioramento:',
  city_buildings_mill_1: 'Mulino',
  city_buildings_mill_2: 'Aumenta la possibilità di far cadere un biscotto di livello superiore durante la pioggia di biscotti',
  city_buildings_mill_3: 'Possibilità è stata aumentata:',
  city_buildings_mill_4: 'a',
  city_buildings_success_1: 'La costruzione è stata completata!',
  city_buildings_success_2: 'Il livello dell’edificio è stato portato a',
  city_buildings_success_3: '',
  city_buildings_success_4: 'L’efficienza è stata aumentata!',
  city_buildings_success_5: 'Ottimo!',
  city_buildings_success_6: 'Limite di produzione',
  city_buildings_success_7: 'Limite di residenti nella città:',
  city_buildings_success_8: 'Premi e requisiti',
  city_buildings_success_9: 'Requisito',
  city_buildings_success_10: 'punti',
  city_buildings_success_11: 'Biscotti sotto la pioggia di biscotti:',
  city_buildings_success_12: 'Possibilità di far cadere un biscotto di livello superiore:',
  city_buildings_success_13: 'Tempo di funzionamento del Booster:',
  city_buildings_success_14: 'Edificio non trovato!',
  city_buildings_upgrade_1: 'Miglioramento',
  city_buildings_upgrade_2: 'Il livello massimo è stato raggiunto',
  city_buildings_upgrade_3: 'Sono necessari i biscotti',
  city_buildings_upgrade_4: 'Sono necessari mattoni',
  city_buildings_upgrade_5: 'Comprare',
  city_buildings_upgrade_6: 'Produrre',
  city_buildings_upgrade_7: 'Aggiungere',
  city_buildings_upgrade_8: 'Non ci sono abbastanza biscotti!',
  city_buildings_upgrade_9: 'Non ci sono abbastanza mattoni!',
  city_buildings_upgrade_10: 'Aspettando i mattoni',
  city_buildings_upgrade_11: 'Aspettando i biscotti',
  city_buildings_upgrade_12: 'Progresso:',
  city_chat_1: 'Il tuo messaggio...',
  city_chat_2: 'Un nuovo messaggio nella chat della città!',
  city_chat_3: 'Alcuni nuovi messaggi nella chat della città!',
  city_city_panel_1: 'Non sei ancora unito alla città',
  city_city_panel_2: 'Il tuo saldo',
  city_city_panel_3: 'mattoni',
  city_city_panel_4: 'biscotti',
  city_city_panel_5: 'online:',
  city_control_changes_1: 'Avatar - scegli un’immagine per la tua città. Alcune di esse potranno essere sbloccate in seguito',
  city_control_changes_2: 'Visualizzare e selezionare',
  city_control_changes_3: 'Nome - un nome censurato, attraente e memorabile della vostra città',
  city_control_changes_4: 'Descrizione - una breve descrizione censurata della vostra città, potete lasciarla vuota',
  city_control_changes_5: 'Accessibilità - scegliete il tipo di accessibilità sociale della vostra città.',
  city_control_changes_6: 'Pubblico',
  city_control_changes_7: '- visibile a tutti nell’elenco delle città casuali;',
  city_control_changes_8: '- qualsiasi giocatore può unirsi alla tua città;',
  city_control_changes_9: 'Privato',
  city_control_changes_10: '- non visibile nell’elenco delle città casuali;',
  city_control_changes_11: '- il giocatore si unisce alla città solo dopo la vostra approvazione;',
  city_control_changes_12: 'biscotti',
  city_control_changes_13: 'Promozione, rimasto: ',
  city_control_control_1: 'Dopo essere uscito, non si potrà aderire a un’altra città per un giorno!',
  city_control_control_2: 'Sei il sindaco di questa città e non puoi lasciare la tua città finché ci sono altri residenti!',
  city_control_control_3: 'Lasciare la città',
  city_control_control_4: 'Qui si può lasciare la città in cui si risiede attualmente.\r\nSe si lascia la città, si perdono tutti i suoi vantaggi',
  city_control_control_5: 'Lasciare la città',
  city_control_logo_1: 'Impostazione',
  city_control_logo_2: 'di un avatar',
  city_control_logo_3: 'Casuale',
  city_control_logo_4: 'Salvare',
  city_control_members_1: 'Residenti della città',
  city_control_members_2: 'In una settimana',
  city_control_members_3: 'Per tutto il tempo',
  city_control_members_4: 'Aprire il profilo',
  city_control_members_5: 'Cacciare dalla città',
  city_control_notes_1: 'Scrivete qui tutto ciò che volete, ad esempio saluti, notizie, regole, istruzioni, desideri. Questo testo sarà visto da tutti i residenti della vostra città',
  city_control_notes_2: 'Codice città',
  city_control_notes_3: 'Scrivere',
  city_control_notes_4: 'Annullare',
  city_control_notes_5: 'Salvare',
  city_control_requests_1: 'Nessuna',
  city_control_requests_2: 'Applicazioni per l’adesione',
  city_control_requests_3: 'la domanda è approvata',
  city_control_summary_1: 'Sommario della città',
  city_control_summary_2: 'Informazione',
  city_control_summary_3: 'Sindaco:',
  city_control_summary_4: 'Residenti in città:',
  city_control_summary_5: 'Data di fondazione:',
  city_control_summary_6: 'di',
  city_control_summary_7: 'Attività della settimana',
  city_control_summary_8: 'Punti ricevuti:',
  city_control_summary_9: 'Accoppiamenti effettuati:',
  city_control_summary_10: 'Edifici',
  city_control_summary_11: 'Livello:',
  city_control_summary_12: 'Mattoni:',
  city_control_summary_13: 'Biscotti:',
  city_control_summary_14: 'd.',
  city_control_summary_15: 'max',
  city_header_1: 'Chat',
  city_help_page_1: '1. Cos’è una città?',
  city_help_page_2: 'Si tratta di una meccanica sociale che permette di fare squadra con altri giocatori e ottenere ottimi bonus.',
  city_help_page_3: '2. Cosa posso fare in città?',
  city_help_page_4: 'Chattare, migliorare gli edifici della città, competere con altri residenti e città per ottenere bonus. L’elenco crescerà.',
  city_help_page_5: '3. Perché migliorare gli edifici?',
  city_help_page_6: 'Ogni edificio dà un bonus unico.',
  city_help_page_7: 'Ad esempio, la Caffetteria aumenta il numero di biscotti che cadono durante la Pioggia dei biscotti e la Fabbrica di dolci aumenta la durata del Rocket Booster.',
  city_help_page_8: '4. Come migliorare gli edifici?',
  city_help_page_9: 'Gli edifici si migliorano in cambio di biscotti e mattoni.',
  city_help_page_10: 'I mattoni sono la moneta della città, si comprano in una fabbrica di mattoni in cambio di argento.',
  city_help_page_11: 'Il costo dei mattoni per tutti i giocatori è uguale e si misura in ore di reddito.',
  city_help_page_12: '5. Chi è il sindaco?',
  city_help_page_13: 'Il sindaco è il creatore della città.',
  city_help_page_14: 'Può modificare l’avatar, il nome, la descrizione e la privacy della città.',
  city_help_page_15: 'È nel suo potere accogliere e cacciare i residenti.',
  city_help_page_16: 'Vede il contributo di ogni residente.',
  city_help_page_17: 'Il ruolo di sindaco non può essere trasferito a un altro residente.',
  city_help_page_18: '6. Perché abbiamo bisogno di una classifica dei residenti?',
  city_help_page_19: 'I residenti più attivi ricevono biglietti per la Ruota della Fortuna dopo ogni fine settimana.',
  city_help_page_20: 'I premi e i requisiti dipendono dal livello di miglioramento della banca.',
  city_help_page_21: 'Per ottenere i biglietti per la Ruota della Fortuna, è necessario ottenere almeno 100 punti di contributo.',
  city_help_page_22: 'I primi 3 residenti ricevono premi maggiori.',
  city_help_page_23: '7. Come ottenere punti per la classifica dei residenti?',
  city_help_page_24: 'I punti si sommano al numero di mattoni e biscotti investiti per migliorare gli edifici.',
  city_help_page_25: '1 punto per 1 mattone.',
  city_help_page_26: '10 punti per 1 biscotto.',
  city_help_page_27: '8. Perché abbiamo bisogno delle classifiche delle città?',
  city_help_page_28: 'La classifica si basa sulla somma delle connessioni dei biscotti tra tutti i residenti della città.',
  city_help_page_29: 'Permette di aumentare la popolarità della città e di attirare i giocatori più attivi.',
  city_help_page_30: 'Aiuto',
  city_help_page_31: 'Domande frequenti',
  city_leaders_1: 'Settimanale',
  city_leaders_2: 'Mensile',
  city_leaders_3: 'Totale',
  city_leaders_4: 'Classifica delle città',
  city_members_1: 'Classifica dei residenti',
  city_members_2: 'Regole di classifica',
  city_members_rules_1: 'Regole',
  city_members_rules_2: 'La classifica si basa sui punti che i residenti possono ottenere per aver giocato e sostenuto attivamente la loro città.',
  city_members_rules_3: 'Per cosa si possono ottenere punti:',
  city_members_rules_4: '- portare mattoni all’edificio',
  city_members_rules_5: '1 mattone =',
  city_members_rules_6: 'punto',
  city_members_rules_7: '- portare i biscotti nell’edificio',
  city_members_rules_8: '1 biscotto =',
  city_members_rules_9: 'punti',
  city_members_rules_10: 'Nella classifica settimanale, i residenti hanno la possibilità di ottenere preziosi premi.',
  city_members_rules_11: 'Per aumentare il numero di premi, migliorare la Banca della città.',
  city_no_items_1: 'Errore, riprovare più tardi',
  city_no_items_2: 'La lista è vuota :(',
  city_overview_page_1: 'Privato',
  city_overview_page_2: 'Pubblico',
  city_overview_page_3: 'Descrizione',
  city_overview_page_4: 'Aderire',
  city_overview_page_5: 'Inviare un’applicazione',
  city_overview_page_6: 'Informazioni sulla città',
  city_overview_page_7: 'Informazioni',
  city_overview_page_8: 'Tipo:',
  city_overview_page_9: 'Residenti:',
  city_overview_page_10: 'Fondato:',
  city_overview_page_11: 'g.',
  city_overview_page_12: 'Edifici',
  city_overview_page_13: 'Municipio:',
  city_overview_page_14: 'livello',
  city_overview_page_15: 'Banca della città:',
  city_overview_page_16: 'Caffetteria:',
  city_overview_page_17: 'Fabbrica di dolci:',
  city_overview_page_18: 'Mulino:',
  city_overview_page_19: 'di',
  city_overview_page_20: 'Fabbrica di mattoni:',
  city_buttons_join: 'Aderire',
  city_buttons_join_req: 'Inviare la richiesta',
  city_buttons_revoke: 'Cancellare la richiesta',
  city_join_is_full: 'Purtroppo ci sono troppi residenti in quella città!',
  city_join_cooldown: 'Il tempo di attesa per cambiare città non è ancora trascorso!',
  city_search_invites: 'Sei invitato',
  city_search_random_1: 'Città casuali',
  city_search_random_2: 'Le vostre richieste',
  city_search_search_1: 'Creare una città',
  city_search_search_panel_1: 'Niente trovato',
  city_search_search_panel_2: 'Digitare qualcosa e cliccare su trova',
  city_search_search_panel_3: 'Cercare le città',
  city_search_search_panel_4: 'Cercare',
  city_search_search_panel_5: 'Nome...',
  city_tutorial_free_panel_1: 'Probabilmente non ci sono ancora città libere.',
  city_tutorial_free_panel_2: 'Crea la tua propria città gratuitamente!',
  city_tutorial_free_panel_3: 'Aderisci alla città che ti piace o crea la tua propria per i biscotti!',
  city_tutorial_free_panel_4: 'Città libere',
  city_tutorial_free_panel_5: 'Aderire',
  city_tutorial_hints_1: 'OK',
  city_tutorial_tutorial_1: 'Crea la tua propria città',
  city_welcome_page_1: 'Benvenuto',
  city_welcome_page_2: 'nella tua propria città!',
  city_welcome_page_3: 'Ora sei il sindaco, il proprietario della città',
  city_welcome_page_4: 'Invita i giocatori nella tua città, chatta con gli abitanti della città, migliora gli edifici e ottieni bonus nel gioco.\r\nRaggiungi posizioni di rilievo nella classifica delle altre città!',
  city_welcome_page_5: 'È arrivato il momento di un buon governante. Rendi la tua città la migliore!',
  city_welcome_page_6: 'Avanti!',
  city_welcome_page_7: 'alla città',
  city_welcome_page_8: 'Migliora gli edifici e ottieni bonus nel gioco,\r\nchatta con gli altri residenti nella chat e\r\ncompeti con altre città',
  city_welcome_page_9: 'Sii un residente esemplare della città :)',
  cookies_shop_item_1: 'Crea',
  cookies_shop_item_2: ' livello',
  cookies_shop_item_buy: 'Acquistare per:',
  cookies_shop_item_sec: '/sec',
  cookies_shop_title: 'Negozio',
  crush_btn: 'Schiacciare',
  extra_menu_battle: 'Battaglia',
  extra_menu_my_city: 'La mia città',
  free_cookies_1: 'Completa i compiti e raccogli la ricompensa qui ogni giorno!',
  free_cookies_2: 'Fai repost e ricevi il pagamento per ogni nuovo giocatore che arriva attraverso i tuoi link',
  free_cookies_3: 'solo per chi non ha mai aperto l’app prima e schiaccerà almeno tre biscotti',
  free_cookies_4: 'Invita i tuoi amici e raccogli qui i biscotti quando loro iniziano a giocare!',
  free_cookies_5: 'per ognuno!',
  free_cookies_6: 'solo per chi non ha mai aperto l’app prima e schiaccerà almeno tre biscotti',
  free_cookies_vk_2: 'Fai repost, invita amici e ricevi per ogni nuovo giocatore che arriva attraverso i tuoi link',
  free_cookies_vk_3: 'solo per gli amici che non hanno mai aperto l’ applicazione prima e che schiacceranno almeno tre biscotti',
  free_cookies_get: 'Prendere',
  free_cookies_gifts: 'Regali',
  free_cookies_in_day: 'al giorno',
  free_cookies_invite: 'Invitare un amico',
  free_cookies_perform: 'Eseguire',
  free_cookies_promo: 'I tuoi codici promozionali',
  free_cookies_promo_codes_active: 'Attivo fino a ',
  free_cookies_promo_codes_copy: 'Codice promozionale copiato nella clipboard',
  free_cookies_promo_codes_send: 'Inviare',
  free_cookies_promo_codes_title: 'Codici promozionali',
  free_cookies_received: 'Ricevuto',
  free_cookies_story: 'Condividi nella storia',
  free_cookies_wall: 'Condividi sul muro',
  free_cookies_share: 'Condividere il gioco',
  game_Free: 'Gratuito',
  game_rain_enabled: 'Attivato!',
  game_for_prize: 'Premio!',
  game_rain: 'Pioggia di biscotti',
  game_rocket: 'Booster',
  game_freezer: 'Fissazione dei prezzi',
  game_freezer_enabled: 'Attivo!',
  game_sale: 'Promozione',
  game_shop: 'Mercato',
  game_battle_leaders_1: 'I migliori di oggi',
  game_battle_leaders_2: 'Premio',
  game_battle_lobby_close: 'chiudere',
  game_battle_lobby_connection: 'Connessione...',
  game_battle_lobby_duel: 'Competizione',
  game_battle_lobby_go: 'Avanti!',
  game_battle_lobby_training: 'Battaglia di allenamento',
  game_battle_merge_1: 'Accoppia i biscotti il più rapidamente possibile, supera l’avversario nel numero di biscotti accoppiati.',
  game_battle_merge_2: 'Vinci la sua scommessa!',
  game_battle_merge_3: 'Scegli una scommessa per il gioco:',
  game_battle_merge_cookie: 'Biscotto',
  game_battle_result_1: 'Ancora una volta!',
  game_battle_result_close: 'chiudere',
  game_battle_result_cookie: 'biscotto',
  game_battle_result_draw_mess: 'Hai restituito:',
  game_battle_result_draw_title: 'Pareggio!',
  game_battle_result_loss_mess: 'Hai perso:',
  game_battle_result_loss_title: 'Sconfitta!',
  game_battle_result_win_mess: 'Hai ricevuto:',
  game_battle_result_win_title: 'Vittoria!',
  game_battle_select_rival_1: ' Ricerca di un avversario',
  game_battle_select_rival_2: 'cerchiamo nei magazzini del server',
  game_battle_select_rival_3: 'cancellare',
  game_battle_tutorial_next: 'Avanti',
  game_battle_tutorial_res_1: 'Evviva, la vittoria è tua! È ora di giocare con un vero avversario!',
  game_battle_tutorial_res_2: 'Vittoria!',
  game_battle_tutorial_res_3: 'Va tutto bene! Prova a completare di nuovo la formazione!',
  game_battle_tutorial_res_4: 'Sconfitta!',
  game_battle_tutorial_res_5: 'Pareggio!',
  game_battle_tutorial_res_6: 'chiudere',
  game_battle_tutorial_res_7: 'La formazione è finita!',
  game_battle_tutorial_res_8: 'Tornare indietro',
  game_cookie_rain_layer_1: 'Affrettati ad accoppiare',
  game_cookie_rain_layer_2: 'biscotti!',
  game_cookie_rain_layer_3: 'Fai spazio',
  game_cookie_rain_layer_4: 'per la Pioggia di Biscotti',
  game_cost: 'Costo',
  game_counter_soft_1: 'Dal booster',
  game_counter_soft_sec: '/s',
  game_leagues: 'Leghe',
  game_leagues_tutorial_1: 'Congratulazioni\nper aver sbloccato le Leghe!',
  game_leagues_tutorial_2: 'Si tratta di una competizione con altri giocatori per',
  game_leagues_tutorial_2_1: 'biscotti premio',
  game_leagues_tutorial_3: 'Va bene',
  game_leagues_tutorial_4: 'Accoppiando i biscotti si ottengono',
  game_leagues_tutorial_4_1: 'punti di accoppiamenti',
  game_leagues_tutorial_5: 'Gli altri giocatori non non si soffermano e ottengono anche i loro punti da accoppiamenti.',
  game_leagues_tutorial_6: 'Capito',
  game_leagues_tutorial_7: 'La Lega dura una settimana, questo timer mostra',
  game_leagues_tutorial_7_1: 'il tempo che manca alla sua conclusione',
  game_leagues_tutorial_8: 'Affrettati a raggiungere',
  game_leagues_tutorial_8_1: 'i primi dieci',
  game_leagues_tutorial_8_2: 'giocatori della tua Lega.',
  game_leagues_tutorial_9: 'Ottieni',
  game_leagues_tutorial_9_1: 'biscotti',
  game_leagues_tutorial_9_2: 'e passa alla prossima,',
  game_leagues_tutorial_9_3: 'lega più forte',
  game_leagues_tutorial_10: 'Cominciare ad accoppiare!',
  game_main_am_unlock_rain: 'Serve un biscotto di livello 5!',
  game_main_am_unlock_rocket: 'Richiesto un biscotto di livello 6!',
  game_main_am_unlock_freezer: 'Ottieni un biscotto di livello 9!',
  game_main_am_unlock_income: 'Sbloccato al livello 7!',
  game_main_am_unlock_plates: 'Richiesto un biscotto di livello 8!',
  game_main_biggest_1: 'Congratulazioni!',
  game_main_biggest_2: 'Un nuovo livello di biscotti!',
  game_main_biggest_3: 'Ottimo!',
  game_main_left_menu_1: 'Città',
  game_main_left_menu_2: 'Battaglia',
  game_main_left_menu_3: 'Lega',
  game_main_left_menu_4: 'Mercato',
  game_main_left_menu_leagues: 'Per sbloccare le Leghe,\ndevi ottenere un biscotto di livello 7!',
  game_main_left_menu_city: 'Le città saranno disponibili\ndopo di aver ottenuto un biscotto di livello 10!',
  game_main_rain_3: 'Provoca una Pioggia di Biscotti sopra il tuo tavolo da gioco',
  game_main_rain_4: 'Avvio',
  game_main_rocket_1: 'Attiva il reddito turbo per alcune ore',
  game_main_rocket_2: 'Attivare',
  game_main_freezer_desc: 'Basta con l’aumento dei prezzi per l’acquisto di biscotti con le monete!',
  game_main_freezer_enable: 'Fare domanda a',
  game_main_tab_1: 'Miglioramenti',
  game_main_tab_2: 'Acquisto rapido',
  game_main_sack_take: 'Prendere',
  game_main_tutor_1: 'Accoppia i biscotti identici',
  game_main_tutor_2: 'Compra dei biscotti per il tavolo',
  game_main_tutor_3: 'Ottieni un biscotto di livello 4',
  game_main_tutor_4: 'Ciao!',
  game_main_tutor_5: 'Lo scopo del gioco è',
  game_main_tutor_6: 'accoppiare i biscotti',
  game_main_tutor_7: 'per sbloccare nuovi fantastici biscotti!',
  game_main_tutor_8: 'Cominciamo ad accoppiare e vediamo cosa succede.',
  game_main_tutor_9: 'Forza!',
  game_main_tutor_10: 'Acquisto!',
  game_main_tutor_11: 'Ottimo! Ma non c’è nient’altro da accoppiare',
  game_main_tutor_12: 'Bisogna',
  game_main_tutor_13: 'comprare altri biscotti per il tavolo',
  game_main_tutor_14: 'così possiamo continuare a giocare!',
  game_main_tutor_15: 'Acquistiamoli attraverso il menu di Acquisto Rapido.',
  game_main_tutor_16: 'Avanti!',
  game_main_tutor_17: 'Monete!',
  game_main_tutor_18: 'Ogni biscotto sul tavolo',
  game_main_tutor_19: 'guadagna',
  game_main_tutor_20: 'monete.',
  game_main_tutor_21: 'Più alto è il livello del biscotto, più monete',
  game_main_tutor_22: 'guadagna al secondo',
  game_main_tutor_23: 'Accoppia i biscotti che hai comprato per ottenere un nuovo livello!',
  game_main_tutor_24: 'Capito!',
  game_main_tutor_25: 'Ottimo!',
  game_main_tutor_26: 'Continua a giocare, compra e accoppia i biscotti, sblocca nuovi livelli.',
  game_main_tutor_27: 'Completa i compiti e ottieni',
  game_main_tutor_28: 'premi',
  game_main_tutor_29: ', sfrutta vari miglioramenti!',
  game_main_tutor_30: 'Sblocca',
  game_main_tutor_31: 'le Leghe',
  game_main_tutor_32: 'e compete per',
  game_main_tutor_33: 'i premi',
  game_main_tutor_34: 'con gli altri giocatori!',
  game_main_tutor_35: 'Giocare!',
  game_income: 'Reddito offline',
  game_income_max: 'Livello massimo',
  game_income_description: 'Guadagna ancora più monete d’argento quando non sei in gioco!',
  game_income_level: 'Livello',
  game_income_upgrade: 'Migliorare',
  game_income_prize: 'Premio!',
  game_leagues_1: 'vincitori ricevono biscotti',
  game_leagues_2: ' vincitori passano a una nuova Lega e ricevono biscotti',
  game_leagues_3: 'Zona di retrocessione della Lega',
  game_plates_footer_1: 'Migliora i piatti per aumentare il reddito generato dai biscotti che vi si trovano sopra!',
  game_plates_footer_2: 'Metti i biscotti migliori sui piatti migliori!',
  game_plates_footer_done: 'Fatto',
  game_plates_plates_sale: 'La promozione terminerà tra:',
  invite_invite_1: 'Sembra che tutti i tuoi amici stiano già giocando ai biscotti',
  invite_invite_2: 'Si è verificato un errore, riprovare più tardi',
  invite_invite_3: 'Chiama i tuoi amici e ricevi una ricompensa quando iniziano a giocare e aprono almeno tre biscotti',
  invite_invite_title: 'Mail',
  invite_list_item_invite: 'Invitare',
  invite_list_item_invited: 'Invitato',
  league_bronze: 'Lega di bronzo',
  league_gold: ' Lega d’oro',
  league_platinum: 'Lega di Platino',
  league_ruby: 'Lega del Rubino',
  league_silver: 'Lega d’argento',
  loading_1: 'caricamento dei dati',
  main_ad_video_rb_view: 'Guardare!',
  main_ad_video_rb_limit: 'Inattivo \nfino a domani',
  main_ad_video_rb_popup: 'La ricompensa dell’annuncio pubblicitario sarà disponibile più tardi!',
  main_app_banner_1: 'Prepara ancora più biscotti!',
  main_app_banner_2: 'hai dei codici promozionali',
  main_app_banner_3: 'Usali prima della scadenza!',
  main_crush_button_text_1: 'Schiacciare di più',
  main_crush_button_text_2: 'Schiacciare per',
  main_crush_tutorial_1: 'Congratulazioni!',
  main_crush_tutorial_2: 'Questa è la tua predizione',
  main_crush_tutorial_3: 'Capito',
  main_crush_tutorial_4: 'Vieni domani',
  main_crush_tutorial_5: 'e ottieni un biscotto gratis',
  main_crush_tutorial_6: 'una volta al giorno!',
  main_crush_tutorial_7: 'Vuoi ottenere ora',
  main_crush_tutorial_8: 'biscotti gratis?',
  main_crush_tutorial_9: 'Entra qui!',
  main_crush_tutorial_10: 'Assicurati di entrare nel gioco.',
  main_crush_tutorial_11: 'Anche lì si può ottenere',
  main_crush_tutorial_12: 'biscotti gratis!',
  main_crush_tutorial_13: 'Domani ti aspetta',
  main_crush_tutorial_14: 'una nuova predizione',
  main_crush_tutorial_15: 'iscriviti per non dimenticare!',
  main_crush_tutorial_16: 'Iscriversi',
  main_crush_tutorial_17: 'Capito',
  main_footer_dating: 'Incontri',
  main_footer_free_cookies: 'Biscotti gratis',
  main_footer_game: 'Gioco',
  main_footer_hint: 'Biscotti!',
  main_footer_profile: 'Profilo',
  main_footer_rating: 'Valutazione',
  main_free_timer_text_1: 'Gratis',
  main_free_timer_text_2: 'Ottenere',
  main_main_cookie_text_1: 'Ti piace la predizione?',
  main_share_buttons_invite: 'Invita un amico',
  main_share_buttons_published: 'Pubblicato',
  main_share_buttons_story: 'Alla storia',
  main_share_buttons_wall: 'Al muro',
  main_share_buttons_share: 'Condividere',
  modals_battle_help_1: 'Benvenuto nella modalità di battaglia PvP con un giocatore reale.',
  modals_battle_help_2: 'In questa modalità, devi accoppiare più biscotti del tuo avversario in poco tempo.',
  modals_battle_help_3: 'All’inizio vengono dati 3500 argenti e la possibilità di usare una pioggia di biscotti per un biscotto della tua scommessa.',
  modals_battle_help_4: 'Tu e il tuo avversario piazzate una scommessa e iniziate la battaglia. Se si vince, si recupera ciò che resta della propria scommessa e l’intera scommessa dell’avversario.',
  modals_battle_help_5: 'Se perdi, perdi la tua scommessa, l’avversario la prende per sé.',
  modals_battle_help_6: 'Buona fortuna nelle battaglie!',
  modals_battle_help_ok: 'OK',
  modals_battle_help_title: 'Battaglie: Aiuto',
  modals_bonus_spwp_1: 'Congratulazioni!',
  modals_bonus_spwp_2: 'Nuovi giocatori sono arrivati attraverso i tuoi link:',
  modals_bonus_spwp_3: 'Ricompensa:',
  modals_bonus_spwp_4: 'Fantastico!',
  modals_bonus_spwp_5: 'Ritirare',
  modals_bonus_spwp_title: 'Ricompensa per gli invitati',
  modals_common_ok: 'Ok',
  modals_common_title: 'Informazioni',
  modals_exit_battle_question: 'Uscire dalla battaglia?',
  modals_exit_battle_description_1: 'La battaglia di allenamento sarà finita',
  modals_exit_battle_description_2: 'Perderai la battaglia e anche i biscotti',
  modals_exit_battle_accept: 'Si\nuscire',
  modals_exit_battle_reject: 'No\nrimanere',
  modals_modal_no_bricks_1: 'Oh, no!',
  modals_modal_no_bricks_2: 'Non ne hai abbastanza',
  modals_modal_no_bricks_3: 'I mattoni sono prodotti nelle città, in una fabbrica di mattoni.',
  modals_modal_no_bricks_4: 'Ok',
  modals_no_hard_hint_shop: 'Torna domani\no ricarica il tuo saldo!',
  modals_no_hard_hint_no_shop: 'Torna domani\ne ottieni biscotti gratis!',
  modals_no_hard_offer_ad: 'Ottieni un biscotto\nper la pubblicità',
  modals_no_hard_watch_ad: 'Guardare pubblicità',
  modals_no_hard_no: 'Oh, no!',
  modals_no_hard_not_enough: 'Non ne hai abbastanza',
  modals_no_hard_ok: 'OK',
  modals_no_hard_shop: 'Al negozio',
  modals_offer_notify_1: 'Un biscotto gratuito apparirà fra un po’',
  modals_offer_notify_2: 'Vuoi che ti avvisa quando un nuovo biscotto apparirà?',
  modals_offer_notify_ok: 'OK',
  modals_offline_1: 'La connessione con il server è stata persa',
  modals_offline_ok: 'OK',
  modals_offline_profit_1: 'Mentre non c’eri',
  modals_offline_profit_2: 'i biscotti hanno guadagnato',
  modals_offline_profit_3: 'Tempo di reddito offline',
  modals_offline_profit_4: '0 ore',
  modals_offline_profit_5: 'Triplicare!',
  modals_offline_profit_6: 'Prendere x3',
  modals_offline_profit_get: 'Prendere',
  modals_offline_profit_hour: 'ore',
  modals_offline_profit_min: 'm.',
  modals_offline_profit_title: 'Reddito',
  modals_ping_screen_back: 'tornare indietro',
  modals_ping_screen_connection: 'Accoppiamento...',
  modals_promo_code_1: 'Condizioni di ricezione',
  modals_promo_code_2: 'Attivare su',
  modals_promo_code_3: 'Copiare il codice promozionale',
  modals_promo_code_4: 'Attivare entro:',
  modals_promo_code_5: 'Tutti i tuoi regali sono qui, nella sezione ’I tuoi codici promozionali’',
  modals_promo_code_6: 'Gratuiti',
  modals_promo_code_7: 'biscotti',
  modals_promo_code_8: 'Inviare a MP',
  modals_promo_code_9: 'Continuare',
  modals_promo_code_10: 'Pubblicità',
  modals_search_ads_1: 'Selezione degli annunci pubblicitari',
  modals_session_error_1: 'Sembra che tu abbia già effettuato l’accesso al gioco su un altro dispositivo!',
  modals_session_error_2: 'Per continuare a giocare qui, clicca sul pulsante sottostante',
  modals_session_error_3: 'Usare questo dispositivo',
  modals_session_error_oops: 'Oops!',
  modals_technical_works_1: 'Sono in corso lavori tecnici. l’applicazione è temporaneamente non disponibile. Ci scusiamo.',
  modals_tester_settings_1: 'Tutorial permanente sui biscotti da schiacciare',
  modals_tester_settings_2: 'Tutorial permanente nel gioco di accoppiamento',
  modals_tester_settings_3: 'Di battaglia',
  modals_tester_settings_4: 'Di prova',
  modals_tester_settings_6: 'Chiudere',
  modals_tester_settings_title: 'Prove',
  modals_welcome_city_1: 'La domanda è approvata!',
  modals_welcome_city_2: 'Il sindaco della città ha approvato la tua richiesta di adesione.',
  modals_welcome_city_3: 'Affrettati a visitare la tua città, scopri i bonus che hai ricevuto e chiacchiera con gli altri residenti!',
  modals_welcome_city_4: 'Alla città!',
  modals_wheel_prize_get: 'Ottenere',
  modals_wheel_prize_open: 'Aprire!',
  modals_winner_gift_1: ', hai ricevuto un regalo! Congratulazioni!',
  modals_winner_gift_accept: 'Accettare',
  predict_download_1: 'Esplorando gli orizzonti di domani',
  predict_download_2: 'Prevedendo il futuro',
  predict_download_3: 'Decifrando i misteri del tempo',
  predict_download_4: 'Analizzando le prospettive',
  predict_download_5: 'Svelando il giorno di domani',
  predict_download_6: 'Investigando i percorsi di avanzamento',
  predict_download_7: 'Svelando la cortina del tempo',
  predict_download_8: 'Guardando al futuro',
  predict_download_9: 'Decifrando il codice di domani',
  predict_download_10: 'Studiando i corpi celesti',
  predict_download_11: 'Guardando le distese cosmiche',
  predict_download_12: 'Esplorando il cielo stellato',
  predict_download_13: 'Esaminando lo spazio cosmico',
  predict_download_14: 'Ispezionando la mappa stellare',
  predict_download_15: 'Scrutando nelle profondità dell’universo',
  predict_download_16: 'Cercando risposte da poteri superiori',
  predict_download_17: 'Rivolgendosi alla saggezza dell’Universo',
  predict_download_18: 'Dialogare con il divino',
  predict_download_19: 'Investigando le conoscenze mistiche',
  predict_download_20: 'Connettendosi con il mondo invisibile',
  predict_download_21: 'Richiedendo le profezie',
  predict_download_22: 'Ascoltando le voci dall’alto',
  predict_download_23: 'Interpretando i segni del destino',
  predict_download_24: 'Estraendo la saggezza dall’etere cosmico',
  predict_download_25: 'Consultando i saggi',
  predict_download_26: 'Contemplando l’eterno',
  predict_download_27: 'Cercando consigli dalle forze più anziane',
  predict_download_28: 'Approfondendo i misteri della magia',
  predict_download_29: 'Ricorrendo alle fonti di saggezza',
  predict_download_30: 'Ponendo domande alla coscienza cosmica',
  profile_cookies_counter: 'Il tuo saldo:',
  profile_gift_page_inventory: 'Inventario',
  profile_gift_page_shop: 'Negozio',
  profile_item_friend_select: 'Selezionare',
  profile_item_shop_gift_hit: 'hit',
  profile_no_items_1: 'Ahimè, non ti è stato ancora presentato nulla.',
  profile_no_items_2: 'Fai un regalo a un amico e probabilmente ti risponderà!',
  profile_no_items_3: 'Fare regalo a un amico',
  profile_no_items_4: 'Ahimè, non hai ancora ricevuto un regalo gratuito.',
  profile_no_items_5: 'I regali casuali si possono ottenere aprendo le predizioni o vincendoli nella ruota della fortuna',
  profile_no_items_6: 'Inoltre, puoi scegliere qualsiasi regalo per i biscotti',
  profile_no_items_7: 'Selezionare',
  profile_no_items_8: 'Ahimè, nessuno dei tuoi amici sta ancora giocando a ’Biscotti della fortuna’',
  profile_no_items_9: 'Si è verificato un errore, riprovare più tardi',
  profile_no_items_10: 'La lista è vuota :(',
  profile_no_items_11: 'La ricerca non ha dato alcun risultato',
  profile_open_gift_page_1: 'Ha regalato:',
  profile_open_gift_page_2: 'Metterlo in vetrina',
  profile_open_gift_page_3: 'Accettare',
  profile_page_1: 'Predizioni aperti:',
  profile_page_2: 'Livello massimo di biscotto:',
  profile_page_3: 'Livello massimo di lega:',
  profile_page_4: 'Inventario',
  profile_page_5: 'Salvati',
  profile_page_title: 'Profilo',
  profile_received_gift_1: 'Mittente:',
  profile_received_gift_put: 'Installato',
  profile_received_gift_showcase: 'Alla vetrina',
  profile_received_gift_title: 'Aprire un nuovo regalo',
  profile_received_page_1: 'Regali ricevuti',
  profile_select_friend_page_1: 'Per chi è il regalo:',
  profile_select_friend_page_2: 'Trovare un amico nella lista',
  profile_send_gift_page_1: 'Regalo',
  profile_send_gift_page_send: 'Inviare',
  profile_user_gifts_1: 'Regalare a un amico',
  profile_user_gifts_2: 'Regalare',
  profile_user_gifts_3: 'Regali ricevuti:',
  profile_user_gifts_watch: 'Visualizzare la lista',
  rating_1: 'Scopri i risultati nel nostro',
  rating_2: 'gruppo ufficiale',
  rating_3: 'Chi ha mangiato di più?',
  rating_all: 'Per tutto il tempo',
  rating_list_1: 'Non c’è ancora nessuno',
  rating_list_2: 'diventa il primo',
  rating_list_3: 'Si è verificato un errore',
  rating_list_4: 'nessun dato ricevuto, riprovare più tardi',
  rating_month: 'Per il mese',
  rating_today: 'Oggi',
  rating_week: 'In una settimana',
  store_ad_1: 'Si è rotto qualcosa, non abbiamo potuto darle una ricompensa.',
  store_ad_2: 'Ahimè, l’annuncio è stato chiuso, riprovare',
  store_ad_3: 'Purtroppo non è stato possibile trovare un annuncio. Riprovare più tardi.',
  store_ad_5: 'Al momento non ci sono annunci.',
  store_ad_6: 'Prova a controllare sul tuo computer, lì appare più spesso.',
  store_ad_7: 'Non dimenticare di disattivare la VPN e il blocco degli annunci',
  store_app_authorization_1: 'Accesso riuscito!',
  store_app_authorization_2: 'Benvenuto',
  store_app_authorization_3: 'Ti piace questo gioco?',
  store_app_authorization_4: 'Hai registrato i tuoi dati?',
  store_app_authorization_5: 'Email errata',
  store_app_authorization_6: 'Il reinvio sarà disponibile più tardi!',
  store_app_authorization_7: 'Grande! I tuoi dati sono stati inviati con successo a ',
  store_city_buildings_brickyard_1: 'Produzione completata: +',
  store_city_city_1: 'Errore nel creare una città. Scrivere al supporto.',
  store_city_city_2: 'Errore nella modifica della città. Scrivere al supporto.',
  store_city_city_3: 'Errore nell’ eliminare una città. Scrivere al supporto.',
  store_city_city_4: 'Il giocatore é già in un’altra città.',
  store_city_city_5: 'Il nome della città è troppo corto!',
  store_city_city_6: 'Nome della città errato!',
  store_city_city_7: 'Descrizione della città errata!',
  store_city_city_8: 'Logo errato!',
  store_city_city_9: 'Non hai abbastanza biscotti!',
  store_city_city_10: 'Non hai abbastanza mattoni!',
  store_city_city_11: 'Sfortuna, ci sono ancora residenti in città!',
  store_city_city_12: 'Vergognati, non fare il bullo!',
  store_city_city_13: 'L’invito esiste già!',
  store_city_city_14: 'Ahimè, la città è piena!',
  store_city_city_15: 'Oh, questa città non esiste più :(',
  store_city_city_16: 'Errore di produzione!',
  store_city_city_17: 'Errore di rifornimento dell’edificio!',
  store_city_city_18: 'Sfortuna! Purtroppo questa promozione è terminata.',
  store_city_city_19: 'Errore:',
  store_city_control_1: 'Creare una città',
  store_city_control_2: 'Stabilire una città',
  store_city_control_3: ' Modificare la città',
  store_city_control_4: 'Salvare le modifiche',
  store_city_control_5: 'Il nome della città non può essere vuoto!',
  store_city_control_6: 'Errore sconosciuto',
  store_city_control_7: 'Le modifiche sono state salvate con successo!',
  store_city_tutorial_1: 'Ci sono edifici sulla mappa della città che danno già dei bonus!',
  store_city_tutorial_2: 'Se li migliorate, otterrete più bonus e ricompense nel gioco.',
  store_city_tutorial_3: 'Ecco la classifica dei residenti della città.',
  store_city_tutorial_4: 'Gareggia con gli altri residenti per ottenere premi!',
  store_city_tutorial_5: 'E qui, la classifica delle altre città',
  store_city_tutorial_6: 'I residenti dovrebbero unire le forze per rendere la tua città la migliore!',
  store_city_tutorial_7: 'È sempre possibile ottenere maggiori informazioni nella finestra di aiuto.',
  store_city_tutorial_8: 'I mattoni sono necessari per migliorare la città.',
  store_city_tutorial_9: 'Per produrli, apri una fabbrica di mattoni.',
  store_city_chat_srv_enter: '@n ha aderito alla città.',
  store_city_chat_srv_leave: '@n ha lasciato la città.',
  store_city_chat_srv_upgrade: 'l’edificio @b è stato aggiornato al livello @l!',
  store_city_chat_srv_donate: '@n ha fatto una grossa donazione a @b - @c.',
  store_city_chat_srv_prizes: 'Congratulazioni ai residenti con i premi! :)',
  store_game_battle_1: 'Bender',
  store_game_battle_2: 'Rodriguez',
  store_game_core_1: 'Non hai abbastanza monete!',
  store_game_core_2: 'È incluso un aumento del profitto a',
  store_game_core_3: 'per',
  store_game_core_4: 'ore',
  store_game_core_5: 'Aumento del profitto a',
  store_game_core_6: 'esteso per altre',
  store_game_core_7: 'ore',
  store_game_core_8: 'Non è possibile eliminare il biscotto massimo!',
  store_game_core_9: 'Non è possibile accoppiare i biscotti massimi!',
  store_game_main_1: 'Sfortuna! Hai esaurito i premi.',
  store_game_main_2: 'Sfortuna! Purtroppo questa promozione è terminata.',
  store_game_main_3: 'Un nuovo livello di biscotti! ',
  store_game_main_sack_reward: 'Ricompensa ricevuta con successo! +',
  store_game_core_10: 'Non c’è spazio libero',
  store_game_tutorial_battle_1: 'Benvenuto alla battaglia di esercitazione, qui il nostro avversario di esercitazione combatterà contra te!',
  store_game_tutorial_battle_2: 'Davanti a te è presentato il campo di gioco.',
  store_game_tutorial_battle_3: 'Lo scopo del gioco è accoppiare più biscotti dell’avversario in 60 secondi.',
  store_game_tutorial_battle_4: 'Il tempo di gioco e il numero di accoppiamenti sono mostrati sopra.',
  store_game_tutorial_battle_5: 'Inizialmente ti vengono dati 3500 argenti, con i quali puoi acquistare biscotti di livello 1 per 100 argenti ciascuno.',
  store_game_tutorial_battle_6: 'Inizia ad accoppiare i biscotti!',
  store_game_tutorial_battle_7: 'È il caso di usare la pioggia di biscotti!',
  store_game_tutorial_battle_8: 'La pioggia di biscotti spreca 1 biscotto della tua scommessa, riducendo così la ricompensa ricevuta, ma dà un buon vantaggio sull’avversario, rendendo più facile la vittoria.',
  store_main_main_loading: 'caricando...',
  store_profile_profile_1: 'Scrivi il tuo commento sul regalo',
  store_profile_profile_2: 'Regali',
  store_profile_profile_3: 'Regalare',
  store_profile_profile_4: 'Il regalo è stato inviato con successo!',
  store_profile_profile_5: 'Regalare a un amico',
  store_profile_profile_6: 'Fare un regalo',
  store_profile_profile_7: 'regalare',
  store_profile_profile_grade_1: 'Frequente',
  store_profile_profile_grade_2: 'Ordinario',
  store_profile_profile_grade_3: 'Raro',
  store_profile_profile_grade_4: 'Super raro!',
  store_profile_gift_buy: 'Il regalo è stato aggiunto all’inventario!',
  store_profile_error: 'Qualcosa è andato storto: ',
  store_rating_1: 'Per un giorno',
  store_rating_2: 'Da lunedì',
  store_rating_3: 'Dal primo giorno del mese',
  store_rating_4: 'Per tutto il tempo',
  store_shop_1: 'Ci scusiamo, fino alla fine della moderazione gli acquisti non sono temporaneamente disponibili.',
  store_shop_2: 'Qualcosa è andato storto, riprovi più tardi.',
  store_shop_3: 'Triplo beneficio',
  store_shop_4: 'Per il tuo primo acquisto, ottieni il triplo dei biscotti al solito prezzo!',
  store_shop_5: 'Moltiplicare i biscotti X3',
  store_shop_6: 'Non hai abbastanza biscotti!',
  store_shop_7: 'Errore. Contattare il supporto!',
  store_shop_8: 'in promozione',
  store_shop_9: 'in regalo',
  store_shop_10: 'e altro ancora',
  store_shop_11: 'Hai ricevuto',
  store_shop_12: 'Buon gioco!',
  store_shop_processing_popup: 'Il tuo acquisto è ancora in fase di elaborazione!',
  store_user_user_1: 'Unisciti al gruppo',
  store_user_user_2: 'Iscriviti alle notifiche',
  store_user_user_3: 'Aggiungi ai preferiti',
  store_user_user_4: 'Iscriviti ai messaggi del gruppo',
  store_user_user_5: 'Scrivi ’Ciao!’ al gruppo',
  store_user_user_6: 'Condividi sul muro',
  store_wheel_1: 'Congratulazioni!',
  store_wheel_2: 'Evviva!',
  store_wheel_3: 'Super!',
  store_wheel_4: 'Fantastico!',
  store_wheel_5: 'Grande!',
  store_wheel_6: 'Successo!',
  store_wheel_7: 'Fortuna!',
  store_wheel_8: 'Ottimo!',
  store_wheel_9: 'Perfetto!',
  store_wheel_10: 'Magnifico!',
  store_wheel_11: 'Jackpot! ',
  store_wheel_12: 'Reddito d’argento per 1 ora',
  store_wheel_13: 'le monete saranno accreditate dopo l’ingresso nel gioco',
  store_wheel_14: 'Pioggia di Biscotti gratis',
  store_wheel_15: 'i tentativi vinti vengono sommati',
  store_wheel_16: 'Piccolo premio: +',
  store_wheel_17: '+1 al livello di reddito offline',
  store_wheel_18: 'Reddito d’argento in 2 ore',
  store_wheel_19: '+50 accoppiamenti nel gioco',
  store_wheel_20: 'conquista le leghe, ottieni premi',
  store_wheel_21: 'Grande premio: +',
  store_wheel_22: 'Booster di reddito gratuito',
  store_wheel_23: 'Reddito d’argento in 30 minuti',
  store_wheel_24: 'Un regalo alla collezione',
  store_wheel_25: 'puoi darlo a qualcuno',
  store_wheel_26: 'Reddito d’argento in 4 ore',
  store_wheel_27: 'Sembra che non vi siano più biglietti gratuiti!',
  welcome_but_proceed: 'Continuare',
  welcome_text: 'Ricevi un biscotto gratuito e scopri quando ne appaiono di nuovi!',
  wheel_1: 'Tenta la fortuna, vinci il primo premio!',
  wheel_2: 'Vincitori:',
  wheel_ad_play_button_1: 'Giocare',
  wheel_ad_play_button_2: 'Gratis!',
  wheel_btn_1: 'Giocare!',
  wheel_btn_2: 'La Ruota della Fortuna non è ancora disponibile.',
  wheel_btn_3: 'Torna domani per giocare!',
  wheel_play_1: 'Giocare per',
  wheel_title: 'Ruota della Fortuna',
  wheel_winner_list_item_hour: ' ore',
  wheel_winner_list_item_min: ' min.',
  wheel_winner_list_item_sec: ' sec.',
  wheel_winner_spin_1: 'Hai vinto',
  wheel_winner_spin_2: 'Prendere',
  app_emo_status_title: 'Scegli il tuo stato emoji!',
  app_emo_status_1: 'Appare a destra del tuo nome e sarà visibile a tutti in ',
  app_emo_status_remove: 'rimuovere lo stato',
  app_emo_status_done: 'Fatto',
  app_loading_offline_title: 'Lavori tecnici' ,
  app_loading_offline_message: 'L’applicazione è in manutenzione, ci scusiamo.\n\nTornate da noi più tardi.',
  app_loading_agreement_header_1: 'Importante!',
  app_loading_agreement_header_2: 'Prima di iniziare a giocare, leggete e accettate:',
  app_loading_agreement_checkbox_default: 'Accetto i termini dell’accordo',
  app_loading_agreement_accept: 'Giocare',
  app_loading_agreement_decline: 'Lasciare il gioco',
  chapter_lvl: 'liv.',
  chapter_level: 'livello',
  chapter_difficulty_easy: 'Facile',
  chapter_difficulty_medium: 'Medio',
  chapter_difficulty_hard: 'Difficile',
  chapter_until_refresh: 'Fino all’aggiornamento:',
  chapter_chapter_rank: 'Classifica:',
  chapter_chapter_ended: 'Fino alla fine:',
  chapter_chapter_of: 'di',
  chapter_chapter_difficulty_1: 'Ottieni',
  chapter_chapter_difficulty_2: ', per passare a un nuovo rango!',
  chapter_chapter_difficulty_3: ', per rimanere a questo rango!',
  chapter_chapter_completed_1: 'Le avventure di questa stagione sono finite!',
  chapter_chapter_completed_2: 'Torna più tardi quando inizia la nuova stagione.',
  chapter_tasks_hourly: 'Missioni panpepato',
  chapter_tasks_daily: 'Missioni giornaliere',
  chapter_tasks_weekly: 'Missioni settimanali',
  chapter_hint_m1: 'Vai al gioco e compra i biscotti per il tavolo attraverso il menu "Acquisto rapido" o al "Mercato".',
  chapter_hint_m2: 'Accoppia due biscotti identici sul tavolo da gioco.',
  chapter_hint_m3: 'Attiva il booster del reddito da monete, che si trova nella scheda "Miglioramenti" del gioco.',
  chapter_hint_m4: 'Avvia la pioggia di biscotti nel gioco. È nella scheda "Miglioramenti".',
  chapter_hint_m5: 'Accoppia i biscotti nel gioco e fai salire di livello il tuo biscotto massimo',
  chapter_hint_m6: 'Migliora il tuo livello di reddito offline nel gioco, nella scheda "Miglioramenti".',
  chapter_hint_m7: 'Vai alla sezione di miglioramento dei piatti (scheda Miglioramenti) e aggiorna il tuo piatto.',
  chapter_hint_m8: 'Alla fine della tua lega nel gioco, devi essere al 20° posto o superiore.',
  chapter_hint_m9: 'Accedi al gioco a intervalli di più di 24 ore per aumentare i progressi della missione.',
  chapter_hint_m10: 'Quando rientri nel gioco, prendi le monete di reddito offline.',
  chapter_hint_m11: 'Scopri il tuo posto nella lega di gioco, controlla di nuovo il tuo posto, deve cambiare.',
  chapter_hint_m12: 'Inizia la pioggia di biscotti e non perderne nemmeno uno oltre il tavolo da gioco, catturandoli tutti.',
  chapter_hint_m13: 'Posiziona sul tuo tavolo da gioco il numero richiesto di biscotti per ordine del livello.',
  chapter_hint_m14: 'Il tavolo da gioco deve contenere il numero richiesto di biscotti per ordine del livello, dal biscotto più grande al più piccolo.',
  chapter_hint_m15: 'Attiva il booster del reddito da monete premio, il costo dovrebbe indicare "Premio". Si trova nella scheda "Miglioramenti" del gioco.',
  chapter_hint_m16: 'Avvia una pioggia di biscotti premio nel gioco. Il costo deve indicare "Premio".',
  chapter_hint_c1: 'Vai nella tua città e crea dei mattoni nella ’Fabbrica di mattoni’.',
  chapter_hint_c2: 'Visita la tua città, seleziona un edificio qualsiasi sulla mappa e aggiungici dei biscotti.',
  chapter_hint_c3: 'Guarda la tua città, apri un edificio qualsiasi sulla mappa e aggiungici dei mattoni.',
  chapter_hint_c4: 'Usa un’azione qualsiasi per ottenere un certo numero di punti per la classifica dei membri della città.',
  chapter_hint_c5: '',
  chapter_hint_c6: 'Torna in città, vai alla scheda della chat e invia un messaggio qualsiasi alla chat della città.',
  chapter_hint_c7: 'Per aumentare i progressi, devi visitare la tua città a intervalli superiori alle 24 ore.',
  chapter_hint_f1: 'Apri le battaglie del gioco e combatti qualsiasi battaglia non di allenamento.',
  chapter_hint_f2: 'Gioca la battaglia e finiscila sconfiggendo il tuo avversario.',
  chapter_hint_f3: 'Gioca la battaglia, accoppia i biscotti e finiscila con oltre 60 accorpamenti.',
  chapter_hint_f4: 'Partecipa alla battaglia e finiscila con un biscotto di almeno livello 7 sulla tabella delle battaglie.',
  chapter_hint_f5: 'Gioca in diverse battaglie e compra i biscotti sul tavolo per ottenere monete, ogni moneta spesa conta.',
  chapter_hint_p1: 'Ottieni una predizione schiacciando un biscotto in qualsiasi categoria.',
  chapter_hint_p2: 'Scegli una qualsiasi categoria di predizione, tranne ’Per il giorno’ e schiaccia il biscotto.',
  chapter_hint_p3: 'Ricevi qualsiasi predizione e condividila in qualsiasi forma disponibile.',
  chapter_hint_p4: 'Apri qualsiasi previsione e valutala facendo clic sul pulsante "Pollice su" o "Pollice giù".',
  chapter_hint_q1: 'Completa una qualsiasi missione d’avventura e premi il pulsante "Prendi" per guadagnare stelle esperienza.',
  chapter_hint_q2: 'Completa una qualsiasi missione panpepato nelle avventure premendo il pulsante "Prendi".',
  chapter_hint_q3: 'Premi il pulsante "Prendi" su qualsiasi missione completata in "Missioni giornaliere" delle avventure.',
  chapter_hint_q4: 'Completa qualsiasi missione e prendi le stelle esperienza per aumentare il tuo livello.',
  chapter_hint_q5: 'Accelera le "Missioni panpepato" con il pulsante "Accelera", usa tutte le accelerazioni possibili al giorno per aumentare i progressi di uno.',
  chapter_hint_d1: 'Apri la "Ruota della Fortuna" e falla girare tentando la fortuna. Il fatto della torsione è preso in considerazione.',
  chapter_hint_d2: 'Visita la sezione del tuo profilo, da qualsiasi punto dell’applicazione.',
  chapter_hint_d3: 'Invia un regalo a qualcuno usando i pulsanti: nel profilo di qualcun altro - "Regalo" o nel tuo profilo - "Regalo a un amico".',
  chapter_hint_d4: 'Puoi chiedere a qualcuno di inviarti un regalo, ad esempio un amico, un membro della città, oppure inviare tu stesso un regalo e attendere una risposta.',
  chapter_hint_d5: 'Guarda qualsiasi pubblicità con una ricompensa, ad esempio: "Accelerazione delle missioni", "Ruota della fortuna", "+1 biscotto", ecc.',
  chapter_hint_d6: 'Visita l’’applicazione a intervalli di più di 24 ore per aumentare i tuoi progressi.',
  chapter_hint_d7: 'Non chiudere l’applicazione per il tempo richiesto. Rimani con noi ancora un po’.',
  chapter_hint_d8: 'Spendi i biscotti per qualsiasi scopo: bonus, miglioramenti, predizioni..., ogni biscotto speso conta.',
  chapter_hint_d9: 'Ottieni biscotti sulla tua bilancia, ad esempio: in "Avventure", prendi "Gratis", vinci nella "Ruota della Fortuna", ecc. ogni biscotto conta.',
  chapter_hint_w2: 'Gira la "Ruota della fortuna" usando un tentativo gratuito per la pubblicità. La rotazione viene presa in considerazione solo per la pubblicità.',
  chapter_hint_w3: 'Tenta la fortuna nella "Ruota della fortuna". Vinci "Monete" per aumentare i progressi di questa attività.',
  chapter_hint_w4: 'Apri la "Ruota della Fortuna", gioca, se vinci il "Regalo", i progressi aumenteranno.',
  chapter_next_level_greetings: 'Congratulazioni!',
  chapter_next_level_proceed: 'Continuare',
  chapter_next_level_reward: 'La tua ricompensa',
  chapter_next_level_great: 'Ottimo!',
  chapter_next_level_vip_active: 'Stato attivo',
  chapter_next_level_vip_offer_1: 'Lo stato ti permetterà di',
  chapter_next_level_vip_offer_2: 'prendere tutte le ricompense',
  chapter_next_level_missed: 'Ricompense perse',
  chapter_next_level_more: 'ancora',
  chapter_next_level_get_vip_1: 'Ottenere lo stato',
  chapter_next_level_get_vip_2: 'per prendere',
  chapter_task_item_reward: 'Ricompensa',
  chapter_task_item_take: 'Prendere',
  chapter_task_item_completed: 'Completato',
  chapter_task_item_speedup: 'Accelerare',
  chapter_task_item_next: 'Prossima missione in:',
  chapter_timer_d: 'g.',
  chapter_timer_h: 'o.',
  chapter_timer_m: 'm.',
  chapter_vip_reward_granted: 'Stato ottenuto!',
  chapter_vip_reward_available: 'Disponibili',
  chapter_vip_reward_missed: 'ricompense perse',
  chapter_vip_reward_hint: 'Mentre lo stato è attivo, si ricevono ricompense',
  chapter_vip_reward_take: 'Prendere!',
  chapter_refresh_title: 'Cambio della missione',
  chapter_refresh_message: 'Se non ti piace questa missione, puoi sostituirla con un’altra scelta a caso.',
  chapter_refresh_actions_1: 'Vuoi tentare la fortuna?',
  chapter_refresh_button: 'Sostiture per',
  chapter_refresh_back: 'Tornare indietro',
  city_control_members_term_s: ' s.',
  city_control_members_term_m: ' m.',
  city_control_members_term_h: ' o.',
  city_control_members_term_d: ' g.',
  city_control_requests_term_d: 'g.',
  free_cookies_promo_codes_empty_1: 'Non hai ancora codici promozionali :(',
  free_cookies_promo_codes_empty_2: 'Apri i predizioni per ricevere piacevoli regali!',
  free_cookies_promo_codes_activate: 'Attivare su',
  free_cookies_promo_codes_reusable: 'Questo codice è\nriutilizzabile',
  free_cookies_promo_codes_extra: 'Fare clic per ottenere\nun’altro codice',
  free_cookies_promo_codes_show_1: 'Mostra il codice nel negozio',
  free_cookies_promo_codes_show_2: 'per ritirare il regalo',
  free_cookies_promo_codes_gift_1: 'Bonus di attivazione: ',
  free_cookies_promo_codes_condition: '[condizioni]',
  free_cookies_promo_codes_send_hint: 'Salva il codice con\ninformazioni dettagliate nei messaggi',
  free_cookies_promo_codes_copy_hint: 'Oppure clicca sul codice per copiarlo',
  game_counter_soft_vip: 'Da stato VIP',
  game_battle_result_exit_title: 'Squalifica',
  game_battle_result_exit_message: 'Hai abbandonato la battaglia in anticipo e hai perso:',
  game_task_tracker_season: 'La stagione è finita. Non ci sono ancora missioni.',
  game_task_tracker_until_next: 'Fino alla prossima missione:',
  game_market_title: 'Mercato',
  game_market_cookies: 'Biscotti',
  game_market_coins: 'Monete',
  main_app_banner_promo: 'Codice promozionale',
  main_app_banner_reward: 'Ricompensa per l’attivazione',
  main_categories_title_1: 'SHEGLI LA CATEGORIA',
  main_categories_title_2: 'DI PREDIZIONE',
  main_categories_back: 'Tornare indietro',
  main_crush_button_more_wishes: 'Altri auguri',
  main_crush_button_crush_wishes: 'Schiacciare',
  main_crush_button_want_wishes: 'Voglio degli auguri!',
  main_crush_button_view_wishes: 'Visualizzare la lista',
  main_crush_button_prize_crush: 'Schiacciare',
  main_crush_button_prizes: 'Gratuiti:',
  main_crush_tutorial_share_1: 'Condividi la tua fortuna con i tuoi',
  main_crush_tutorial_share_2: 'amici inviando il widget',
  main_crush_tutorial_share_3: 'dell’applicazione alle chat!',
  main_footer_promo: 'I tuoi codici promozionali',
  main_footer_chapter_1: 'Missioni',
  main_footer_chapter_2: 'delle avventure',
  main_main_cookie_complaint: '[reclamo]',
  main_main_cookie_empty_wishes: 'Nessun nuovo augurio.',
  main_main_cookie_count_wishes: 'Hai',
  main_share_buttons_sender: 'Chi ha inviato?',
  main_share_buttons_reveal: 'Rivela per',
  main_share_buttons_view_1: 'Visualizzare',
  main_share_buttons_view_2: 'auguri',
  main_share_buttons_to_chat: 'Inviare alla chat',
  modals_complaint_complaint: 'Reclamare',
  modals_complaint_attention: 'Tutti gli auguri ricevuti da questo mittente saranno cancellati e non potrà inviarvi nuovi auguri.',
  modals_complaint_blocking_1: 'Bloccare l’autore',
  modals_complaint_blocking_2: 'e rimuovere gli auguri',
  modals_complaint_attention_2: 'Se questo messaggio viola le regole del gioco, puoi presentare un reclamo contro di esso.',
  modals_complaint_blocking_3: 'Inviare reclamo',
  modals_onboarding_header_1: 'Apri i biscotti della fortuna con gli amici attraverso dialoghi e chat',
  modals_onboarding_header_2: 'I vostri amici possono condividere le loro previsioni nella chat',
  modals_onboarding_content_1: 'Condividi le predizioni ricevute attraverso la storia e il muro',
  modals_onboarding_content_2: 'E puoi mandare le tue in risposta',
  modals_onboarding_ok: 'OK',
  modals_promo_code_bonus_1: 'Regalo per l’attivazione:',
  modals_promo_code_bonus_ya_1: 'Ricevi un regalo per l’attivazione di un codice promozionale',
  modals_promo_code_bonus_ya_2: '(il periodo di emissione dei biscotti è di 4 giorni)',
  modals_promo_code_great: 'Ottimo!',
  modals_promo_code_footer_btn_1: 'I tuoi',
  modals_promo_code_footer_btn_2: 'codici promozionali!',
  modals_tester_settings_tutor_mode: 'Modalità tutorial per i test di gioco',
  modals_tester_settings_skip_ad: 'Saltare la pubblicità per ricompensa',
  profile_profile_page_vip_until: 'Attivo fino a:',
  profile_profile_page_emo_status_1: 'Emoji',
  profile_profile_page_emo_status_2: 'stato',
  profile_profile_page_register: 'Già con un biscotto:',
  shop_pack_item_page_sale: 'Promozione',
  shop_pack_item_page_status: 'Stato',
  shop_pack_item_page_until_vip: 'Attivo fino a',
  shop_pack_item_page_unsubscribe: 'Annullare l’iscrizione',
  shop_pack_item_page_unsubscribed: 'L’iscrizione annullata',
  shop_pack_item_page_unavailable: 'Mentre lo stato VIP è attivo, questo pacchetto non è disponibile.',
  shop_pack_item_page_cost: 'Costo',
  shop_pack_item_page_privacy: 'Facendo clic sul pulsante "Ricevi", l’utente accetta',
  shop_pack_item_page_agreement: 'Accordo per gli utenti',
  shop_pack_item_page_processing: 'Elaborazione acquisto',
  shop_sales_container_bonus_success_1: 'Bello! Regalo ricevuto',
  shop_sales_container_bonus_success_2: 'Visita il negozio per non perdere nuovi regali e promozioni.',
  shop_sales_container_bonus_take: 'Prendere',
  shop_sales_container_left: 'Rimasto: ',
  shop_shop_page_title: 'Negozio',
  shop_shop_page_cookies: 'Biscotti',
  shop_shop_page_vip: 'Stato VIP',
  shop_shop_page_boosters: 'Pacchetti Boosters',
  shop_shop_page_hit: 'HIT',
  shop_shop_page_active: 'Attivo',
  wishes_received_empty_new: 'Schiaccia il biscotto per scoprire il tuo primo augurio!',
  wishes_received_empty: 'Spiacente, la tua lista degli auguri è ancora vuota :(',
  wishes_received_more: 'Ancora',
  wishes_received_list_1: 'Auguri',
  wishes_received_list_2: 'lista',
  wishes_received_sender: '[chi ha inviato]',
  wishes_received_reveal: 'Rivelare il mittente per',
  wishes_received_complaint: '[reclamo]',
  wishes_wishes_hint: 'Inserisci il testo di augurio',
  wishes_wishes_todo_1: 'Scrivi un',
  wishes_wishes_todo_2: 'augurio sincero',
  wishes_wishes_result_1: 'Augurio',
  wishes_wishes_result_2: 'per',
  wishes_wishes_result_3: 'Inviato!',
  wishes_wishes_wish: 'Inviare un augurio',
  wishes_wishes_get_predict: 'Ottieni una predizione',
  store_ad_limit: 'Raggiunto il limite di visualizzazioni!',
  store_ad_tests: 'Saltare gli annunci! L’impostazione è attivata nei test.',
  store_ad_task_reward_error: 'Impossibile trovare un’attività da velocizzare!',
  store_ad_speed_count: ' Velocizzazioni utilizzate:',
  store_ad_survey_closed: 'Sondaggio pubblicitario fallito, riprovare più tardi.',
  store_chapter_info_name: 'Avventure',
  store_chapter_wt: 'Ricevuto un id di missione inesistente!',
  store_chapter_er_pr: 'Qualcosa è andato storto con il monitoraggio dei progressi delle missioni!',
  store_chapter_task_ready: 'La missione è stata completata! Sbrigati a prendere le stelle esperienza!',
  store_chapter_new_task: 'La nuova missione è ora disponibile!',
  store_chapter_sw: 'Hmm... Qualcosa è andato storto!',
  store_chapter_sb: 'Si è rotto qualcosa! ',
  store_shop_eb_header: 'PROMOZIONI',
  store_shop_eb_text: 'Nuove vendite e regali in arrivo. Vieni più spesso in negozio per non perderti nulla!',
  store_shop_buy_pack: 'Ottieni questo pacchetto',
  store_shop_pack_contains: 'PACCHETTO CONTIENE',
  store_shop_vip_contains: 'VANTAGGI',
  store_shop_vip_info_chapter: 'sblocca i premi delle avventure',
  store_shop_vip_info_free: '+1 biscotto gratuito al giorno',
  store_shop_vip_info_fc: '+1 biscotto al giorno per attività sociali',
  store_shop_vip_info_main_ad: '+5 annunci premiati al giorno',
  store_shop_vip_info_soft: 'x2 alle entrate di monete nel gioco',
  store_shop_vip_info_icon: 'Icona VIP nella classifica',
  store_shop_vip_info_no_ad: 'disabilitazione degli annunci a schermo intero e dei banner',
  store_shop_receive_vip: 'Ottenere stato',
  store_shop_prolong_vip: 'Prolungare stato',
  store_shop_prolonged_vip_1: 'Congratulazioni!\nIl tuo stato VIP è stato prolungato con successo per',
  store_shop_prolonged_vip_2: 'giorni.\n\nBuon gioco.',
  store_shop_received_vip_1: 'Congratulazioni!\nHai ricevuto lo status di VIP per',
  store_shop_received_vip_2: 'giorni.\n\nBuon gioco.',
  store_shop_received_vip_3: 'Congratulazioni! Hai ottenuto:\n',
  store_shop_received_vip_4: 'giorni.\n\nBuon gioco.',
  store_shop_bu_error: 'Questo regalo è già stato ricevuto!',
  store_shop_b_error: 'Qualcosa è andato storto, non è stato possibile prendere il regalo.',
  store_shop_sbe: 'Si è rotto qualcosa, riprovare più tardi.',
  store_shop_unsbce: 'Impossibile annullare l’iscrizione. Qualcosa è andato storto!',
  store_shop_unsbce_vk: 'Impossibile annullare l’iscrizione, errore di VK',
  store_shop_pack_bonus: ' (regalo)',
  store_shop_pack_sale: ' (promozione)',
  store_shop_pack_vip: 'Stato VIP per ',
  store_wishes_category_name: 'Auguri',
  store_wishes_category_hint: 'Schiaccia il biscotto e scopri cosa ti augurano le altre persone',
  store_wishes_e_empty: 'Hmm, non ci sono più auguri!',
  store_wishes_e_bad: 'Per favore, usa il testo censurato per l’augurio!',
  store_wishes_e_no_user_1: 'Sfortunatamente,',
  store_wishes_e_no_user_2: 'non ha visitato il biscotto per molto tempo e non è nel database!',
  store_wishes_e_already_sent: 'ha già ricevuto un augurio da te oggi!',
  store_wishes_e_black: 'non accetta auguri da te!',
  store_wishes_e_no_hard: 'Non ci sono abbastanza biscotti!',
  store_wishes_e_def: 'Errore! ',
  store_wishes_butt_e: 'Pulsante non aggiunto, qualcosa è andato storto',
  store_wishes_butt_suc: 'Ora puoi ricevere auguri!',
  store_wishes_butt_del: 'Il pulsante per l’invio degli auguri è stato rimosso dal profilo ;(',
  store_wishes_butt_ue: 'Pulsante non aggiunto, si è verificato un errore!',
  store_wishes_e_sender_uid: 'Non puoi inviare un augurio a te stesso!',
  store_wishes_ue: 'Errore sconosciuto: ',
  store_wishes_complaint: 'Il tuo reclamo è stato accettato, l’autore è bloccato, tutti i suoi auguri sono stati rimossi.',
  store_game_main_es: 'Salvataggio del gioco fallito!',
  store_game_main_esw: 'Qualcosa è andato storto! ',
  store_game_main_esb: 'Si è rotto qualcosa! ',
  store_game_plates_su: 'Piatto aggiornato con successo a x',
  store_main_no_prize: 'Hai esaurito le predizioni gratuiti.',
  store_main_esw: 'Hmm, qualcosa è andato storto, riprova più tardi o scrivici.',
  store_user_friends_evk: 'Errore nell’ottenere la lista degli amici!',
  store_user_status_not_allowed: 'Stato non disponibile :(',
  store_user_status_eu: 'Si è verificato un errore!',
  store_user_status_e_empty: 'Nessuno stato disponibile!',
  store_user_status_e_not_set: 'L’installazione dello stato non è riuscita, sembra che qualcosa sia andato storto.',
  store_user_status_e_not_select: 'Stato di selezione fallito, qualcosa è andato storto.',
  store_user_status_e_not_remove: 'Non è stato possibile rimuovere lo stato, qualcosa è andato storto.',
  store_user_recommend_app: 'Raccomanda l’applicazione',
  store_user_reward_received: 'Evviva! Ricompensa ricevuta:',
  store_user_esw_recommend: 'Qualcosa è andato storto, contatta il supporto!',
  store_user_esb_recommend: 'Si è rotto qualcosa, riprova più tardi.',
  store_app_invite_text: 'Ti invito a schiacciare i biscotti della fortuna.',
  store_app_invite_button: 'Ottieni predizioni',
  store_app_invite_title: 'Invita i tuoi amici a schiacciare i biscotti!',
  store_share_error: 'Oh! Qualcosa è andato storto!',
  store_share_wall_predict_text: 'Il Biscotto della Fortuna mi ha detto: @p',
  store_share_wall_biggest_text: 'Ho raggiunto un nuovo livello di biscotti @b!',
  store_share_wall_achievement_text: 'Ho ottenuto @t risultato "@n"!',
  store_share_invite_text: 'Io conosco il mio futuro, e tu? Ti invito a Biscotto della Fortuna, prendi le tue predizioni e accoppia i biscotti!',
  share_story_predict_title_1: 'Biscotto della Fortuna',
  share_story_predict_title_2: 'mi ha detto:',
  share_story_special_title_1: 'Ottieni',
  share_story_special_title_2: 'la predizione del giorno',
  share_story_special_title_3: 'dal biscotto',
  share_story_biggest_title_1: 'Ho un nuovo',
  share_story_biggest_title_2: 'livello',
  share_story_biggest_title_3: 'del biscotto',
  share_story_biggest_title_4: 'Gioco fantastico -',
  share_story_biggest_title_5: 'apri il link anche tu!',
  share_story_special_button: 'Ottieni la tua predizione',
  share_story_predict_button: 'Ottieni la tua predizione',
  share_story_biggest_button: 'Giocare',
  share_wall_predict_title_1: 'Biscotto',
  share_wall_predict_title_2: 'mi ha detto:',
  share_wall_special_title_1: 'Ottieni',
  share_wall_special_title_2: 'predizioni',
  share_wall_special_title_3: 'dal biscotto',
  share_wall_biggest_title_1: 'Ho un nuovo',
  share_wall_biggest_title_2: 'livello',
  share_wall_biggest_title_3: 'del biscotto!',
  share_wall_biggest_title_4: 'Gioco fantastico -',
  share_wall_biggest_title_5: 'apri il link anche tu!',
  share_wall_special_footer_1: 'Quale fortuna ti aspetta oggi?',
  share_wall_special_footer_2: 'Sbrigati, schiaccia il biscotto!',
  share_wall_predict_footer_1: 'Quale fortuna ti aspetta oggi?',
  share_wall_predict_footer_2: 'Sbrigati, schiaccia il biscotto!',
  share_wall_biggest_footer_1: 'Gioca, accoppia i biscotti',
  share_wall_biggest_footer_2: 'Ricevi predizioni',
  share_wall_biggest_footer_3: 'da Biscotti della Fortuna!',
  share_wall_achievements_footer_1: 'Gioca, fai le conquiste',
  share_wall_achievements_footer_2: 'Ricevi predizioni',
  share_wall_achievements_footer_3: 'da Biscotti della Fortuna!',
  special_predict: 'Sarai felice',
  achievement_name_1: 'Fan',
  achievement_description_1: 'Accedi all’applicazione',
  achievement_hint_1: 'Per aumentare i progressi nelle conquiste, basta accedere all’applicazione, ma non troppo spesso.',
  achievement_name_2: 'Fornaio',
  achievement_description_2: 'Ottieni reddito offline',
  achievement_hint_2: 'Entra nel gioco e raccogli il reddito offline accumulato durante la tua assenza.',
  achievement_name_3: 'Pasticciere',
  achievement_description_3: 'Compri i biscotti per il tavolo',
  achievement_hint_3: 'Vai al gioco e compra i biscotti per il tuo tavolo da gioco, ogni biscotto verrà contato.',
  achievement_name_4: 'Cuoco',
  achievement_description_4: 'Accoppia i biscotti',
  achievement_hint_4: 'Accoppia biscotti identici sul tuo tavolo di gioco per aumentare i tuoi progressi.',
  achievement_name_5: 'Inarrestabile',
  achievement_description_5: 'Attiva "Rocket Boosters"',
  achievement_hint_5: 'Attiva "Rocket boosters", si trova nella scheda "Miglioramenti" del gioco.',
  achievement_name_6: 'Tor',
  achievement_description_6: 'Avvia una pioggia di biscotti',
  achievement_hint_6: 'Avvia una "Pioggia di biscotti" nel gioco. Il pulsante si trova nella scheda "Miglioramenti".',
  achievement_name_7: 'Potter',
  achievement_description_7: 'Miglioramento dei Piatti',
  achievement_hint_7: 'Vai alla sezione dei miglioramenti dei piatti (scheda "Miglioramenti") e aggiorna i livelli dei piatti.',
  achievement_name_8: 'Oracolo',
  achievement_description_8: 'Apri le predizioni',
  achievement_hint_8: 'Schiaccia i biscotti in qualsiasi categoria - ottieni le tue predizioni per aumentare i progressi nelle conquiste.',
  achievement_name_9: 'Reporter',
  achievement_description_9: 'Condividi tutto',
  achievement_hint_9: 'Condividi sulla tua pagina una predizione, un nuovo livello di biscotti o un risultato ottenuto. Non più di una volta in poche ore.',
  achievement_name_10: 'Babbo Natale',
  achievement_description_10: 'Invia regali agli altri',
  achievement_hint_10: 'Invia regali a qualcuno usando i pulsanti: nel profilo di qualcun altro - "Regalo" o nel tuo profilo - "Regalo a un amico".',
  achievement_name_11: 'Segmento Premio',
  achievement_description_11: 'Gira la "Ruota della Fortuna"',
  achievement_hint_11: 'Apri la "Ruota della Fortuna" e falla girare. Ogni giro conta.',
  achievement_name_12: 'Sei fortunato',
  achievement_description_12: 'Vinci il "Premio" con i biscotti',
  achievement_hint_12: 'Gira la "Ruota della Fortuna" - se si ottiene un Premio piccolo, un Premio grande o un Jackpot, i progressi aumenteranno.',
  achievement_name_13: 'Grande punteggio',
  achievement_description_13: 'Vinci "Jackpot"',
  achievement_hint_13: 'Gira la "Ruota della Fortuna", prendi la fortuna per la coda vincendo il Jackpot.',
  achievement_name_14: 'Muratore',
  achievement_description_14: 'Produci "Mattoni"',
  achievement_hint_14: 'Crea mattoni nella "Fabbrica di mattoni" della tua città. Ogni mattone verrà contato.',
  achievement_name_15: 'Capitalista',
  achievement_description_15: 'Vinci biscotti',
  achievement_hint_15: 'Gioca alla "Ruota della Fortuna", vinci biscotti e i progressi aumenteranno in base al numero di biscotti vinti.',
  achievement_name_16: 'Collettore',
  achievement_description_16: 'Raccogli sacchi di monete',
  achievement_hint_16: 'Dimostra la tua arguzia e prendi il sacco che cade sul tavolo da gioco, raccogli le monete e i tuoi progressi aumenteranno.',
  achievement_name_17: 'Avventuriero',
  achievement_description_17: 'Raggiungi il livello 45 nelle avventure',
  achievement_hint_17: 'Partecipa alle "Avventure", ottieni esperienza e sali di livello per completare questo risultato.',
  achievement_name_18: 'Pignolo',
  achievement_description_18: 'Sostituisci le missioni delle avventure',
  achievement_hint_18: 'Apri ’Avventure’ e sostituisci tutte le missioni che non ti piacciono',
  achievement_name_19: 'Cercatore di stelle',
  achievement_description_19: 'Raccogli le stelle nelle avventure',
  achievement_hint_19: 'Completa una qualsiasi missione Avventura e premi il pulsante "Prendi" per ottenere le stelle esperienza.',
  achievement_name_20: 'Medaglista',
  achievement_description_20: 'Diventa un vincitore di premi della classifica',
  achievement_hint_20: 'Apri le predizioni e guadagna una ricompensa qualsiasi nella valutazione "Chi ha mangiato di più?", i progressi aumenteranno dopo che la "ricompensa" è stata completata.',
  achievements_congratulations_bronze: 'Bronzo',
  achievements_congratulations_silver: 'Argento',
  achievements_congratulations_gold: 'Oro',
  achievements_congratulations_brilliant: 'Diamante',
  achievements_page_title_other: 'Conquiste',
  achievements_page_title_my: 'Le mie conquiste',
  achievements_page_all_progress: 'Progresso totale',
  achievements_my_have: 'Hanno',
  achievements_my_take: 'Prendere',
  achievements_my_reward: 'Ricompensa',
  achievements_my_from: 'dalla',
  achievements_my_gallery: 'Galleria',
  achievements_my_slot: 'Nella slot',
  achievements_gallery_heading: 'Scegli un posto in galleria',
  achievements_gallery_pick: 'Scegliere',
  achievements_gallery_switch: 'Sostituire',
  achievements_gallery_delete: 'Eliminare',
  achievements_gallery_show: 'visualizzare tutti',
  achievements_gallery_empty: 'Punto vacante',
  achievements_congratulations_great: 'Ottimo!',
  achievements_congratulations_achiev: 'risultato',
  achievements_congratulations_cool: 'Perfetto',
  achievements_congratulations_times: 'volte',
  store_user_achievements_error: 'Conquiste. Qualcosa è andato storto! ',
  achievements_story_have: 'LA MIA',
  achievements_story_achievement: 'CONQUISTA!',
  achievements_story_want: 'Vuoi fare la tua?',
  achievements_story_hurryup: 'Sbrigati a giocare!',
  achievements_story_button: `Avanti! Alle conquiste`,
};

export {italian};