const russian = {
  app_name: "Печенька",
  anonymous: "Аноним",
  app_email_1: "Записал свои данные?",
  app_email_2: "Укажи свою почту и нажми отправить.",
  app_email_3: "Получи свой логин и пароль, чтобы всегда иметь возможность вернуться в игру!",
  app_email_4: "Отправить",
  app_email_5: "Твой Email",
  app_settings_title: "Настройки",
  app_settings_music: "Музыка",
  app_settings_music_bg: "Проигрывать в свернутом",
  app_settings_sounds: "Звуки",
  app_settings_rain: "Скорость печенькопада",
  app_settings_notify: "Уведомления",
  app_settings_wishes: "Пожелания",
  app_settings_extra: "Дополнительно",
  app_settings_user_agreement: "Пользовательское соглашение",
  app_welcome_1: "Привет!",
  app_welcome_2: "регистрация завершена",
  app_welcome_3: "Логин:",
  app_welcome_4: "Пароль:",
  app_welcome_5: "Мы храним твои данные на этом устройстве, пока они существуют ты не потеряешь свой прогресс!",
  app_welcome_6: "Хорошо, играть!",
  app_welcome_7: "Уже есть логин?",
  app_welcome_8: "Введи свои данные, чтобы продолжить игру!",
  app_welcome_9: "Ввести данные!",
  app_welcome_10: "Вход в игру",
  app_welcome_11: "Логин",
  app_welcome_12: "Пароль",
  app_welcome_13: "Войти",
  city_buildings_bank_1: "Городской банк",
  city_buildings_bank_2: "Уровень:",
  city_buildings_bank_3: "Определяет количество призовых билетов в рейтинге жителей города, набравших требуемое количество очков",
  city_buildings_bank_4: "Характеристики",
  city_buildings_bank_5: "Требование",
  city_buildings_bank_6: "Сейчас:",
  city_buildings_bank_7: "очков",
  city_buildings_bank_8: "Далее:",
  city_buildings_brickyard_1: "Кирпичный завод",
  city_buildings_brickyard_2: "Позволяет производить кирпичи, необходимые для строительства и улучшения зданий города",
  city_buildings_brickyard_3: "Производство",
  city_buildings_brickyard_4: "Выберите количество:",
  city_buildings_brickyard_5: "ИТОГО:",
  city_buildings_brickyard_6: "Изготовить",
  city_buildings_brickyard_7: "Лимит производства",
  city_buildings_brickyard_8: "шт.",
  city_buildings_brickyard_9: "Условия производсва",
  city_buildings_brickyard_10: "Стоимость кирпича",
  city_buildings_brickyard_11: "Сброс лимита",
  city_buildings_brickyard_12: "раз в сутки",
  city_buildings_brickyard_13: "Производство остановлено",
  city_buildings_brickyard_14: "достигнут суточный лимит",
  city_buildings_brickyard_15: "Улучшение",
  city_buildings_buildings_1: "В здание добавлено ",
  city_buildings_cafe_1: "Кафе",
  city_buildings_cafe_2: "Увеличивает количество выпадающих печенек в печенькопаде",
  city_buildings_cafe_3: "Увеличение сейчас:",
  city_buildings_cafe_4: "После улучшения:",
  city_buildings_cafe_5: "шт.",
  city_buildings_candy_factory_1: "Кондитерский завод",
  city_buildings_candy_factory_2: "Позволяет увеличить время работы ускорителя при его активации",
  city_buildings_candy_factory_3: "Увеличение времени:",
  city_buildings_candy_factory_4: "мин.",
  city_buildings_city_hall_1: "Мэрия",
  city_buildings_city_hall_2: "Отвечает за максимальное число жителей (участников) в городе",
  city_buildings_city_hall_3: "Лимит сейчас:",
  city_buildings_city_hall_4: "жителей",
  city_buildings_city_hall_5: "После улучшения:",
  city_buildings_mill_1: "Мельница",
  city_buildings_mill_2: "Увеличивает шанс выпадения печеньки повышенного уровня во время печенькопада",
  city_buildings_mill_3: "Шанс увеличен:",
  city_buildings_mill_4: "на",
  city_buildings_success_1: "Стройка завершена!",
  city_buildings_success_2: "Уровень здания повышен до",
  city_buildings_success_3: "-го",
  city_buildings_success_4: "Эффективность увеличена!",
  city_buildings_success_5: "Отлично!",
  city_buildings_success_6: "Лимит производства",
  city_buildings_success_7: "Лимит жителей в городе:",
  city_buildings_success_8: "Награды и требования",
  city_buildings_success_9: "Требование",
  city_buildings_success_10: "очков",
  city_buildings_success_11: "Печенек в печенькопаде:",
  city_buildings_success_12: "Шанс выпадения печеньки повышенного уровня:",
  city_buildings_success_13: "Время работы ускорителя:",
  city_buildings_success_14: "Здание не найдено!",
  city_buildings_upgrade_1: "Улучшение",
  city_buildings_upgrade_2: "Достигнут максимальный уровень",
  city_buildings_upgrade_3: "Требуется печенек",
  city_buildings_upgrade_4: "Требуется кирпичей",
  city_buildings_upgrade_5: "Купить",
  city_buildings_upgrade_6: "Произвести",
  city_buildings_upgrade_7: "Добавить",
  city_buildings_upgrade_8: "Недостаточно печенек!",
  city_buildings_upgrade_9: "Недостаточно кирпичей!",
  city_buildings_upgrade_10: "Ожидание кирпичей",
  city_buildings_upgrade_11: "Ожидание печенек",
  city_buildings_upgrade_12: "Прогресс:",
  city_chat_1: "Ваше сообщение...",
  city_chat_2: "Новое сообщение в городском чате!",
  city_chat_3: "Несколько новых сообщений городском чате!",
  city_city_panel_1: "Вы еще не присоединились к городу",
  city_city_panel_2: "Ваш баланс",
  city_city_panel_3: "кирпичей",
  city_city_panel_4: "печенек",
  city_city_panel_5: "в сети:",
  city_control_changes_1: "Аватар - выберите изображение для вашего города. Некоторые из них, вы сможете разблокировать позже.",
  city_control_changes_2: "Посмотреть и выбрать",
  city_control_changes_3: "Название - цензурное, привлекательное и запоминающееся название вашего города",
  city_control_changes_4: "Описание - цензурное, краткое описание вашего города, можно не заполнять.",
  city_control_changes_5: "Доступность - выберите тип социальной доступности вашего города.",
  city_control_changes_6: "Публичный",
  city_control_changes_7: "- виден всем в списке случайных городов;",
  city_control_changes_8: "- присоединиться к вашему городу может любой игрок;",
  city_control_changes_9: "Закрытый",
  city_control_changes_10: "- не виден в списке случайных городов;",
  city_control_changes_11: "- игрок присоединяется к городу только после вашего одобрения;",
  city_control_changes_12: "печенек",
  city_control_changes_13: "Акция, осталось: ",
  city_control_control_1: "После выхода вы не сможете вступить в другой город в течение суток!",
  city_control_control_2: "Вы - мэр этого города и не можете покинуть свой город, пока в нем есть другие жители!",
  city_control_control_3: "Покинуть город",
  city_control_control_4: "Здесь можно покинуть город, в котором вы сейчас находитесь в качестве жителя.\r\nПокинув город, вы потеряете все его преимущества.",
  city_control_control_5: "Выйти из этого города",
  city_control_logo_1: "Настройка",
  city_control_logo_2: "аватара",
  city_control_logo_3: "Случайно",
  city_control_logo_4: "Сохранить",
  city_control_members_1: "Жители города",
  city_control_members_2: "За неделю",
  city_control_members_3: "За все время",
  city_control_members_4: "Открыть профиль",
  city_control_members_5: "Выгнать из города",
  city_control_notes_1: "Напишите здесь все, что хотите например приветствие, новости, правила, инструкции, пожелания. Этот текст увидят все жители вашего города.",
  city_control_notes_2: "Кодекс города",
  city_control_notes_3: "Написать",
  city_control_notes_4: "Отмена",
  city_control_notes_5: "Сохранить",
  city_control_requests_1: "Отсутствуют",
  city_control_requests_2: "Заявки на вступление",
  city_control_requests_3: "заявка одобрена",
  city_control_summary_1: "Сводка города",
  city_control_summary_2: "Информация",
  city_control_summary_3: "Мэр:",
  city_control_summary_4: "Жителей в городе:",
  city_control_summary_5: "Дата основания:",
  city_control_summary_6: "из",
  city_control_summary_7: "Активность за неделю",
  city_control_summary_8: "Баллов получено:",
  city_control_summary_9: "Соединений сделано:",
  city_control_summary_10: "Здания",
  city_control_summary_11: "Уровень:",
  city_control_summary_12: "Кирпичей:",
  city_control_summary_13: "Печенек:",
  city_control_summary_14: "д.",
  city_control_summary_15: "макс.",
  city_header_1: "Беседа",
  city_help_page_1: "1. Что такое город?",
  city_help_page_2: "Это социальная механика, позволяющая объединяться вместе с другими игроками и получать хорошие бонусы.",
  city_help_page_3: "2. Что можно делать в городе?",
  city_help_page_4: "Общаться в чате, улучшать городские здания, соревноваться с другими жителями и городами за бонусы. Список будет расти.",
  city_help_page_5: "3. Зачем улучшать здания?",
  city_help_page_6: "Каждое здание даёт свой уникальный бонус.",
  city_help_page_7: "Например, кафе увеличивает количество выпадающих печенек в печенькопаде, а кондитерский завод увеличивает время работы ускорителя дохода.",
  city_help_page_8: "4. Как улучшать здания?",
  city_help_page_9: "Здания улучшаются за печеньки и кирпичи.",
  city_help_page_10: "Кирпичи - городская валюта, покупаемая за серебро на кирпичном заводе.",
  city_help_page_11: "Стоимость кирпичей для всех игроков равна и измеряется в часах дохода.",
  city_help_page_12: "5. Кто такой мэр?",
  city_help_page_13: "Мэр - это создатель города.",
  city_help_page_14: "Он может менять аватар, название, описание и приватность города.",
  city_help_page_15: "В его праве принимать и выгонять жителей.",
  city_help_page_16: "Он видит вклад каждого жителя.",
  city_help_page_17: "Роль мэра нельзя передать другому жителю.",
  city_help_page_18: "6. Зачем нужен рейтинг жителей?",
  city_help_page_19: "Самые активные жители получают билеты в Колесо фортуны после каждого конца недели.",
  city_help_page_20: "Призы и требования зависят от уровня улучшения банка.",
  city_help_page_21: "Чтобы получить билеты в Колесо Фортуны, необходимо набрать минимум 100 баллов вклада.",
  city_help_page_22: "Топ 3 жителя получают повышенные призы.",
  city_help_page_23: "7. Как набрать баллы для рейтинга жителей?",
  city_help_page_24: "Баллы суммируются из количества вложенных кирпичей и печенек в улучшение зданий.",
  city_help_page_25: "За 1 кирпич - 1 балл.",
  city_help_page_26: "За 1 печеньку - 10 баллов.",
  city_help_page_27: "8. Зачем нужен рейтинг городов?",
  city_help_page_28: "Рейтинг строится из суммы соединений печенек среди всех жителей города.",
  city_help_page_29: "Позволяет повысить популярность своего города и привлечь самых активных игроков.",
  city_help_page_30: "Помощь",
  city_help_page_31: "Часто задаваемые вопрос",
  city_leaders_1: "Недельный",
  city_leaders_2: "Месячный",
  city_leaders_3: "Общий",
  city_leaders_4: "Рейтинг городов",
  city_members_1: "Рейтинг жителей",
  city_members_2: "Правила рейтинга",
  city_members_rules_1: "Правила",
  city_members_rules_2: "Рейтинг строится на баллах (очках), которые жители могут получать\r\nза активную игру и поддержку своего города.",
  city_members_rules_3: "За что можно получить баллы:",
  city_members_rules_4: "- внесение кирпичей в здание",
  city_members_rules_5: "1 кирпич =",
  city_members_rules_6: "балл",
  city_members_rules_7: "- внесение печенек в здание",
  city_members_rules_8: "1 печенька =",
  city_members_rules_9: "баллов",
  city_members_rules_10: "В еженедельном рейтинге у жителей есть шанс получить ценные призы.",
  city_members_rules_11: "Чтобы увеличить количество призов, улучшайте Городской банк.",
  city_no_items_1: "Произошла какая-то ошибка, попробуйте позже",
  city_no_items_2: "Список пуст :(",
  city_overview_page_1: "Закрытый",
  city_overview_page_2: "Публичный",
  city_overview_page_3: "Описание",
  city_overview_page_4: "Вступить",
  city_overview_page_5: "Отправить заявку",
  city_overview_page_6: "Сведения о городе",
  city_overview_page_7: "Информация",
  city_overview_page_8: "Тип:",
  city_overview_page_9: "Жителей:",
  city_overview_page_10: "Основан:",
  city_overview_page_11: "д.",
  city_overview_page_12: "Постройки",
  city_overview_page_13: "Мэрия:",
  city_overview_page_14: "уровень",
  city_overview_page_15: "Городской банк:",
  city_overview_page_16: "Кафе:",
  city_overview_page_17: "Кондитерский завод:",
  city_overview_page_18: "Мельница:",
  city_overview_page_19: "из",
  city_overview_page_20: "Кирпичный завод:",
  city_search_buttons_1: "Принять",
  city_search_buttons_2: "Вступить",
  city_search_buttons_3: "Подать заявку",
  city_search_buttons_4: "Отозвать",
  city_search_buttons_5: "Вас приглашают",
  city_search_random_1: "Случайные города",
  city_search_random_2: "Ваши заявки",
  city_search_search_1: "Создать город",
  city_search_search_panel_1: "Ничего не найдено",
  city_search_search_panel_2: "Введите что-нибудь и нажмите найти",
  city_search_search_panel_3: "Поиск городов",
  city_search_search_panel_4: "Найти",
  city_search_search_panel_5: "Название...",
  city_tutorial_free_panel_1: "Вероятно, свободных городов пока нет.",
  city_tutorial_free_panel_2: "Создай свой город бесплатно!",
  city_tutorial_free_panel_3: "Вступи в город который тебе по душе или создай за печеньки свой собственный!",
  city_tutorial_free_panel_4: "Свободные города",
  city_tutorial_free_panel_5: "Вступить",
  city_tutorial_hints_1: "Понятно",
  city_tutorial_tutorial_1: "Создать свой город",
  city_welcome_page_1: "Добро пожаловать",
  city_welcome_page_2: "в твой личный город!",
  city_welcome_page_3: "Теперь ты мэр, хозяин города",
  city_welcome_page_4: "Приглашай к себе игроков, общайся в чате с жителями города, улучшай здания и получай бонусы в игре.\r\nДобейся лидирующих позиций в рейтинге других городов!",
  city_welcome_page_5: "Настало время хорошего правителя. Сделай свой город лучшим!",
  city_welcome_page_6: "Вперед!",
  city_welcome_page_7: "в город",
  city_welcome_page_8: "Улучшай здания и получай за это бонусы в игре,\r\nобщайся с другими жителями в чате, а также\r\nсоревнуйся с другими городами.",
  city_welcome_page_9: "Будь примерным жителем города :)",
  cookies_shop_item_1: "Создай",
  cookies_shop_item_2: "-й уровень",
  cookies_shop_item_buy: "Купить за:",
  cookies_shop_item_sec: "/сек",
  cookies_shop_title: "Магазин",
  crush_btn: "Разломить",
  extra_menu_battle: "Битва",
  extra_menu_my_city: "Мой город",
  free_cookies_1: "Выполни задания и каждый день забирай здесь награду!",
  free_cookies_2: "Делай репосты и получай за каждого зашедшего нового игрока по твоим ссылкам",
  free_cookies_3: "только за тех кто никогда не открывал приложение раньше и разломит хотя бы три печеньки",
  free_cookies_4: "Приглашай друзей и забирай здесь печеньки когда они начнут играть!",
  free_cookies_5: "за каждого!",
  free_cookies_vk_2: "Делай репосты, приглашая друзей, и получай за каждого зашедшего по твоим ссылкам нового игрока",
  free_cookies_vk_3: "только за тех друзей кто никогда не открывал приложение раньше и разломит хотя бы три печеньки",
  free_cookies_get: "Забрать",
  free_cookies_gifts: "Подарки",
  free_cookies_in_day: "в день",
  free_cookies_invite: "Пригласить друга",
  free_cookies_perform: "Выполнить",
  free_cookies_promo: "Твои промокоды",
  free_cookies_promo_codes_active: "Активен до ",
  free_cookies_promo_codes_copy: "Скопировать",
  free_cookies_promo_codes_send: "Отправить в ЛС",
  free_cookies_promo_codes_title: "Ваши промокоды",
  free_cookies_received: "Получено",
  free_cookies_story: "Поделись в истории",
  free_cookies_wall: "Поделись на стене",
  free_cookies_share: "Поделиться игрой",
  game_Free: "Бесплатно",
  game_rain_enabled: "Включен!",
  game_for_prize: "Призовой!",
  game_rain: "Печенькопад",
  game_rocket: "Ускоритель",
  game_sale: "Акция",
  game_shop: "Рынок",
  game_battle_leaders_1: "Лучшие за сегодня",
  game_battle_leaders_2: "Приз",
  game_battle_lobby_close: "закрыть",
  game_battle_lobby_connection: "Подключение...",
  game_battle_lobby_duel: "Состязание",
  game_battle_lobby_go: "Вперед!",
  game_battle_lobby_training: "Учебный бой",
  game_battle_merge_1: "Соединяй печеньки как можно быстрей, обгони соперника по количеству соединений.",
  game_battle_merge_2: "Выиграй его ставку!",
  game_battle_merge_3: "Выберите ставку для игры:",
  game_battle_merge_cookie: "Печенька",
  game_battle_result_1: "Еще раз!",
  game_battle_result_close: "закрыть",
  game_battle_result_cookie: "печенька",
  game_battle_result_draw_mess: "Вы вернули:",
  game_battle_result_draw_title: "Ничья!",
  game_battle_result_loss_mess: "Вы проиграли:",
  game_battle_result_loss_title: "Поражение!",
  game_battle_result_win_mess: "Вы получили:",
  game_battle_result_win_title: "Победа!",
  game_battle_select_rival_1: "Поиск соперника",
  game_battle_select_rival_2: "ищем в кладовых сервера",
  game_battle_select_rival_3: "отмена",
  game_battle_tutorial_next: "Далее",
  game_battle_tutorial_res_1: "Ура, победа за Вами! Самое время сыграть с настоящим противником!",
  game_battle_tutorial_res_2: "Победа!",
  game_battle_tutorial_res_3: "Ничего страшного! Попробуйте пройти обучение ещё раз!",
  game_battle_tutorial_res_4: "Поражение!",
  game_battle_tutorial_res_5: "Ничья!",
  game_battle_tutorial_res_6: "закрыть",
  game_battle_tutorial_res_7: "Тренировка завершена!",
  game_battle_tutorial_res_8: "Назад",
  game_cookie_rain_layer_1: "Успевай соединять",
  game_cookie_rain_layer_2: "печеньки!",
  game_cookie_rain_layer_3: "Освобождай место",
  game_cookie_rain_layer_4: "для печенькопада!",
  game_cost: "Стоимость",
  game_counter_soft_1: "От ускорителя",
  game_counter_soft_sec: "/c",
  game_leagues: "Лиги",
  game_leagues_tutorial_1: 'Поздравляем\nТы разблокировал лиги!',
  game_leagues_tutorial_2: 'Это соревнование с другими игроками за',
  game_leagues_tutorial_2_1: 'призовые печеньки',
  game_leagues_tutorial_3: 'Хорошо',
  game_leagues_tutorial_4: 'Объединяя печеньки ты получаешь',
  game_leagues_tutorial_4_1: 'очки соединений',
  game_leagues_tutorial_5: 'Другие игроки не дремлют и также получают свои очки соединений.',
  game_leagues_tutorial_6: 'Понятно',
  game_leagues_tutorial_7: 'Лига длится одну неделю, этот таймер показывает',
  game_leagues_tutorial_7_1: 'время до ее завершения',
  game_leagues_tutorial_8: 'Успей войти в',
  game_leagues_tutorial_8_1: 'первую десятку',
  game_leagues_tutorial_8_2: 'игроков своей лиги.',
  game_leagues_tutorial_9: 'Получи',
  game_leagues_tutorial_9_1: 'печеньки',
  game_leagues_tutorial_9_2: 'и переходи в следующую, более',
  game_leagues_tutorial_9_3: 'крутую лигу',
  game_leagues_tutorial_10: 'Соединять!',
  game_main_am_unlock_rain: 'Нужна печенька 5-го уровня!',
  game_main_am_unlock_rocket: 'Требуется печенька 6-го уровня!',
  game_main_am_unlock_income: 'Откроется на 7-м уровне!',
  game_main_am_unlock_plates: 'Необходима печенька 8-го уровня!',
  game_main_biggest_1: "Поздравляем!",
  game_main_biggest_2: "Новый уровень печеньки!",
  game_main_biggest_3: "Отлично!",
  game_main_left_menu_1: "Город",
  game_main_left_menu_2: "Битва",
  game_main_left_menu_3: "Лиги",
  game_main_left_menu_4: "Рынок",
  game_main_left_menu_leagues: 'Чтобы разблокировать лиги,\nполучи печеньку 7-го уровня!',
  game_main_left_menu_city: 'Города будут доступны\nпосле 10-го уровня печеньки!',
  game_main_rain_3: "Вызови дождь из печенек на свой игровой стол",
  game_main_rain_4: "Запустить",
  game_main_rocket_1: "Активируй турбо доход на несколько часов",
  game_main_rocket_2: "Активировать",
  game_main_tab_1: "Улучшения",
  game_main_tab_2: "Быстрая покупка",
  game_main_sack_take: 'Забрать',
  game_main_tutor_1: "Соедини одинаковые печеньки",
  game_main_tutor_2: "Купи несколько печенек на стол",
  game_main_tutor_3: "Получи печеньку 4-го уровня",
  game_main_tutor_4: "Привет!",
  game_main_tutor_5: "Цель игры -",
  game_main_tutor_6: "соединять печеньки",
  game_main_tutor_7: ", чтобы открывать новые классные печеньки!",
  game_main_tutor_8: "Давай начнем соединять и посмотрим, что будет.",
  game_main_tutor_9: "Погнали!",
  game_main_tutor_10: "Покупка!",
  game_main_tutor_11: "Супер! Но больше соединять нечего.",
  game_main_tutor_12: "Надо",
  game_main_tutor_13: "купить еще",
  game_main_tutor_14: "печенек на стол, чтобы продолжить играть!",
  game_main_tutor_15: "Давай купим их через меню быстрой покупки.",
  game_main_tutor_16: "Вперед!",
  game_main_tutor_17: "Монетки!",
  game_main_tutor_18: "Каждая печенька на столе",
  game_main_tutor_19: "зарабатывает",
  game_main_tutor_20: "монетки.",
  game_main_tutor_21: "Чем выше уровень печеньки, тем больше монеток она",
  game_main_tutor_22: "зарабатывает за секунду",
  game_main_tutor_23: "Соедини купленные печеньки, чтобы получить новый уровень!",
  game_main_tutor_24: "Понятно!",
  game_main_tutor_25: "Отлично!",
  game_main_tutor_26: "Продолжай играть, покупай и соединяй печеньки, открывай новые уровни.",
  game_main_tutor_27: "Выполняй задания и получай",
  game_main_tutor_28: "награды",
  game_main_tutor_29: ", используй различные улучшения!",
  game_main_tutor_30: "Разблокируй",
  game_main_tutor_31: "лиги",
  game_main_tutor_32: " и поборись за",
  game_main_tutor_33: "призы",
  game_main_tutor_34: "с другими игроками!",
  game_main_tutor_35: "Играть!",
  game_income: 'Оффлайн доход',
  game_income_max: "Достигнут максимум",
  game_income_description: "Зарабатывай еще больше серебра когда ты не в игре!",
  game_income_level: "Уровень",
  game_income_upgrade: "Улучшить",
  game_income_prize: "Приз!",
  game_leagues_1: " победителей получают печеньки",
  game_leagues_2: " победителей переходят в новую лигу и получают печеньки",
  game_leagues_3: "Зона понижения лиги",
  game_plates_footer_1: "Улучшай тарелочки и печеньки, которые на них лежат, они будут приносить больше на Х дохода!",
  game_plates_footer_2: "Расставляй лучшие печеньки на лучшие тарелочки!",
  game_plates_footer_done: "Готово",
  game_plates_plates_sale: "Акция закончится через:",
  invite_invite_1: "Похоже, что все твои друзья уже играют в печеньку",
  invite_invite_2: "Произошла какая-то ошибка, попробуйте позже",
  invite_invite_3: "Зови друзей и получи награду, когда они начнут играть и разломят хотя бы три печеньки",
  invite_invite_title: "Почта",
  invite_list_item_invite: "Пригласить",
  invite_list_item_invited: "Приглашен",
  league_bronze: "Бронзовая лига",
  league_gold: "Золотая лига",
  league_platinum: "Платиновая лига",
  league_ruby: "Рубиновая лига",
  league_silver: "Серебряная лига",
  loading_1: "получаем ваши данные",
  main_ad_video_rb_view: "Смотреть!",
  main_ad_video_rb_limit: "Неактивно\nдо завтра",
  main_ad_video_rb_popup: "Награда за рекламу будет доступна немного позже!",
  main_app_banner_1: "Напеки еще больше печенек!",
  main_app_banner_2: "у тебя есть промокоды",
  main_app_banner_3: "Используй их до истечения срока!",
  main_crush_button_text_1: "Разломить еще",
  main_crush_button_text_2: "Разломить за",
  main_crush_tutorial_1: "Поздравляем!",
  main_crush_tutorial_2: "Это твоё предсказание.",
  main_crush_tutorial_3: "Понятно",
  main_crush_tutorial_4: "Приходи завтра",
  main_crush_tutorial_5: "и получай раз в день",
  main_crush_tutorial_6: "бесплатную печеньку!",
  main_crush_tutorial_7: "Хочешь сейчас получить",
  main_crush_tutorial_8: "бесплатные печеньки?",
  main_crush_tutorial_9: "Заходи сюда!",
  main_crush_tutorial_10: "Обязательно заходи в игру.",
  main_crush_tutorial_11: "Там тоже можно получить",
  main_crush_tutorial_12: "бесплатные печеньки!",
  main_crush_tutorial_13: "Завтра тебя будет ждать",
  main_crush_tutorial_14: "новое предсказание,",
  main_crush_tutorial_15: "подпишись, чтобы не забыть!",
  main_crush_tutorial_16: "Подписаться",
  main_crush_tutorial_17: "Понятно",
  main_footer_dating: "Знакомства",
  main_footer_free_cookies: "Бесплатные печеньки",
  main_footer_game: "Игра",
  main_footer_hint: "Печеньки!",
  main_footer_profile: "Профиль",
  main_footer_rating: "Рейтинг",
  main_free_timer_text_1: "Бесплатная",
  main_free_timer_text_2: "Получить",
  main_main_cookie_text_1: "Как вам предсказание?",
  main_share_buttons_invite: "Пригласить друга",
  main_share_buttons_published: "Опубликовано",
  main_share_buttons_story: "В историю",
  main_share_buttons_wall: "На стену",
  main_share_buttons_share: "Поделиться",
  modals_battle_help_1: "Добро пожаловать в режим PvP - битвы с живым игроком.",
  modals_battle_help_2: "В этом режиме Вам предстоит за короткое время выполнить больше соединений печенек, чем Ваш соперник.",
  modals_battle_help_3: "На старте даны 3500 серебра и возможность использовать печенькопад за одну печеньку из Вашей ставки.",
  modals_battle_help_4: "Вы и соперник делаете ставку и начинаете сражение. Если побеждаете Вы, то получаете назад то, что осталось от вашей ставки и полную ставку соперника.",
  modals_battle_help_5: "Если же Вы проиграли, Вы теряете вашу ставку, ее забирает себе соперник.",
  modals_battle_help_6: "Удачи в битвах!",
  modals_battle_help_ok: "Понятно",
  modals_battle_help_title: "Сражения: помощь",
  modals_bonus_spwp_1: "Поздравляем!",
  modals_bonus_spwp_2: "По Вашим ссылкам пришло новых игроков:",
  modals_bonus_spwp_3: "Награда:",
  modals_bonus_spwp_4: "Блестяще!",
  modals_bonus_spwp_5: "Забрать",
  modals_bonus_spwp_title: "Награда за приглашенных",
  modals_common_ok: "Ок",
  modals_common_title: "Информация",
  modals_exit_battle_question: 'Покинуть битву?',
  modals_exit_battle_description_1: 'Тренировка будет завершена',
  modals_exit_battle_description_2: 'Ты проиграешь бой, а также свои печеньки',
  modals_exit_battle_accept: 'Да\nпокинуть',
  modals_exit_battle_reject: 'Нет\nостаться',
  modals_modal_no_bricks_1: "О нет!",
  modals_modal_no_bricks_2: "У тебя не хватает",
  modals_modal_no_bricks_3: "Кирпичи производятся в городах, на кирпичном заводе.",
  modals_modal_no_bricks_4: "Ок",
  modals_no_hard_hint_shop: "Возвращайся завтра\nили пополни баланс!",
  modals_no_hard_hint_no_shop: "Возвращайся завтра\nи получи бесплатные печеньки!",
  modals_no_hard_offer_ad: "Получи печеньку\nза рекламу",
  modals_no_hard_watch_ad: "Смотреть",
  modals_no_hard_no: "О нет!",
  modals_no_hard_not_enough: "У тебя не хватает",
  modals_no_hard_ok: "Понятно",
  modals_no_hard_shop: "В магазин",
  modals_offer_notify_1: "Бесплатная печенька появится через некоторое время.",
  modals_offer_notify_2: "Напомнить Вам о появлении новой?",
  modals_offer_notify_ok: "Хорошо",
  modals_offline_1: "Потеряна связь с сервером",
  modals_offline_ok: "ОК",
  modals_offline_profit_1: "Пока тебя не было,",
  modals_offline_profit_2: "печеньки заработали",
  modals_offline_profit_3: "Время оффлайн дохода",
  modals_offline_profit_4: "0 ч",
  modals_offline_profit_5: "Утроить!",
  modals_offline_profit_6: "Забрать х3",
  modals_offline_profit_get: "Забрать",
  modals_offline_profit_hour: " ч.",
  modals_offline_profit_min: " м.",
  modals_offline_profit_title: "Доход",
  modals_ping_screen_back: "назад",
  modals_ping_screen_connection: "Соединение...",
  modals_promo_code_1: "Условия получения",
  modals_promo_code_2: "Активируйте на",
  modals_promo_code_3: "Скопировать промокод",
  modals_promo_code_4: "Срок активации до:",
  modals_promo_code_5: "Все подарки находятся здесь, в разделе «Твои промокоды»",
  modals_promo_code_6: "Бесплатные",
  modals_promo_code_7: "печеньки",
  modals_promo_code_8: "Отправить в ЛС",
  modals_promo_code_9: "Продолжить",
  modals_promo_code_10: "Реклама",
  modals_search_ads_1: "Подбор рекламы",
  modals_session_error_1: "Кажется, вы уже вошли в игру на другом устройстве!",
  modals_session_error_2: "Чтобы продолжить играть здесь, нажмите на кнопку ниже",
  modals_session_error_3: "Использовать это устройство",
  modals_session_error_oops: "Упс!",
  modals_technical_works_1: "Проводятся технические работы. Приложение временно недоступно. Приносим свои извинения.",
  modals_tester_settings_1: "Постоянный туториал разлома",
  modals_tester_settings_2: "Постоянные советы по мердж игре",
  modals_tester_settings_3: "Боевой",
  modals_tester_settings_4: "Тестовый",
  modals_tester_settings_6: "Закрыть",
  modals_tester_settings_title: "Тесты",
  modals_welcome_city_1: "Заявка одобрена!",
  modals_welcome_city_2: "Мэр города одобрил твой запрос на вступление.",
  modals_welcome_city_3: "Поспеши посетить свой город, узнай о полученных бонусах и пообщайся с другими жителями!",
  modals_welcome_city_4: "В город!",
  modals_wheel_prize_get: "Получить",
  modals_wheel_prize_open: "Открыть!",
  modals_winner_gift_1: ", тебе выпал подарок! Поздравляем!",
  modals_winner_gift_accept: "Принять",
  predict_download_1: "Изучаем горизонты завтрашнего дня",
  predict_download_2: "Прогнозируем будущее",
  predict_download_3: "Расшифровываем тайны времени",
  predict_download_4: "Анализируем перспективы",
  predict_download_5: "Открываем завтра",
  predict_download_6: "Исследуем пути вперед",
  predict_download_7: "Приоткрываем завесу времени",
  predict_download_8: "Вглядываемся в грядущее",
  predict_download_9: "Разгадываем код завтрашнего дня",
  predict_download_10: "Изучаем небесные тела",
  predict_download_11: "Взираем на космические просторы",
  predict_download_12: "Исследуем звездное небо",
  predict_download_13: "Разглядываем космос",
  predict_download_14: "Осматриваем звездную карту",
  predict_download_15: "Заглядываем в глубины вселенной",
  predict_download_16: "Ищем ответы у высших сил",
  predict_download_17: "Обращаемся к мудрости Вселенной",
  predict_download_18: "Ведем диалог с божественным",
  predict_download_19: "Исследуем мистические знания",
  predict_download_20: "Соединяемся с невидимым миром",
  predict_download_21: "Запрашиваем пророчества",
  predict_download_22: "Слушаем голоса с высот",
  predict_download_23: "Толкуем знаки судьбы",
  predict_download_24: "Извлекаем мудрость из космического эфира",
  predict_download_25: "Спрашиваем у мудрецов",
  predict_download_26: "Размышляем над вечным",
  predict_download_27: "Ищем совета у старших сил",
  predict_download_28: "Вникаем в тайны магии",
  predict_download_29: "Обращаемся к источникам мудрости",
  predict_download_30: "Задаем вопросы космическому сознанию",
  profile_cookies_counter: "Ваш баланс:",
  profile_gift_page_inventory: "Инвентарь",
  profile_gift_page_shop: "Магазин",
  profile_item_friend_select: "Выбрать",
  profile_item_shop_gift_hit: "хит",
  profile_no_items_1: "Увы, вам пока ничего не подарили.",
  profile_no_items_2: "Сделайте подарок другу и вероятно, он вам ответит!",
  profile_no_items_3: "Подарить другу",
  profile_no_items_4: "Увы, вам пока не выпал бесплатный подарок.",
  profile_no_items_5: "Случайные подарки можно получить вскрывая предсказания или выиграть их в колесе фортуны",
  profile_no_items_6: "Также, вы можете выбрать любой подарок за печеньки",
  profile_no_items_7: "Выбрать",
  profile_no_items_8: "Увы, никто из ваших друзей пока не играет в «Печеньку»",
  profile_no_items_9: "Произошла какая-то ошибка, попробуйте позже",
  profile_no_items_10: "Список пуст :(",
  profile_no_items_11: "Поиск не дал результатов",
  profile_open_gift_page_1: "Подарил:",
  profile_open_gift_page_2: "Поставить на витрину",
  profile_open_gift_page_3: "Принять",
  profile_page_1: "Открыто предсказаний:",
  profile_page_2: "Максимальный уровень печеньки:",
  profile_page_3: "Максимальный уровень лиги:",
  profile_page_4: "Инвентарь",
  profile_page_5: "Сохранись",
  profile_page_title: "Профиль",
  profile_received_gift_1: "Отправитель:",
  profile_received_gift_put: "Установлен",
  profile_received_gift_showcase: "На витрину",
  profile_received_gift_title: "Открыть новый подарок",
  profile_received_page_1: "Полученные подарки",
  profile_select_friend_page_1: "Кому подарить:",
  profile_select_friend_page_2: "Найти друга в списке",
  profile_send_gift_page_1: "Подарок",
  profile_send_gift_page_send: "Отправить",
  profile_user_gifts_1: "Подарить другу",
  profile_user_gifts_2: "Подарить",
  profile_user_gifts_3: "Получено подарков:",
  profile_user_gifts_watch: "Посмотреть",
  rating_1: "Узнай результаты в нашей",
  rating_2: "официальной группе",
  rating_3: "Кто съел больше?",
  rating_all: "Все время",
  rating_list_1: "Никого еще нет",
  rating_list_2: "станьте первым",
  rating_list_3: "Произошла ошибка",
  rating_list_4: "данные не получены, попробуйте позже",
  rating_month: "За месяц",
  rating_today: "Сегодня",
  rating_week: "За неделю",
  store_ad_1: "Что-то сломалось, мы не смогли выдать вам награду.",
  store_ad_2: "Увы, вы закрыли рекламу, попробуйте еще раз.",
  store_ad_3: "К сожалению, не удалось подобрать рекламу. Попробуйте позже.",
  store_ad_5: "Рекламы сейчас нет.",
  store_ad_6: "Попробуй проверить на компьютере, там она бывает чаще.",
  store_ad_7: "Только не забудь отключить VPN и блокировщик рекламы",
  store_app_authorization_1: "Успешный вход!",
  store_app_authorization_2: "Добро пожаловать",
  store_app_authorization_3: "Нравится игра?",
  store_app_authorization_4: "Записал свои данные?",
  store_app_authorization_5: "Введен некорректный Email",
  store_app_authorization_6: "Повторная отправка будет доступна позже!",
  store_app_authorization_7: "Отлично! Твои данные успешно отправлены на ",
  store_city_buildings_brickyard_1: "Производство завершено: +",
  store_city_city_1: "Ошибка создания города. Напишите в поддержку.",
  store_city_city_2: "Ошибка изменения города. Напишите в поддержку.",
  store_city_city_3: "Ошибка удаления города. Напишите в поддержку.",
  store_city_city_4: "Игрок уже в другом городе.",
  store_city_city_5: "Название города слишком коротко!",
  store_city_city_6: "Некорректное название города!",
  store_city_city_7: "Некорректное описание города!",
  store_city_city_8: "Некорректный логотип!",
  store_city_city_9: "У вас не хватает печенек!",
  store_city_city_10: "У вас не хватает кирпичей!",
  store_city_city_11: "Неудача, в городе еще остались жители!",
  store_city_city_12: "Стыдно, не хулигань!",
  store_city_city_13: "Приглашение уже существует!",
  store_city_city_14: "Увы, город полон!",
  store_city_city_15: "Ой, такого города уже не существует :(",
  store_city_city_16: "Ошибка производства!",
  store_city_city_17: "Ошибка пополнения здания!",
  store_city_city_18: "Неудача! К сожалению, эта акция закончилась.",
  store_city_city_19: "Ошибка:",
  store_city_control_1: "Создание города",
  store_city_control_2: "Основать город",
  store_city_control_3: "Изменение города",
  store_city_control_4: "Сохранить правки",
  store_city_control_5: "Название города не может быть пустым!",
  store_city_control_6: "Неизвестная ошибка",
  store_city_control_7: "Изменения успешно сохранены!",
  store_city_tutorial_1: "На карте города есть здания и они уже дают тебе бонусы!",
  store_city_tutorial_2: "Если улучшать их, ты будешь получать больше бонусов и наград в игре.",
  store_city_tutorial_3: "Тут находится рейтинг жителей города.",
  store_city_tutorial_4: "Соревнуйся с другими жителями, чтобы получать награды!",
  store_city_tutorial_5: "А здесь, рейтинг других городов.",
  store_city_tutorial_6: "Жители должны объединить усилия, чтобы твой город стал лучшим!",
  store_city_tutorial_7: "Ты всегда можешь получить больше информации в окне помощи.",
  store_city_tutorial_8: "Для улучшения города необходимы кирпичи.",
  store_city_tutorial_9: "Чтобы произвести их, открой кирпичный завод.",
  store_city_chat_srv_enter: '@n вступил(а) в город.',
  store_city_chat_srv_leave: '@n покинул(а) город.',
  store_city_chat_srv_upgrade: 'Здание @b улучшено до @l уровня!',
  store_city_chat_srv_donate: '@n совершил(а) щедрый вклад в здание @b @c.',
  store_city_chat_srv_prizes: 'Поздравляем жителей с призовыми местами! :)',
  store_game_battle_1: "Бендер",
  store_game_battle_2: "Родригез",
  store_game_core_1: "У вас не хватает монет!",
  store_game_core_2: "Включено увеличение прибыли до",
  store_game_core_3: "на",
  store_game_core_4: "часа",
  store_game_core_5: "Увеличение прибыли до",
  store_game_core_6: "продлено еще на",
  store_game_core_7: "часа",
  store_game_core_8: "Нельзя удалить максимальную!",
  store_game_core_9: "Нельзя соединить максимальные!",
  store_game_main_1: "Неудача! У вас закончились призы.",
  store_game_main_2: "Неудача! К сожалению, эта акция закончилась.",
  store_game_main_3: "Новый уровень печеньки! ",
  store_game_main_sack_reward: 'Награда успешно получена! +',
  store_game_core_10: "Нет свободного места",
  store_game_tutorial_battle_1: "Приветствуем в обучающей битве, здесь с Вами сразится наш тренировочный соперник!",
  store_game_tutorial_battle_2: "Перед вами представлено игровое поле.",
  store_game_tutorial_battle_3: "Цель игры - соединить больше печенек, чем противник за 60 секунд.",
  store_game_tutorial_battle_4: "Время игры и количество соединений показаны выше.",
  store_game_tutorial_battle_5: "Изначально Вам дано 3500 серебра, за которые Вы можете покупать печенку 1 уровня по 100 серебра за каждую.",
  store_game_tutorial_battle_6: "Начинайте соединять печеньки!",
  store_game_tutorial_battle_7: "Самое время использовать печенькопад!",
  store_game_tutorial_battle_8: "Печенькопад тратит 1 печеньку из Вашей ставки, тем самым уменьшая получаемую награду, зато даёт хорошее преимущество перед противником, облегчая победу.",
  store_main_main_loading: "загрузка...",
  store_profile_profile_1: "Напишите свой комментарий к подарку",
  store_profile_profile_2: "Подарки",
  store_profile_profile_3: "Подарить",
  store_profile_profile_4: "Подарок успешно отправлен!",
  store_profile_profile_5: "Подарить другу",
  store_profile_profile_6: "Сделать подарок",
  store_profile_profile_7: "подарить",
  store_profile_profile_grade_1: "Частый",
  store_profile_profile_grade_2: "Обычный",
  store_profile_profile_grade_3: "Редкий",
  store_profile_profile_grade_4: "Супер редкость!",
  store_profile_gift_buy: 'Подарок добавлен в инвентарь!',
  store_profile_error: 'Что-то пошло не так: ',
  store_rating_1: "За сутки",
  store_rating_2: "С понедельника",
  store_rating_3: "С 1-го числа",
  store_rating_4: "За всё время",
  store_shop_1: "Приносим свои извинения, до окончания модерации, покупки временно недоступны.",
  store_shop_2: "Что то пошло не так, пожалуйста, попробуйте позже.",
  store_shop_3: "«Тройная выгода»",
  store_shop_4: "За первую покупку, получай в три раза больше печенек по обычной цене!",
  store_shop_5: "Умножаем печеньки Х3",
  store_shop_6: "У вас нехватает печенек!",
  store_shop_7: "Ошибка. Пожалуйста обратитесь в поддержку!",
  store_shop_8: "по акции",
  store_shop_9: "в подарок",
  store_shop_10: "и еще",
  store_shop_11: "Вы получили",
  store_shop_12: "Приятной игры!",
  store_shop_processing_popup: "Ваша покупка еще обрабатывается!",
  store_user_user_1: "Вступи в группу",
  store_user_user_2: "Подпишись на уведомления",
  store_user_user_3: "Добавь в избранное",
  store_user_user_4: "Подпишись на лс от группы",
  store_user_user_5: "Напиши в группу «Привет!»",
  store_user_user_6: "Поделись на стене",
  store_wheel_1: "Поздравляем!",
  store_wheel_2: "Ура!",
  store_wheel_3: "Супер!",
  store_wheel_4: "Классно!",
  store_wheel_5: "Крутяк!",
  store_wheel_6: "Успех!",
  store_wheel_7: "Удача!",
  store_wheel_8: "Здорово!",
  store_wheel_9: "Прекрасно!",
  store_wheel_10: "Потрясающе!",
  store_wheel_11: "Джекпот! ",
  store_wheel_12: "Доход серебра за 1 час",
  store_wheel_13: "монеты будут начислены после входа в игру",
  store_wheel_14: "Бесплатный печенькопад",
  store_wheel_15: "выигранные попытки суммируются",
  store_wheel_16: "Небольшой приз: +",
  store_wheel_17: "+1 к уровню оффлайн дохода",
  store_wheel_18: "Доход серебра за 2 часа",
  store_wheel_19: "+50 соединений в игре",
  store_wheel_20: "покоряй лиги, получай призы",
  store_wheel_21: "Большой приз: +",
  store_wheel_22: "Бесплатный ускоритель дохода",
  store_wheel_23: "Доход серебра за 30 минут",
  store_wheel_24: "Подарок в коллекцию",
  store_wheel_25: "его можно кому-нибудь подарить",
  store_wheel_26: "Доход серебра за 4 часа",
  store_wheel_27: "Похоже, у тебя не осталось бесплатных билетов!",
  welcome_but_proceed: "Продолжить",
  welcome_text: "Получи бесплатную печеньку и узнавай, когда появляются новые!",
  wheel_1: "Испытай удачу, выиграй главный приз!",
  wheel_2: "Победители:",
  wheel_ad_play_button_1: "Играть",
  wheel_ad_play_button_2: "Бесплатно!",
  wheel_btn_1: "Играть!",
  wheel_btn_2: "Колесо Фортуны пока недоступно.",
  wheel_btn_3: "Приходи завтра, чтобы сыграть!",
  wheel_play_1: "Играть за",
  wheel_title: "Колесо Фортуны",
  wheel_winner_list_item_hour: " час.",
  wheel_winner_list_item_min: " мин.",
  wheel_winner_list_item_sec: " сек.",
  wheel_winner_spin_1: "Вы выиграли",
  wheel_winner_spin_2: "Забрать",
  app_emo_status_title: 'Выбери себе эмодзи‑статус!',
  app_emo_status_1: 'Появится справа от вашего имени и будет виден всем в ',
  app_emo_status_remove: 'убрать статус',
  app_emo_status_done: 'Готово',
  app_loading_offline_title: 'Технические работы' ,
  app_loading_offline_message: 'В приложении проводятся технические работы, приносим свои извинения.\n\nВозвращайтесь к нам немного позже.' ,
  app_loading_agreement_header_1: 'Это важно!',
  app_loading_agreement_header_2: 'Прежде чем начать играть, пожалуйста ознакомьтесь и дайте свое согласие:',
  app_loading_agreement_checkbox_default: 'Принимаю условия соглашения',
  app_loading_agreement_accept: 'Играть',
  app_loading_agreement_decline: 'Покинуть игру',
  chapter_lvl: 'ур.',
  chapter_level: 'уровень',
  chapter_difficulty_easy: 'Легкий',
  chapter_difficulty_medium: 'Средний',
  chapter_difficulty_hard: 'Тяжелый',
  chapter_until_refresh: 'До обновления:',
  chapter_chapter_rank: 'Ранг:',
  chapter_chapter_ended: 'До окончания:',
  chapter_chapter_of: 'из',
  chapter_chapter_difficulty_1: 'Получи',
  chapter_chapter_difficulty_2: ', чтобы перейти на новый ранг!',
  chapter_chapter_difficulty_3: ', чтобы остаться на этом ранге!',
  chapter_chapter_completed_1: 'Приключения этого сезона завершены!',
  chapter_chapter_completed_2: 'Возвращайся немного позже, когда начнется новый сезон.',
  chapter_tasks_hourly: 'Пряничные задания',
  chapter_tasks_daily: 'Ежедневные задания',
  chapter_tasks_weekly: 'Еженедельные задания',
  chapter_hint_m1: 'Переходи в игру и купи несколько печенек на стол через меню «Быстрая покупка» или на «Рынке».',
  chapter_hint_m2: 'Соедини две одинаковые печеньки на своем игровом столе.',
  chapter_hint_m3: 'Активируй ускоритель дохода монет, который находится во вкладке «Улучшения» в игре.',
  chapter_hint_m4: 'Запусти печенькопад в игре. Он находится во вкладке «Улучшения».',
  chapter_hint_m5: 'Соединяй печеньки в игре и повысь уровень своей максимальной печеньки.',
  chapter_hint_m6: 'Улучшай свой уровень оффлайн дохода в игре, находящийся во вкладке «Улучшения».',
  chapter_hint_m7: 'Перейди в раздел улучшения тарелочек (вкладка «Улучшения») и повысь уровень тарелочки',
  chapter_hint_m8: 'На момент завершения твоей лиги в игре, необходимо занимать 20-е место или выше.',
  chapter_hint_m9: 'Заходи в игру с интервалом более 24-х часов, чтобы увеличить прогресс задания.',
  chapter_hint_m10: 'При возвращении в игру, забирай свои монеты оффлайн дохода.',
  chapter_hint_m11: 'Узнай свое место в игровой лиге, проверь свое место еще раз, необходимо, чтобы оно изменилось.',
  chapter_hint_m12: 'Запусти печенькопад и не упусти ни одной печеньки мимо игрового стола, поймав их все.',
  chapter_hint_m13: 'Размести на своем игровом столе необходимое количество печенек с уровнями, идущими по порядку.',
  chapter_hint_m14: 'На твоем игровом столе должно находиться необходимое количество печенек с уровнями идущими по порядку, от твоей самой большей печеньки к меньшей.',
  chapter_hint_m15: 'Активируй «призовой» ускоритель дохода монет, в стоимости должно быть указано «Призовой». Он находится во вкладке «Улучшения» в игре.',
  chapter_hint_m16: 'Запусти «призовой» печенькопад в игре. В стоимости должно быть указано «Призовой».',
  chapter_hint_c1: 'Переходи в свой город и создай несколько кирпичей на «Кирпичном заводе».',
  chapter_hint_c2: 'Посети свой город, выбери любое здание на карте, затем добавь в него печеньки.',
  chapter_hint_c3: 'Загляни в свой город, открой любое здание на карте, затем добавь в него кирпичи.',
  chapter_hint_c4: 'Используй любые действия, чтобы получить некоторое количество баллов для рейтинга жителей города.',
  chapter_hint_c5: '',
  chapter_hint_c6: 'Вернись в город, перейди на вкладку чата и отправь любое сообщение в городской чат.',
  chapter_hint_c7: 'Для увеличения прогресса необходимо заходить в свой город с интервалом более 24-х часов.',
  chapter_hint_f1: 'Открой битвы в игре и проведи любую не тренировочную битву.',
  chapter_hint_f2: 'Сыграй битву и закончи ее, победив своего соперника.',
  chapter_hint_f3: 'Играй битву, соединяй печеньки и закончи ее сделав более 60-ти соединений.',
  chapter_hint_f4: 'Участвуй в битве и закончи ее, имея печеньку минимум 7-го уровня на столе битвы.',
  chapter_hint_f5: 'Играй в разных битвах и покупай за монеты печеньки на стол, каждая потраченная монетка идет в зачет.',
  chapter_hint_p1: 'Получи предсказание, разломив печеньку в любой категории.',
  chapter_hint_p2: 'Выбери любую категорию предсказания, кроме «Ежедневного» и разломи печеньку.',
  chapter_hint_p3: 'Получи любое предсказание и поделись им в любом доступном виде.',
  chapter_hint_p4: 'Открой любое предсказание и оцени его, нажав на кнопку «Палец вверх» или «Палец вниз».',
  chapter_hint_q1: 'Выполни любое задание приключений и нажми кнопку «Забрать», получив звезды опыта.',
  chapter_hint_q2: 'Заверши любое «Пряничное задание» в приключении, нажатием кнопки «Забрать»',
  chapter_hint_q3: 'Нажми кнопку «Забрать» на любом готовом «Ежедневном задании» приключений.',
  chapter_hint_q4: 'Выполняй любые задания приключений и забирай звезды опыта, чтобы повысить свой уровень.',
  chapter_hint_q5: 'Ускоряй «Пряничные задания» кнопкой «Ускорить», используй все возможные ускорения за день, чтобы увеличить прогресс на единицу.',
  chapter_hint_d1: 'Открой «Колесо Фортуны» и раскрути его, испытав удачу. В зачет идет факт кручения.',
  chapter_hint_d2: 'Посети раздел своего профиля, из любого места в приложении.',
  chapter_hint_d3: 'Отправь подарок кому-либо используя кнопки: в чужом профиле - «Подарить» или в своем профиле - «Подарить другу».',
  chapter_hint_d4: 'Можно попросить кого-нибудь отправить тебе подарок, например: друга, жителя города или же сам отправь подарок и дождись ответа.',
  chapter_hint_d5: 'Посмотри любую рекламу с наградой, например: «Ускорение задания», «Колесо фортуны», «+1 печенька« и т.д.',
  chapter_hint_d6: 'Заходи в приложение с интервалом более 24-х часов для увеличения прогресса.',
  chapter_hint_d7: 'Не закрывай приложение в течении необходимого времени. Останься с нами чуть подольше.',
  chapter_hint_d8: 'Потрать печеньки на любые цели: бонусы, улучшения, предсказания..., каждая потраченная печенька идет в зачет.',
  chapter_hint_d9: 'Получи печеньки себе на баланс, например: в «Приключениях», забери «Бесплатные», выиграй в «Колесе Фортуны» и т.д., каждая печенька идет в зачет.',
  chapter_hint_w2: 'Раскрути «Колесо Фортуны» используя бесплатную попытку за рекламу. Учитывается вращение только за рекламу.',
  chapter_hint_w3: 'Испытай свою удачу в «Колесе Фортуны». Выиграй «Монеты», чтобы увеличить прогресс этого задания.',
  chapter_hint_w4: 'Открой «Колесо Фортуны», сыграй, если ты выиграл «Подарок», прогресс будет увеличен.',
  chapter_next_level_greetings: 'Поздравляем!',
  chapter_next_level_proceed: 'Продолжить',
  chapter_next_level_reward: 'Твоя награда',
  chapter_next_level_great: 'Отлично!',
  chapter_next_level_vip_active: 'Статус активен',
  chapter_next_level_vip_offer_1: 'Статус позволит тебе',
  chapter_next_level_vip_offer_2: 'забирать все награды',
  chapter_next_level_missed: 'Пропущенные награды',
  chapter_next_level_more: 'еще',
  chapter_next_level_get_vip_1: 'Получи статус',
  chapter_next_level_get_vip_2: 'чтобы забрать',
  chapter_task_item_reward: 'Награда',
  chapter_task_item_take: 'Забрать',
  chapter_task_item_completed: 'Выполнено',
  chapter_task_item_speedup: 'Ускорить',
  chapter_task_item_next: 'Следующее задание через:',
  chapter_timer_d: 'д.',
  chapter_timer_h: 'ч.',
  chapter_timer_m: 'м.',
  chapter_vip_reward_granted: 'Статус получен!',
  chapter_vip_reward_available: 'Доступны',
  chapter_vip_reward_missed: 'пропущенные награды',
  chapter_vip_reward_hint: 'Пока статус активен, ты получаешь все награды.',
  chapter_vip_reward_take: 'Забрать!',
  chapter_refresh_title: 'Замена задания',
  chapter_refresh_message: 'Если тебе не нравится это задание, то его можно заменить на другое, выбранное случайным образом.',
  chapter_refresh_actions_1: 'Хочешь испытать удачу?',
  chapter_refresh_button: 'Заменить за',
  chapter_refresh_back: 'Назад',
  city_control_members_term_s: ' с.',
  city_control_members_term_m: ' м.',
  city_control_members_term_h: ' ч.',
  city_control_members_term_d: ' д.',
  city_control_requests_term_d: 'д.',
  free_cookies_promo_codes_empty_1: 'У тебя пока нет промокодов :(',
  free_cookies_promo_codes_empty_2: 'Отрывай предсказания, чтобы получать приятные подарки!',
  free_cookies_promo_codes_activate: 'Активируй на',
  free_cookies_promo_codes_show_1: 'Покажи код в магазине,',
  free_cookies_promo_codes_show_2: 'чтобы забрать подарок',
  free_cookies_promo_codes_gift_1: 'Активируй этот промокод',
  free_cookies_promo_codes_gift_2: 'и получи в подарок',
  free_cookies_promo_codes_condition: '[условия]',
  game_counter_soft_vip: 'От VIP-статуса',
  game_battle_result_exit_title: 'Дисквалификация',
  game_battle_result_exit_message: 'Вы вышли из битвы досрочно и проиграли:',
  game_task_tracker_season: 'Сезон завершен. Заданий пока нет.',
  game_task_tracker_until_next: 'До нового задания:',
  game_market_title: 'Рынок',
  game_market_cookies: 'Печеньки',
  game_market_coins: 'Монетки',
  main_app_banner_promo: 'Промокод',
  main_app_banner_reward: 'Награда за активацию',
  main_categories_title_1: 'ВЫБЕРИ РУБРИКУ',
  main_categories_title_2: 'ПРЕДСКАЗАНИЯ',
  main_categories_back: 'Назад',
  main_crush_button_more_wishes: 'Еще пожелания',
  main_crush_button_crush_wishes: 'Разломить',
  main_crush_button_want_wishes: 'Хочу пожеланий!',
  main_crush_button_view_wishes: 'Смотреть список',
  main_crush_button_prize_crush: 'Разломить',
  main_crush_button_prizes: 'Бесплатных:',
  main_crush_tutorial_share_1: 'Делись предсказаниями',
  main_crush_tutorial_share_2: 'с друзьями отправляя виджет',
  main_crush_tutorial_share_3: 'приложения в чаты!',
  main_footer_promo: 'Твои промокоды',
  main_footer_chapter_1: 'Задачи',
  main_footer_chapter_2: 'приключений',
  main_main_cookie_complaint: '[жалоба]',
  main_main_cookie_empty_wishes: 'Нет новых пожеланий.',
  main_main_cookie_count_wishes: 'У тебя',
  main_share_buttons_sender: 'Кто прислал?',
  main_share_buttons_reveal: 'Узнать за',
  main_share_buttons_view_1: 'Смотреть',
  main_share_buttons_view_2: 'пожелания',
  main_share_buttons_to_chat: 'Отправить в чат',
  modals_complaint_complaint: 'Пожаловаться',
  modals_complaint_attention: 'Все пожелания полученные от этого отправителя будут удалены и он не сможет отправить тебе новые пожелания.',
  modals_complaint_blocking_1: 'Заблокировать автора',
  modals_complaint_blocking_2: 'и удалить пожелания',
  modals_complaint_attention_2: 'Если это сообщение нарушает правила игры, то вы можете отправить на него жалобу.',
  modals_complaint_blocking_3: 'Отправить жалобу',
  modals_onboarding_header_1: 'Открывай печеньки с предсказанием с друзьями через диалоги и чаты',
  modals_onboarding_header_2: 'Твои друзья могут делиться своими предсказаниями в чате',
  modals_onboarding_content_1: 'Делись полученными предсказаниями через историю и стену',
  modals_onboarding_content_2: 'А ты можешь отправлять свои в ответ',
  modals_onboarding_ok: 'Хорошо',
  modals_promo_code_bonus_1: 'Подарок за активацию:',
  modals_promo_code_bonus_ya_1: 'Получи в подарок за активацию промокода',
  modals_promo_code_bonus_ya_2: '(срок выдачи печенек составляет 4 суток)',
  modals_promo_code_great: 'Отлично!',
  modals_promo_code_footer_btn_1: 'Твои!',
  modals_promo_code_footer_btn_2: 'промокоды!',
  modals_tester_settings_tutor_mode: 'Режим тестового туториала в игре',
  modals_tester_settings_skip_ad: 'Пропускать рекламу за награду',
  profile_profile_page_vip_until: 'Активен до:',
  profile_profile_page_emo_status_1: 'Эмодзи',
  profile_profile_page_emo_status_2: 'статус',
  profile_profile_page_register: 'Уже с печенькой:',
  shop_pack_item_page_sale: 'Акция',
  shop_pack_item_page_status: 'Статус',
  shop_pack_item_page_until_vip: 'Активен до',
  shop_pack_item_page_unsubscribe: 'Отписаться',
  shop_pack_item_page_unsubscribed: 'Отписан',
  shop_pack_item_page_unavailable: 'Пока VIP-статус активен, этот пакет недоступен.',
  shop_pack_item_page_cost: 'Стоимость',
  shop_pack_item_page_privacy: 'Нажимая «Получить», Вы соглашаетесь с',
  shop_pack_item_page_agreement: 'Пользовательским соглашением',
  shop_pack_item_page_processing: 'Обработка покупки',
  shop_sales_container_bonus_success_1: 'Ура! Подарок получен.',
  shop_sales_container_bonus_success_2: 'Заходи в магазин, чтобы не пропустить новые подарки и акции.',
  shop_sales_container_bonus_take: 'Забрать',
  shop_sales_container_left: 'Осталось: ',
  shop_shop_page_title: 'Магазин',
  shop_shop_page_cookies: 'Печеньки',
  shop_shop_page_vip: 'VIP Статус',
  shop_shop_page_boosters: 'Бустер паки',
  shop_shop_page_hit: 'ХИТ',
  shop_shop_page_active: 'Активен',
  wishes_received_empty_new: 'Разломи печеньку, чтобы узнать свое первое пожелание!',
  wishes_received_empty: 'К сожалению, твой список пожеланий пока пуст :(',
  wishes_received_more: 'Еще',
  wishes_received_list_1: 'Пожелания',
  wishes_received_list_2: 'список',
  wishes_received_sender: '[кто прислал]',
  wishes_received_reveal: 'Раскрыть личность за',
  wishes_received_complaint: '[жалоба]',
  wishes_wishes_hint: 'Введи текст пожелания',
  wishes_wishes_todo_1: 'Напиши',
  wishes_wishes_todo_2: 'искреннее пожелание',
  wishes_wishes_result_1: 'Пожелание',
  wishes_wishes_result_2: 'для',
  wishes_wishes_result_3: 'Отправлено!',
  wishes_wishes_wish: 'Пожелать',
  wishes_wishes_get_predict: 'Получить предсказание',
  store_ad_limit: 'Лимит возможных просмотров достигнут!',
  store_ad_tests: 'Пропускаем просмотр рекламы! Настройка включена в тестах.',
  store_ad_task_reward_error: 'Не удалось найти задание для ускорения!',
  store_ad_speed_count: 'Использовано ускорений:',
  store_ad_survey_closed: 'Рекламный опрос не пройден, попробуйте еще раз, позже.',
  store_chapter_info_name: 'Приключения',
  store_chapter_wt: 'Получен несуществующий id задания!',
  store_chapter_er_pr: 'Что-то пошло не так при учете прогресса заданий!',
  store_chapter_task_ready: 'Задание выполнено!\nПоспеши забрать звезды опыта!',
  store_chapter_new_task: 'Новое задание уже доступно!',
  store_chapter_sw: 'Хм... Что-то пошло не так! ',
  store_chapter_sb: 'Что-то сломалось! ',
  store_shop_eb_header: 'АКЦИИ',
  store_shop_eb_text: 'Скоро появятся новые акции и подарки. Заходи в магазин чаще, чтобы ничего не пропустить!',
  store_shop_buy_pack: 'Получить пакет',
  store_shop_pack_contains: 'СОСТАВ ПАКЕТА',
  store_shop_vip_contains: 'ПРЕИМУЩЕСТВА',
  store_shop_vip_info_chapter: 'открывает награды приключений',
  store_shop_vip_info_free: '+1 бесплатная печенька в день',
  store_shop_vip_info_fc: '+1 печенька в день за соц.задания',
  store_shop_vip_info_main_ad: '+5 реклам с наградой в сутки',
  store_shop_vip_info_soft: 'x2 к доходу монет в игре',
  store_shop_vip_info_icon: 'иконка VIP в рейтинге',
  store_shop_vip_info_no_ad: 'отключение полноэкранной и баннерной рекламы',
  store_shop_receive_vip: 'Получить статус',
  store_shop_prolong_vip: 'Продлить статус',
  store_shop_prolonged_vip_1: 'Поздравляем!\nТвой VIP-статус успешно продлен на',
  store_shop_prolonged_vip_2: 'дней.\n\nПриятной игры.',
  store_shop_received_vip_1: 'Поздравляем!\nТы получил VIP-статус на',
  store_shop_received_vip_2: 'дней.\n\nПриятной игры.',
  store_shop_received_vip_3: 'Поздравляем! Ты получил:\n',
  store_shop_received_vip_4: 'дней.\n\nПриятной игры.',
  store_shop_bu_error: 'Этот подарок уже получен!',
  store_shop_b_error: 'Что-то пошло не так, не получилось забрать подарок.',
  store_shop_sbe: 'Что-то сломалось, попробуйте позже.',
  store_shop_unsbce: 'Отписаться не вышло, что-то пошло не так!',
  store_shop_unsbce_vk: 'Отписаться не вышло, ошибка VK',
  store_shop_pack_bonus: ' (подарок)',
  store_shop_pack_sale: ' (акция)',
  store_shop_pack_vip: 'VIP-статус на ',
  store_wishes_category_name: 'Пожелания',
  store_wishes_category_hint: 'Разломи печеньку и узнай что тебе желают другие люди',
  store_wishes_e_empty: 'Хм, новых пожеланий больше нет!',
  store_wishes_e_bad: 'Пожалуйста, используй цензурный текст для пожелания!',
  store_wishes_e_no_user_1: 'К сожалению,',
  store_wishes_e_no_user_2: 'давно не заходил в печеньку и его нет в базе данных!',
  store_wishes_e_already_sent: 'уже получил сегодня от тебя пожелание!',
  store_wishes_e_black: 'не принимает от тебя пожеланий!',
  store_wishes_e_no_hard: 'Не хватает печенек!',
  store_wishes_e_def: 'Ошибка! ',
  store_wishes_butt_e: 'Кнопка не добавлена, что-то пошло не так',
  store_wishes_butt_suc: 'Теперь ты можешь получать пожелания!',
  store_wishes_butt_del: 'Кнопка для отправки пожеланий удалена из профиля ;(',
  store_wishes_butt_ue: 'Кнопка не добавлена, произошла какая-то ошибка!',
  store_wishes_e_sender_uid: 'Нельзя отправить пожелание самому себе!',
  store_wishes_ue: 'Неизвестная ошибка: ',
  store_wishes_complaint: 'Ваша жалоба принята, автор заблокирован все его пожелания, удалены.',
  store_game_main_es: 'Сбой сохранения игры!',
  store_game_main_esw: 'Что-то пошло не так! ',
  store_game_main_esb: 'Что-то сломалось! ',
  store_game_plates_su: 'Тарелочка успешно улучшена до х',
  store_main_no_prize: 'У вас закончились бесплатные предсказания.',
  store_main_esw: 'Хм, что-то пошло не так, попробуйте позже или напишите нам.',
  store_user_friends_evk: 'Ошибка получения списка друзей!',
  store_user_status_not_allowed: 'Нет доступа к статусу :(',
  store_user_status_eu: 'Произошла какая-то ошибка!',
  store_user_status_e_empty: 'Нет доступных статусов!',
  store_user_status_e_not_set: 'Установить статус не получилось, кажется что-то пошло не так.',
  store_user_status_e_not_select: 'Выбрать статус не получилось, что-то пошло не так.',
  store_user_status_e_not_remove: 'Убрать статус не получилось, что-то пошло не так.',
  store_user_recommend_app: 'Рекомендуй приложение',
  store_user_reward_received: 'Ура! Награда получена:',
  store_user_esw_recommend: 'Что-то пошло не так, обратитесь в поддержку!',
  store_user_esb_recommend: 'Что-то сломалось, попробуйте позже.',
  store_app_invite_text: 'Приглашаю тебя поломать печеньки с предсказаниями.',
  store_app_invite_button: 'Получить предсказания',
  store_app_invite_title: 'Зови друзей ломать печеньки!',
  store_share_error: 'Ой! Что-то пошло не так!',
  share_story_predict_title_1: 'Печенька',
  share_story_predict_title_2: 'предсказала мне:',
  share_story_special_title_1: 'Получай',
  share_story_special_title_2: 'предсказание дня',
  share_story_special_title_3: 'от печеньки',
  share_story_biggest_title_1: 'У меня новый',
  share_story_biggest_title_2: 'уровень',
  share_story_biggest_title_3: 'печеньки',
  share_story_biggest_title_4: 'Клевая игра -',
  share_story_biggest_title_5: 'заходите тоже!',
  share_story_special_button: 'Получить свое предсказание',
  share_story_predict_button: 'Получить свое предсказание',
  share_story_biggest_button: 'Зайти',
  share_wall_predict_title_1: 'Печенька',
  share_wall_predict_title_2: 'предсказала мне:',
  share_wall_special_title_1: 'Получай',
  share_wall_special_title_2: 'предсказания',
  share_wall_special_title_3: 'от печеньки',
  share_wall_biggest_title_1: 'У меня новый',
  share_wall_biggest_title_2: 'уровень',
  share_wall_biggest_title_3: 'печеньки!',
  share_wall_biggest_title_4: 'Клевая игра -',
  share_wall_biggest_title_5: 'заходите тоже!',
  share_wall_special_footer_1: 'Что ждет сегодня?',
  share_wall_special_footer_2: 'Скорее открывай печеньку!',
  share_wall_predict_footer_1: 'Что ждет сегодня?',
  share_wall_predict_footer_2: 'Скорее открывай печеньку!',
  share_wall_biggest_footer_1: 'Играй в игру, соединяй печеньки',
  share_wall_biggest_footer_2: 'Получай предсказания',
  share_wall_biggest_footer_3: 'от Печеньки!',
  share_wall_achievements_footer_1: 'Играй в игру, выполняй достижения',
  share_wall_achievements_footer_2: 'Получай предсказания',
  share_wall_achievements_footer_3: 'от Печеньки!',
  special_predict: 'Ты будешь счастлив',
  achievement_name_1: 'Фанат',
  achievement_description_1: 'Заходи в приложение',
  achievement_hint_1: 'Чтобы увеличить прогресс достижения - просто заходи в приложение, но не слишком часто.',
  achievement_name_2: 'Пекарь',
  achievement_description_2: 'Забирай оффлайн доход',
  achievement_hint_2: 'Заходи в игру и забирай оффлайн доход, который накопился за время твоего отсутствия.',
  achievement_name_3: 'Кондитер',
  achievement_description_3: 'Покупай печеньки на стол',
  achievement_hint_3: 'Переходи в игру и покупай печеньки на свой игровой стол, каждая печенька идет в зачет.',
  achievement_name_4: 'Кулинар',
  achievement_description_4: 'Соединяй печеньки',
  achievement_hint_4: 'Соединяй одинаковые печеньки на своем игровом столе, чтобы увеличить прогресс.',
  achievement_name_5: 'Неудержимый',
  achievement_description_5: 'Активируй ускорители',
  achievement_hint_5: 'Активируй ускоритель дохода монет, он находится во вкладке «Улучшения» в игре.',
  achievement_name_6: 'Тор',
  achievement_description_6: 'Запускай печенькопады',
  achievement_hint_6: 'Запускай печенькопады в игре. Кнопка находится во вкладке «Улучшения».',
  achievement_name_7: 'Гончар',
  achievement_description_7: 'Улучшай тарелочки',
  achievement_hint_7: 'Зайди в раздел улучшения тарелочек (вкладка «Улучшения») и повышай уровни тарелочек.',
  achievement_name_8: 'Оракул',
  achievement_description_8: 'Открывай предсказания',
  achievement_hint_8: 'Разламывай печеньки в любой категории - получай свои предсказания для увеличения прогресса достижения.',
  achievement_name_9: 'Репортёр',
  achievement_description_9: 'Делай репосты',
  achievement_hint_9: 'Поделись на своей странице предсказанием, новым уровнем печеньки или полученным достижением. Не чаще одного раза за несколько часов.',
  achievement_name_10: 'Санта-Клаус',
  achievement_description_10: 'Дари подарки',
  achievement_hint_10: 'Отправляй подарки кому-либо используя кнопки: в чужом профиле - «Подарить» или в своем профиле - «Подарить другу».',
  achievement_name_11: 'Сектор Приз',
  achievement_description_11: 'Крути Колесо Фортуны',
  achievement_hint_11: 'Открой «Колесо Фортуны» и просто раскрути его. Учитывается каждое кручение.',
  achievement_name_12: 'Везунчик',
  achievement_description_12: 'Выиграй «Приз» с печеньками',
  achievement_hint_12: 'Крути «Колесо Фортуны» - если выпал Малый приз, Большой приз или Джекпот, прогресс будет увеличен.',
  achievement_name_13: 'Большой куш',
  achievement_description_13: 'Выиграй Джекпот',
  achievement_hint_13: 'Вращай «Колесо Фортуны», поймай удачу за хвост выиграв Джекпот.',
  achievement_name_14: 'Каменщик',
  achievement_description_14: 'Создавай кирпичи',
  achievement_hint_14: 'Создавай кирпичи на «Кирпичном заводе» своего города. Будет учтен каждый кирпич.',
  achievement_name_15: 'Капиталист',
  achievement_description_15: 'Выигрывай печеньки',
  achievement_hint_15: 'Играй в «Колесо Фортуны», выиграй печеньки и прогресс будет увеличен на количество выигранных печенек.',
  achievement_name_16: 'Инкассатор',
  achievement_description_16: 'Собирай мешки с монетами',
  achievement_hint_16: 'Прояви смекалку и поймай падающий на игровое поле мешок, забери его монеты, и прогресс будет увеличен.',
  achievement_name_17: 'Авантюрист',
  achievement_description_17: 'Получай 45 ур. приключений',
  achievement_hint_17: 'Участвуй в «Приключениях», получай опыт, повышай уровень, чтобы выполнить это достижение.',
  achievement_name_18: 'Привереда',
  achievement_description_18: 'Заменяй задания',
  achievement_hint_18: 'Открой «Приключения» и замени любое неугодное тебе задание.',
  achievement_name_19: 'Звездочет',
  achievement_description_19: 'Забирай звезды приключений',
  achievement_hint_19: 'Выполняй любые задания «Приключений» и нажимай кнопку «Забрать», чтобы получить звезды опыта.',
  achievement_name_20: 'Медалист',
  achievement_description_20: 'Стань призером рейтинга',
  achievement_hint_20: 'Открывай предсказания и займи любое призовое место в рейтинге «Кто съел больше?», прогресс увеличится после "награждения".',
  achievements_congratulations_bronze: 'Бронзовое',
  achievements_congratulations_silver: 'Серебряное',
  achievements_congratulations_gold: 'Золотое',
  achievements_congratulations_brilliant: 'Бриллиантовое',
  achievements_page_title_other: 'Достижения',
  achievements_page_title_my: 'Мои достижения',
  achievements_page_all_progress: 'Общий прогресс',
  achievements_my_have: 'Имеют',
  achievements_my_take: 'Забрать',
  achievements_my_reward: 'Награда',
  achievements_my_from: 'из',
  achievements_my_gallery: 'Витрина',
  achievements_my_slot: 'В слоте',
  achievements_gallery_heading: 'Выбери место на витрине',
  achievements_gallery_pick: 'Выбрать',
  achievements_gallery_switch: 'Заменить',
  achievements_gallery_delete: 'Убрать',
  achievements_gallery_show: 'показать все',
  achievements_gallery_empty: 'Свободно',
  achievements_congratulations_great: 'Замечательно!',
  achievements_congratulations_achiev: 'достижение',
  achievements_congratulations_cool: 'Отлично',
  achievements_congratulations_times: 'раз',
  store_user_achievements_error: 'Достижения. Что-то пошло не так! ',
  achievements_story_have: 'У МЕНЯ',
  achievements_story_achievement: 'ДОСТИЖЕНИЕ!',
  achievements_story_want: 'Хочешь свое?',
  achievements_story_hurryup: 'Поспеши в печеньку!',
  achievements_story_button: 'За достижениями',
};

export {russian};