const spanish = {
  app_name: "Galeta",
  anonymous: "Anónimo",
  app_email_1: "¿Has anotado tus datos?",
  app_email_2: "Introduce tu correo electrónico y haz clic en enviar.",
  app_email_3: "¡Obtén tu nombre de usuario y contraseña para siempre poder volver al juego!",
  app_email_4: "Enviar",
  app_email_5: "Tu Email",
  app_settings_title: "Configuraciones",
  app_settings_music: "Música",
  app_settings_music_bg: "Reproducir en segundo plano",
  app_settings_sounds: "Sonidos",
  app_settings_rain: "Velocidad de lluvia de galletas",
  app_welcome_1: "¡Hola!",
  app_welcome_2: "registro completado",
  app_welcome_3: "Usuario:",
  app_welcome_4: "Contraseña:",
  app_welcome_5: "Almacenamos tus datos en este dispositivo, mientras existan no perderás tu progreso.",
  app_welcome_6: "¡Vale, jugar!",
  app_welcome_7: "¿Ya tienes usuario?",
  app_welcome_8: "¡Introduce tus datos para continuar jugando!",
  app_welcome_9: "¡Ingresar datos!",
  app_welcome_10: "Inicio de sesión",
  app_welcome_11: "Usuario",
  app_welcome_12: "Contraseña",
  app_welcome_13: "Ingresar",
  city_buildings_bank_1: "Banco de la ciudad",
  city_buildings_bank_2: "Nivel:",
  city_buildings_bank_3: "Determina la cantidad de billetes de premio en la clasificación de los habitantes de la ciudad que han obtenido la cantidad requerida de puntos.",
  city_buildings_bank_4: "Características",
  city_buildings_bank_5: "Requisito",
  city_buildings_bank_6: "Ahora:",
  city_buildings_bank_7: "puntos",
  city_buildings_bank_8: "Siguiente:",
  city_buildings_brickyard_1: "Fábrica de ladrillos",
  city_buildings_brickyard_2: "Permite producir ladrillos necesarios para la construcción y mejora de edificios en la ciudad",
  city_buildings_brickyard_3: "Producción",
  city_buildings_brickyard_4: "Seleccione cantidad:",
  city_buildings_brickyard_5: "TOTAL:",
  city_buildings_brickyard_6: "Fabricar",
  city_buildings_brickyard_7: "Límite de producción",
  city_buildings_brickyard_8: "pcs.",
  city_buildings_brickyard_9: "Condiciones de producción",
  city_buildings_brickyard_10: "Costo de ladrillo",
  city_buildings_brickyard_11: "Restablecer límite",
  city_buildings_brickyard_12: "una vez al día",
  city_buildings_brickyard_13: "Producción detenida",
  city_buildings_brickyard_14: "límite diario alcanzado",
  city_buildings_brickyard_15: "Mejora",
  city_buildings_buildings_1: "Añadido al edificio ",
  city_buildings_cafe_1: "Café",
  city_buildings_cafe_2: "Aumenta la cantidad de galletas que caen en la lluvia de galletas",
  city_buildings_cafe_3: "Aumento ahora:",
  city_buildings_cafe_4: "Después de la mejora:",
  city_buildings_cafe_5: "pcs.",
  city_buildings_candy_factory_1: "Fábrica de dulces",
  city_buildings_candy_factory_2: "Permite aumentar el tiempo de funcionamiento del acelerador cuando se activa",
  city_buildings_candy_factory_3: "Aumento de tiempo:",
  city_buildings_candy_factory_4: "min.",
  city_buildings_city_hall_1: "Ayuntamiento",
  city_buildings_city_hall_2: "Responde por el número máximo de residentes (participantes) en la ciudad",
  city_buildings_city_hall_3: "Límite ahora:",
  city_buildings_city_hall_4: "residentes",
  city_buildings_city_hall_5: "Después de la mejora:",  
  city_buildings_mill_1: "Molino",
  city_buildings_mill_2: "Aumenta la probabilidad de caída de una galleta de nivel superior durante la lluvia de galletas",
  city_buildings_mill_3: "Probabilidad aumentada:",
  city_buildings_mill_4: "en",
  city_buildings_success_1: "¡Construcción completada!",
  city_buildings_success_2: "Nivel del edificio aumentado a",
  city_buildings_success_3: "-vo",
  city_buildings_success_4: "¡Eficiencia aumentada!",
  city_buildings_success_5: "¡Genial!",
  city_buildings_success_6: "Límite de producción",
  city_buildings_success_7: "Límite de residentes en la ciudad:",
  city_buildings_success_8: "Recompensas y requisitos",
  city_buildings_success_9: "Requisito",
  city_buildings_success_10: "puntos",
  city_buildings_success_11: "Galletas en la lluvia de galletas:",
  city_buildings_success_12: "Probabilidad de caída de galletas de nivel superior:",
  city_buildings_success_13: "Tiempo de funcionamiento del acelerador:",
  city_buildings_success_14: "¡Edificio no encontrado!",
  city_buildings_upgrade_1: "Mejora",
  city_buildings_upgrade_2: "Nivel máximo alcanzado",
  city_buildings_upgrade_3: "Se requieren galletas",
  city_buildings_upgrade_4: "Se requieren ladrillos",
  city_buildings_upgrade_5: "Comprar",
  city_buildings_upgrade_6: "Producir",
  city_buildings_upgrade_7: "Añadir",
  city_buildings_upgrade_8: "¡No hay suficientes galletas!",
  city_buildings_upgrade_9: "¡No hay suficientes ladrillos!",
  city_buildings_upgrade_10: "Esperando ladrillos",
  city_buildings_upgrade_11: "Esperando galletas",
  city_buildings_upgrade_12: "Progreso:",
  city_chat_1: "Tu mensaje...",
  city_chat_2: "¡Nuevo mensaje en el chat de la ciudad!",
  city_chat_3: "¡Varios mensajes nuevos en el chat de la ciudad!",
  city_city_panel_1: "Aún no te has unido a una ciudad",
  city_city_panel_2: "Tu balance",
  city_city_panel_3: "ladrillos",
  city_city_panel_4: "galletas",
  city_city_panel_5: "en línea:",  
  city_control_changes_1: "Avatar: elige una imagen para tu ciudad. Algunas de ellas podrás desbloquearlas más adelante.",
  city_control_changes_2: "Ver y seleccionar",
  city_control_changes_3: "Nombre: un nombre adecuado, atractivo y memorable para tu ciudad",
  city_control_changes_4: "Descripción: una descripción adecuada y breve de tu ciudad, opcional.",
  city_control_changes_5: "Accesibilidad: elige el tipo de accesibilidad social de tu ciudad.",
  city_control_changes_6: "Pública",
  city_control_changes_7: "- visible para todos en la lista de ciudades aleatorias;",
  city_control_changes_8: "- cualquier jugador puede unirse a tu ciudad;",
  city_control_changes_9: "Privada",
  city_control_changes_10: "- no visible en la lista de ciudades aleatorias;",
  city_control_changes_11: "- el jugador se une a la ciudad solo después de tu aprobación;",
  city_control_changes_12: "galletas",
  city_control_changes_13: "Oferta, quedan:",
  city_control_control_1: "¡Después de salir no podrás unirte a otra ciudad durante un día!",
  city_control_control_2: "¡Eres el alcalde de esta ciudad y no puedes dejarla mientras haya otros residentes!",
  city_control_control_3: "Dejar la ciudad",
  city_control_control_4: "Aquí puedes dejar la ciudad en la que te encuentras como residente.\r\nAl dejar la ciudad, perderás todas sus ventajas.",
  city_control_control_5: "Salir de esta ciudad",
  city_control_logo_1: "Configuración",
  city_control_logo_2: "del avatar",
  city_control_logo_3: "Aleatorio",
  city_control_logo_4: "Guardar",
  city_control_members_1: "Residentes de la ciudad",
  city_control_members_2: "Por semana",
  city_control_members_3: "De todo el tiempo",
  city_control_members_4: "Abrir perfil",
  city_control_members_5: "Expulsar de la ciudad",
  city_control_notes_1: "Escribe aquí todo lo que quieras, como un saludo, noticias, reglas, instrucciones, deseos. Este texto será visible para todos los residentes de tu ciudad.",
  city_control_notes_2: "Código de la ciudad",
  city_control_notes_3: "Escribir",
  city_control_notes_4: "Cancelar",
  city_control_notes_5: "Guardar",
  city_control_requests_1: "No hay",
  city_control_requests_2: "Solicitudes de ingreso",
  city_control_requests_3: "solicitud aprobada",
  city_control_summary_1: "Resumen de la ciudad",
  city_control_summary_2: "Información",
  city_control_summary_3: "Alcalde:",
  city_control_summary_4: "Residentes en la ciudad:",
  city_control_summary_5: "Fecha de fundación:",
  city_control_summary_6: "de",
  city_control_summary_7: "Actividad semanal",
  city_control_summary_8: "Puntos obtenidos:",
  city_control_summary_9: "Conexiones realizadas:",
  city_control_summary_10: "Edificios",
  city_control_summary_11: "Nivel:",
  city_control_summary_12: "Ladrillos:",
  city_control_summary_13: "Galletas:",
  city_control_summary_14: "d.",
  city_control_summary_15: "máx.",  
  city_header_1: "Charla",
  city_help_page_1: "1. ¿Qué es una ciudad?",
  city_help_page_2: "Es una mecánica social que permite unirse a otros jugadores y obtener buenos beneficios.",
  city_help_page_3: "2. ¿Qué se puede hacer en la ciudad?",
  city_help_page_4: "Chatear, mejorar los edificios de la ciudad, competir con otros residentes y ciudades por recompensas. La lista seguirá creciendo.",
  city_help_page_5: "3. ¿Por qué mejorar los edificios?",
  city_help_page_6: "Cada edificio otorga un beneficio único.",
  city_help_page_7: "Por ejemplo, el café aumenta la cantidad de galletas que caen en la lluvia de galletas, y la fábrica de dulces aumenta la duración del acelerador de ingresos.",
  city_help_page_8: "4. ¿Cómo mejorar los edificios?",
  city_help_page_9: "Los edificios se mejoran con galletas y ladrillos.",
  city_help_page_10: "Los ladrillos son la moneda de la ciudad, comprados con plata en la fábrica de ladrillos.",
  city_help_page_11: "El costo de los ladrillos es el mismo para todos los jugadores y se mide en horas de ingresos.",
  city_help_page_12: "5. ¿Quién es el alcalde?",
  city_help_page_13: "El alcalde es el creador de la ciudad.",
  city_help_page_14: "Puede cambiar el avatar, nombre, descripción y privacidad de la ciudad.",
  city_help_page_15: "Tiene el derecho de aceptar y expulsar a los residentes.",
  city_help_page_16: "Puede ver la contribución de cada residente.",
  city_help_page_17: "El rol de alcalde no se puede transferir a otro residente.",
  city_help_page_18: "6. ¿Para qué sirve el ranking de residentes?",
  city_help_page_19: "Los residentes más activos obtienen boletos para la Rueda de la Fortuna al final de cada semana.",
  city_help_page_20: "Los premios y requisitos dependen del nivel de mejora del banco.",
  city_help_page_21: "Para obtener billetes para la Rueda de la Fortuna, debes acumular al menos 100 puntos de contribución.",
  city_help_page_22: "Los 3 primeros residentes obtienen premios aumentados.",
  city_help_page_23: "7. ¿Cómo ganar puntos para el ranking de residentes?",
  city_help_page_24: "Los puntos se suman de la cantidad de ladrillos y galletas invertidos en la mejora de edificios.",
  city_help_page_25: "1 ladrillo = 1 punto.",
  city_help_page_26: "1 galleta = 10 puntos.",
  city_help_page_27: "8. ¿Para qué sirve el ranking de ciudades?",
  city_help_page_28: "El ranking se basa en la suma de conexiones de galletas de todos los residentes de la ciudad.",
  city_help_page_29: "Permite aumentar la popularidad de tu ciudad y atraer a los jugadores más activos.",
  city_help_page_30: "Ayuda",
  city_help_page_31: "Preguntas frecuentes",
  city_leaders_1: "Semanal",
  city_leaders_2: "Mensual",
  city_leaders_3: "Total",
  city_leaders_4: "Ranking de ciudades",
  city_members_1: "Ranking de residentes",
  city_members_2: "Reglas del ranking",
  city_members_rules_1: "Reglas",
  city_members_rules_2: "El ranking se basa en puntos que los residentes pueden obtener\r\npor jugar activamente y apoyar su ciudad.",
  city_members_rules_3: "Por qué se pueden obtener puntos:",
  city_members_rules_4: "- invertir ladrillos en un edificio",
  city_members_rules_5: "1 ladrillo =",
  city_members_rules_6: "punto",
  city_members_rules_7: "- invertir galletas en un edificio",
  city_members_rules_8: "1 galleta =",
  city_members_rules_9: "puntos",
  city_members_rules_10: "En el ranking semanal, los residentes tienen la oportunidad de obtener valiosos premios.",
  city_members_rules_11: "Para aumentar la cantidad de premios, mejora el Banco de la ciudad.",
  city_no_items_1: "Ocurrió un error, inténtalo más tarde",
  city_no_items_2: "La lista está vacía :(",
  city_overview_page_1: "Privada",
  city_overview_page_2: "Pública",
  city_overview_page_3: "Descripción",
  city_overview_page_4: "Unirse",
  city_overview_page_5: "Enviar solicitud",
  city_overview_page_6: "Información de la ciudad",
  city_overview_page_7: "Información",
  city_overview_page_8: "Tipo:",
  city_overview_page_9: "Residentes:",
  city_overview_page_10: "Fundada:",
  city_overview_page_11: "d.",
  city_overview_page_12: "Edificios",
  city_overview_page_13: "Ayuntamiento:",
  city_overview_page_14: "nivel",
  city_overview_page_15: "Banco de la ciudad:",
  city_overview_page_16: "Café:",
  city_overview_page_17: "Fábrica de dulces:",
  city_overview_page_18: "Molino:",
  city_overview_page_19: "de",
  city_overview_page_20: "Fábrica de ladrillos:",  
  city_search_buttons_1: "Aceptar",
  city_search_buttons_2: "Unirse",
  city_search_buttons_3: "Enviar solicitud",
  city_search_buttons_4: "Retirar",
  city_search_buttons_5: "Te invitan",
  city_search_random_1: "Ciudades aleatorias",
  city_search_random_2: "Tus solicitudes",
  city_search_search_1: "Crear ciudad",
  city_search_search_panel_1: "No se encontró nada",
  city_search_search_panel_2: "Escribe algo y haz clic en buscar",
  city_search_search_panel_3: "Buscar ciudades",
  city_search_search_panel_4: "Buscar",
  city_search_search_panel_5: "Nombre...",
  city_tutorial_free_panel_1: "Probablemente no hay ciudades disponibles por ahora.",
  city_tutorial_free_panel_2: "¡Crea tu propia ciudad gratis!",
  city_tutorial_free_panel_3: "Únete a una ciudad que te guste o crea la tuya propia con galletas!",
  city_tutorial_free_panel_4: "Ciudades disponibles",
  city_tutorial_free_panel_5: "Unirse",
  city_tutorial_hints_1: "Entendido",
  city_tutorial_tutorial_1: "Crear tu ciudad",
  city_welcome_page_1: "Bienvenid@",
  city_welcome_page_2: "a tu ciudad personal!",
  city_welcome_page_3: "Ahora eres el alcalde, el dueño de la ciudad",
  city_welcome_page_4: "Invita a otros jugadores, chatea con los residentes, mejora los edificios y obtén bonificaciones en el juego.\r\n¡Consigue las mejores posiciones en el ranking de otras ciudades!",
  city_welcome_page_5: "Es el momento de un buen gobernante. ¡Haz que tu ciudad sea la mejor!",
  city_welcome_page_6: "¡Adelante!",
  city_welcome_page_7: "a la ciudad",
  city_welcome_page_8: "Mejora los edificios y obtén bonificaciones en el juego,\r\nchatea con otros residentes y\r\ncompite con otras ciudades.",
  city_welcome_page_9: "Sé un residente ejemplar :)",
  cookies_shop_item_1: "Crear",
  cookies_shop_item_2: "nivel",
  cookies_shop_item_buy: "Comprar por:",
  cookies_shop_item_sec: "/seg",
  cookies_shop_title: "Tienda",
  crush_btn: "Romper",
  extra_menu_battle: "Batalla",
  extra_menu_my_city: "Mi ciudad",
  free_cookies_1: "¡Completa tareas y recoge tu recompensa aquí todos los días!",
  free_cookies_2: "Comparte y obtén recompensas por cada nuevo jugador que se una a través de tus enlaces",
  free_cookies_3: "solo por aquellos que nunca hayan abierto la aplicación antes y rompan al menos tres galletas",
  free_cookies_4: "¡Invita a tus amigos y recoge las galletas aquí cuando empiecen a jugar!",
  free_cookies_5: "¡por cada uno!",
  free_cookies_6: "solo por aquellos que nunca hayan abierto la aplicación antes y rompan al menos tres galletas",
  free_cookies_get: "Recoger",
  free_cookies_gifts: "Regalos",
  free_cookies_in_day: "por día",
  free_cookies_invite: "Invitar a un amigo",
  free_cookies_perform: "Completar",
  free_cookies_promo: "Tus códigos promocionales",
  free_cookies_promo_codes_active: "Activo hasta ",
  free_cookies_promo_codes_copy: "Copiar",
  free_cookies_promo_codes_send: "Enviar por mensaje privado",
  free_cookies_promo_codes_title: "Tus códigos promocionales",
  free_cookies_received: "Recibido",
  free_cookies_story: "Compartir en la historia",
  free_cookies_wall: "Compartir en el muro",
  free_cookies_share: "Compartir el juego",  
  game_Free: "Gratis",
  game_rain_enabled: "¡Activado!",
  game_for_prize: "¡Premio!",
  game_rain: "Lluvia de galletas",
  game_rocket: "Acelerador",
  game_sale: "Oferta",
  game_shop: "Mercado",
  game_battle_leaders_1: "Mejores del día",
  game_battle_leaders_2: "Premio",
  game_battle_lobby_close: "cerrar",
  game_battle_lobby_connection: "Conectando...",
  game_battle_lobby_duel: "Competencia",
  game_battle_lobby_go: "¡Adelante!",
  game_battle_lobby_training: "Combate de entrenamiento",
  game_battle_merge_1: "Conecta las galletas lo más rápido posible, supera al oponente en número de conexiones.",
  game_battle_merge_2: "¡Gana su apuesta!",
  game_battle_merge_3: "Elige una apuesta para jugar:",
  game_battle_merge_cookie: "Galleta",
  game_battle_result_1: "¡Otra vez!",
  game_battle_result_close: "cerrar",
  game_battle_result_cookie: "galleta",
  game_battle_result_draw_mess: "Has recuperado:",
  game_battle_result_draw_title: "¡Empate!",
  game_battle_result_loss_mess: "Has perdido:",
  game_battle_result_loss_title: "¡Derrota!",
  game_battle_result_win_mess: "Has ganado:",
  game_battle_result_win_title: "¡Victoria!",
  game_battle_select_rival_1: "Buscando oponente",
  game_battle_select_rival_2: "buscando en los servidores",
  game_battle_select_rival_3: "cancelar",
  game_battle_tutorial_next: "Siguiente",
  game_battle_tutorial_res_1: "¡Hurra, has ganado! Es el momento de jugar contra un verdadero oponente.",
  game_battle_tutorial_res_2: "¡Victoria!",
  game_battle_tutorial_res_3: "¡No te preocupes! Intenta el tutorial otra vez.",
  game_battle_tutorial_res_4: "¡Derrota!",
  game_battle_tutorial_res_5: "¡Empate!",
  game_battle_tutorial_res_6: "cerrar",
  game_battle_tutorial_res_7: "¡Entrenamiento completado!",
  game_battle_tutorial_res_8: "Atrás",
  game_cookie_rain_layer_1: "Conecta",
  game_cookie_rain_layer_2: "las galletas a tiempo!",
  game_cookie_rain_layer_3: "Libera espacio",
  game_cookie_rain_layer_4: "para la lluvia de galletas!",
  game_cost: "Costo",
  game_counter_soft_1: "Del acelerador",
  game_counter_soft_sec: "/s",
  game_leagues: "Ligas",
  game_leagues_tutorial_1: '¡Felicidades\nHas desbloqueado las ligas!',
  game_leagues_tutorial_2: 'Es una competencia con otros jugadores por',
  game_leagues_tutorial_2_1: 'galletas de premio',
  game_leagues_tutorial_3: 'Bien',
  game_leagues_tutorial_4: 'Conectando galletas obtienes',
  game_leagues_tutorial_4_1: 'puntos de conexión',
  game_leagues_tutorial_5: 'Otros jugadores también están acumulando sus puntos de conexión.',
  game_leagues_tutorial_6: 'Entendido',
  game_leagues_tutorial_7: 'La liga dura una semana, este temporizador muestra',
  game_leagues_tutorial_7_1: 'el tiempo restante',
  game_leagues_tutorial_8: 'Intenta entrar en',
  game_leagues_tutorial_8_1: 'los primeros diez',
  game_leagues_tutorial_8_2: 'jugadores de tu liga.',
  game_leagues_tutorial_9: 'Gana',
  game_leagues_tutorial_9_1: 'galletas',
  game_leagues_tutorial_9_2: 'y avanza a la siguiente, más',
  game_leagues_tutorial_9_3: 'increíble liga',
  game_leagues_tutorial_10: '¡Conectar!',  
  game_main_am_unlock_rain: '¡Necesitas una galleta de nivel 5!',
  game_main_am_unlock_rocket: '¡Requiere una galleta de nivel 6!',
  game_main_am_unlock_income: '¡Se desbloqueará en el nivel 7!',
  game_main_am_unlock_plates: '¡Necesitas una galleta de nivel 8!',
  game_main_biggest_1: "¡Felicidades!",
  game_main_biggest_2: "¡Nuevo nivel de galleta!",
  game_main_biggest_3: "¡Excelente!",
  game_main_left_menu_1: "Ciudad",
  game_main_left_menu_2: "Batalla",
  game_main_left_menu_3: "Ligas",
  game_main_left_menu_4: "Mercado",
  game_main_left_menu_leagues: 'Para desbloquear las ligas,\nobtén una galleta de nivel 7!',
  game_main_left_menu_city: 'Las ciudades estarán disponibles\ndespués del nivel 10 de galleta!',
  game_main_rain_3: "Haz llover galletas sobre tu mesa de juego",
  game_main_rain_4: "Lanzar",
  game_main_rocket_1: "Activa el turbo ingreso por varias horas",
  game_main_rocket_2: "Activar",
  game_main_tab_1: "Mejoras",
  game_main_tab_2: "Compra rápida",
  game_main_tutor_1: "Conecta galletas idénticas",
  game_main_tutor_2: "Compra varias galletas para la mesa",
  game_main_tutor_3: "Obtén una galleta de nivel 4",
  game_main_tutor_4: "¡Hola!",
  game_main_tutor_5: "El objetivo del juego es",
  game_main_tutor_6: "conectar galletas",
  game_main_tutor_7: ", para desbloquear nuevas y geniales galletas!",
  game_main_tutor_8: "Vamos a empezar a conectar y ver qué sucede.",
  game_main_tutor_9: "¡Vamos!",
  game_main_tutor_10: "¡Comprar!",
  game_main_tutor_11: "¡Genial! Pero ya no hay más galletas para conectar.",
  game_main_tutor_12: "Necesitas",
  game_main_tutor_13: "comprar más",
  game_main_tutor_14: "galletas para la mesa, para seguir jugando!",
  game_main_tutor_15: "Vamos a comprarlas a través del menú de compra rápida.",
  game_main_tutor_16: "¡Adelante!",
  game_main_tutor_17: "¡Monedas!",
  game_main_tutor_18: "Cada galleta en la mesa",
  game_main_tutor_19: "gana",
  game_main_tutor_20: "monedas.",
  game_main_tutor_21: "Cuanto mayor sea el nivel de la galleta, más monedas",
  game_main_tutor_22: "ganará por segundo",
  game_main_tutor_23: "Conecta las galletas compradas para obtener un nuevo nivel!",
  game_main_tutor_24: "¡Entendido!",
  game_main_tutor_25: "¡Excelente!",
  game_main_tutor_26: "Sigue jugando, compra y conecta galletas, desbloquea nuevos niveles.",
  game_main_tutor_27: "Completa misiones y gana",
  game_main_tutor_28: "recompensas",
  game_main_tutor_29: ", utiliza varias mejoras!",
  game_main_tutor_30: "Desbloquea",
  game_main_tutor_31: "ligas",
  game_main_tutor_32: " y compite por",
  game_main_tutor_33: "premios",
  game_main_tutor_34: "con otros jugadores!",
  game_main_tutor_35: "¡Jugar!",
  game_income: 'Ingreso offline',
  game_income_max: "Máximo alcanzado",
  game_income_description: "¡Gana aún más plata cuando no estés en el juego!",
  game_income_level: "Nivel",
  game_income_upgrade: "Mejorar",
  game_income_prize: "¡Premio!",
  game_leagues_1: " ganadores obtienen galletas",
  game_leagues_2: " ganadores avanzan a una nueva liga y obtienen galletas",
  game_leagues_3: "Zona de descenso de liga",
  game_plates_footer_1: "Mejora los platos y las galletas que hay en ellos, ¡generarán más ingresos X!",
  game_plates_footer_2: "¡Coloca las mejores galletas en los mejores platos!",
  game_plates_footer_done: "Hecho",
  game_plates_plates_sale: "La oferta termina en:",  
  invite_invite_1: "Parece que todos tus amigos ya están jugando a la galleta",
  invite_invite_2: "Ocurrió algún error, intenta de nuevo más tarde",
  invite_invite_3: "Invita a tus amigos y recibe una recompensa cuando empiecen a jugar y rompan al menos tres galletas",
  invite_invite_title: "Correo",
  invite_list_item_invite: "Invitar",
  invite_list_item_invited: "Invitado",
  league_bronze: "Liga de Bronce",
  league_gold: "Liga de Oro",
  league_platinum: "Liga de Platino",
  league_ruby: "Liga de Rubí",
  league_silver: "Liga de Plata",
  loading_1: "obteniendo tus datos",
  main_ad_video_rb_view: "¡Ver!",
  main_ad_video_rb_limit: "Inactivo\nhasta mañana",
  main_ad_video_rb_popup: "La recompensa por ver el anuncio estará disponible más tarde.",
  main_app_banner_1: "¡Hornea aún más galletas!",
  main_app_banner_2: "tienes códigos promocionales",
  main_app_banner_3: "¡Úsalos antes de que caduquen!",
  main_crush_button_text_1: "Romper otra",
  main_crush_button_text_2: "Romper por",
  main_crush_tutorial_1: "¡Felicidades!",
  main_crush_tutorial_2: "Este es tu pronóstico.",
  main_crush_tutorial_3: "Entendido",
  main_crush_tutorial_4: "Vuelve mañana",
  main_crush_tutorial_5: "y recibe una galleta gratis",
  main_crush_tutorial_6: "¡una vez al día!",
  main_crush_tutorial_7: "¿Quieres recibir galletas",
  main_crush_tutorial_8: "gratis ahora?",
  main_crush_tutorial_9: "¡Entra aquí!",
  main_crush_tutorial_10: "No olvides entrar en el juego.",
  main_crush_tutorial_11: "Allí también puedes obtener",
  main_crush_tutorial_12: "¡galletas gratis!",
  main_crush_tutorial_13: "Mañana te espera",
  main_crush_tutorial_14: "un nuevo pronóstico,",
  main_crush_tutorial_15: "¡suscríbete para no olvidarlo!",
  main_crush_tutorial_16: "Suscribirse",
  main_crush_tutorial_17: "Entendido",
  main_footer_dating: "Citas",
  main_footer_free_cookies: "Galletas gratis",
  main_footer_game: "Juego",
  main_footer_hint: "¡Galletas!",
  main_footer_profile: "Perfil",
  main_footer_rating: "Clasificación",
  main_free_timer_text_1: "Gratis",
  main_free_timer_text_2: "Obtener",
  main_main_cookie_text_1: "¿Qué te parece el pronóstico?",
  main_share_buttons_invite: "Invitar a un amigo",
  main_share_buttons_published: "Publicado",
  main_share_buttons_story: "En la historia",
  main_share_buttons_wall: "En el muro",
  main_share_buttons_share: "Compartir",  
  modals_battle_help_1: "Bienvenido al modo PvP - batallas con un jugador en vivo.",
  modals_battle_help_2: "En este modo, debes realizar más combinaciones de galletas que tu oponente en un corto período de tiempo.",
  modals_battle_help_3: "Al inicio, recibes 3500 de plata y la posibilidad de usar la lluvia de galletas por una galleta de tu apuesta.",
  modals_battle_help_4: "Tú y tu oponente hacen una apuesta y comienzan la batalla. Si ganas, recuperas lo que queda de tu apuesta y la apuesta completa de tu oponente.",
  modals_battle_help_5: "Si pierdes, pierdes tu apuesta y tu oponente se la queda.",
  modals_battle_help_6: "¡Buena suerte en las batallas!",
  modals_battle_help_ok: "Entendido",
  modals_battle_help_title: "Batallas: Ayuda",
  modals_bonus_spwp_1: "¡Felicidades!",
  modals_bonus_spwp_2: "Han llegado nuevos jugadores a través de tus enlaces:",
  modals_bonus_spwp_3: "Recompensa:",
  modals_bonus_spwp_4: "¡Brillante!",
  modals_bonus_spwp_5: "Recoger",
  modals_bonus_spwp_title: "Recompensa por invitados",
  modals_common_ok: "Ok",
  modals_common_title: "Información",
  modals_exit_battle_question: '¿Abandonar la batalla?',
  modals_exit_battle_description_1: 'El entrenamiento se completará',
  modals_exit_battle_description_2: 'Perderás la batalla y también tus galletas',
  modals_exit_battle_accept: 'Sí\nabandonar',
  modals_exit_battle_reject: 'No\nquedarse',
  modals_modal_no_bricks_1: "¡Oh no!",
  modals_modal_no_bricks_2: "No tienes suficientes",
  modals_modal_no_bricks_3: "Los ladrillos se producen en las ciudades, en la fábrica de ladrillos.",
  modals_modal_no_bricks_4: "Ok",
  modals_no_hard_hint_shop: "Vuelve mañana\no recarga tu saldo!",
  modals_no_hard_hint_no_shop: "Vuelve mañana\ny recibe galletas gratis!",
  modals_no_hard_offer_ad: "Recibe una galleta\npor ver un anuncio",
  modals_no_hard_watch_ad: "Ver",
  modals_no_hard_no: "¡Oh no!",
  modals_no_hard_not_enough: "No tienes suficientes",
  modals_no_hard_ok: "Entendido",
  modals_no_hard_shop: "A la tienda",
  modals_offer_notify_1: "Pronto aparecerá una galleta gratis.",
  modals_offer_notify_2: "¿Quieres que te notifiquemos cuando esté disponible?",
  modals_offer_notify_ok: "Bien",
  modals_offline_1: "Se ha perdido la conexión con el servidor",
  modals_offline_ok: "OK",
  modals_offline_profit_1: "Mientras no estabas,",
  modals_offline_profit_2: "tus galletas ganaron",
  modals_offline_profit_3: "Tiempo de ingresos offline",
  modals_offline_profit_4: "0 h",
  modals_offline_profit_5: "¡Triplicar!",
  modals_offline_profit_6: "Recoger x3",
  modals_offline_profit_get: "Recoger",
  modals_offline_profit_hour: " h.",
  modals_offline_profit_min: " m.",
  modals_offline_profit_title: "Ingresos",
  modals_ping_screen_back: "volver",
  modals_ping_screen_connection: "Conectando...",
  modals_promo_code_1: "Términos de uso",
  modals_promo_code_2: "Activa en",
  modals_promo_code_3: "Copiar código promocional",
  modals_promo_code_4: "Fecha de caducidad:",
  modals_promo_code_5: "Todos los regalos están aquí, en la sección «Tus códigos promocionales»",
  modals_promo_code_6: "Gratis",
  modals_promo_code_7: "galletas",
  modals_promo_code_8: "Enviar por mensaje privado",
  modals_promo_code_9: "Continuar",
  modals_promo_code_10: "Anuncio",
  modals_search_ads_1: "Buscando anuncio",
  modals_session_error_1: "¡Parece que ya has iniciado sesión en otro dispositivo!",
  modals_session_error_2: "Para seguir jugando aquí, haz clic en el botón de abajo",
  modals_session_error_3: "Usar este dispositivo",
  modals_session_error_oops: "¡Ups!",
  modals_technical_works_1: "Se están realizando trabajos técnicos. La aplicación está temporalmente fuera de servicio. Lamentamos las molestias.",
  modals_tester_settings_1: "Tutorial constante de rompimiento",
  modals_tester_settings_2: "Consejos constantes para el juego de combinación",
  modals_tester_settings_3: "Combate",
  modals_tester_settings_4: "Prueba",
  modals_tester_settings_6: "Cerrar",
  modals_tester_settings_title: "Pruebas",
  modals_welcome_city_1: "¡Solicitud aprobada!",
  modals_welcome_city_2: "El alcalde de la ciudad ha aprobado tu solicitud de ingreso.",
  modals_welcome_city_3: "¡Date prisa en visitar tu ciudad, descubre los bonos recibidos y chatea con otros residentes!",
  modals_welcome_city_4: "¡A la ciudad!",
  modals_wheel_prize_get: "Recoger",
  modals_wheel_prize_open: "¡Abrir!",
  modals_winner_gift_1: ", ¡has recibido un regalo! ¡Felicidades!",
  modals_winner_gift_accept: "Aceptar",  
  predict_download_1: "Explorando los horizontes del mañana",
  predict_download_2: "Prediciendo el futuro",
  predict_download_3: "Descifrando los misterios del tiempo",
  predict_download_4: "Analizando perspectivas",
  predict_download_5: "Descubriendo el mañana",
  predict_download_6: "Explorando caminos hacia adelante",
  predict_download_7: "Levantando el velo del tiempo",
  predict_download_8: "Mirando hacia el futuro",
  predict_download_9: "Descifrando el código del mañana",
  predict_download_10: "Estudiando cuerpos celestes",
  predict_download_11: "Observando los vastos espacios cósmicos",
  predict_download_12: "Explorando el cielo estrellado",
  predict_download_13: "Observando el cosmos",
  predict_download_14: "Examinando el mapa estelar",
  predict_download_15: "Explorando las profundidades del universo",
  predict_download_16: "Buscando respuestas en las fuerzas superiores",
  predict_download_17: "Consultando la sabiduría del universo",
  predict_download_18: "Dialogando con lo divino",
  predict_download_19: "Explorando conocimientos místicos",
  predict_download_20: "Conectando con el mundo invisible",
  predict_download_21: "Solicitando profecías",
  predict_download_22: "Escuchando las voces de lo alto",
  predict_download_23: "Interpretando los signos del destino",
  predict_download_24: "Extrayendo sabiduría del éter cósmico",
  predict_download_25: "Consultando a los sabios",
  predict_download_26: "Reflexionando sobre lo eterno",
  predict_download_27: "Buscando consejo en las fuerzas mayores",
  predict_download_28: "Profundizando en los secretos de la magia",
  predict_download_29: "Consultando las fuentes de sabiduría",
  predict_download_30: "Haciendo preguntas a la conciencia cósmica",
  profile_cookies_counter: "Tu saldo:",
  profile_gift_page_inventory: "Inventario",
  profile_gift_page_shop: "Tienda",
  profile_item_friend_select: "Seleccionar",
  profile_item_shop_gift_hit: "popular",
  profile_no_items_1: "Lamentablemente, aún no has recibido ningún regalo.",
  profile_no_items_2: "Haz un regalo a un amigo y probablemente te devolverá el gesto.",
  profile_no_items_3: "Regalar a un amigo",
  profile_no_items_4: "Lamentablemente, no has recibido un regalo gratis.",
  profile_no_items_5: "Puedes obtener regalos aleatorios rompiendo predicciones o ganándolos en la rueda de la fortuna.",
  profile_no_items_6: "También puedes elegir cualquier regalo por galletas.",
  profile_no_items_7: "Seleccionar",
  profile_no_items_8: "Lamentablemente, aún ninguno de tus amigos juega a \"Galleta\".",
  profile_no_items_9: "Ocurrió un error, inténtalo más tarde.",
  profile_no_items_10: "La lista está vacía :(",
  profile_no_items_11: "La búsqueda no arrojó resultados.",
  profile_open_gift_page_1: "Regalado por:",
  profile_open_gift_page_2: "Colocar en vitrina",
  profile_open_gift_page_3: "Aceptar",
  profile_page_1: "Predicciones abiertas:",
  profile_page_2: "Nivel máximo de la galleta:",
  profile_page_3: "Nivel máximo de la liga:",
  profile_page_4: "Inventario",
  profile_page_5: "Guardar",
  profile_page_title: "Perfil",
  profile_received_gift_1: "Remitente:",
  profile_received_gift_put: "Instalado",
  profile_received_gift_showcase: "A la vitrina",
  profile_received_gift_title: "Abrir nuevo regalo",
  profile_received_page_1: "Regalos recibidos",
  profile_select_friend_page_1: "¿A quién regalar?",
  profile_select_friend_page_2: "Encontrar amigo en la lista",
  profile_send_gift_page_1: "Regalo",
  profile_send_gift_page_send: "Enviar",
  profile_user_gifts_1: "Regalar a un amigo",
  profile_user_gifts_2: "Regalar",
  profile_user_gifts_3: "Regalos recibidos:",
  profile_user_gifts_watch: "Ver",
  rating_1: "Consulta los resultados en nuestro",
  rating_2: "grupo oficial",
  rating_3: "¿Quién ha comido más?",
  rating_all: "Todo el tiempo",
  rating_list_1: "Aún no hay nadie",
  rating_list_2: "sé el primero",
  rating_list_3: "Ocurrió un error",
  rating_list_4: "datos no recibidos, inténtalo más tarde",
  rating_month: "Mes",
  rating_today: "Hoy",
  rating_week: "Semana",
  store_ad_mess_1: "Algo salió mal, no pudimos otorgarte la recompensa.",
  store_ad_mess_2: "Lamentablemente, has cerrado el anuncio, intenta de nuevo.",
  store_ad_mess_3: "Lamentablemente, no fue posible encontrar un anuncio. Inténtalo de nuevo más tarde.",  
  store_ad_5: "No hay anuncios disponibles en este momento.",
  store_ad_6: "Intenta comprobar en el ordenador, suele suceder más allí.",
  store_ad_7: "No olvides desactivar el VPN y el bloqueador de anuncios",
  store_app_authorization_1: "¡Inicio de sesión exitoso!",
  store_app_authorization_2: "Bienvenido",
  store_app_authorization_3: "¿Te gusta el juego?",
  store_app_authorization_4: "¿Has registrado tus datos?",
  store_app_authorization_5: "Correo electrónico inválido",
  store_app_authorization_6: "¡Reenvío disponible más tarde!",
  store_app_authorization_7: "¡Genial! Tus datos fueron enviados exitosamente a ",
  store_city_buildings_brickyard_1: "Producción completada: +",
  store_city_city_1: "Error al crear la ciudad. Contacta con soporte.",
  store_city_city_2: "Error al modificar la ciudad. Contacta con soporte.",
  store_city_city_3: "Error al eliminar la ciudad. Contacta con soporte.",
  store_city_city_4: "El jugador ya está en otra ciudad.",
  store_city_city_5: "¡El nombre de la ciudad es demasiado corto!",
  store_city_city_6: "¡Nombre de ciudad inválido!",
  store_city_city_7: "¡Descripción de ciudad inválida!",
  store_city_city_8: "¡Logotipo inválido!",
  store_city_city_9: "¡No tienes suficientes galletas!",
  store_city_city_10: "¡No tienes suficientes ladrillos!",
  store_city_city_11: "¡Error! Aún quedan habitantes en la ciudad.",
  store_city_city_12: "¡Qué vergüenza, no seas travieso!",
  store_city_city_13: "¡La invitación ya existe!",
  store_city_city_14: "¡Vaya, la ciudad está llena!",
  store_city_city_15: "Oh, esa ciudad ya no existe :(",
  store_city_city_16: "¡Error de producción!",
  store_city_city_17: "¡Error al rellenar el edificio!",
  store_city_city_18: "¡Error! Lamentablemente, esta oferta ha terminado.",
  store_city_city_19: "Error:",
  store_city_control_1: "Crear una ciudad",
  store_city_control_2: "Fundar ciudad",
  store_city_control_3: "Modificar ciudad",
  store_city_control_4: "Guardar cambios",
  store_city_control_5: "¡El nombre de la ciudad no puede estar vacío!",
  store_city_control_6: "Error desconocido",
  store_city_control_7: "¡Los cambios se han guardado con éxito!",
  store_city_tutorial_1: "¡En el mapa de la ciudad hay edificios y ya te están dando bonus!",
  store_city_tutorial_2: "Si los mejoras, obtendrás más bonus y recompensas en el juego.",
  store_city_tutorial_3: "Aquí está el ranking de los habitantes de la ciudad.",
  store_city_tutorial_4: "¡Compite con otros habitantes para recibir recompensas!",
  store_city_tutorial_5: "Y aquí, el ranking de otras ciudades.",
  store_city_tutorial_6: "¡Los habitantes deben unir fuerzas para que tu ciudad sea la mejor!",
  store_city_tutorial_7: "Siempre puedes obtener más información en la ventana de ayuda.",
  store_city_tutorial_8: "Se necesitan ladrillos para mejorar la ciudad.",
  store_city_tutorial_9: "Para producirlos, abre una fábrica de ladrillos.",
  store_game_battle_1: "Bender",
  store_game_battle_2: "Rodríguez",
  store_game_core_1: "¡No tienes suficientes monedas!",
  store_game_core_2: "Aumento de ganancias habilitado hasta",
  store_game_core_3: "por",
  store_game_core_4: "horas",
  store_game_core_5: "Aumento de ganancias hasta",
  store_game_core_6: "extendido por",
  store_game_core_7: "horas",
  store_game_core_8: "¡No se puede eliminar el máximo!",
  store_game_core_9: "¡No puedes fusionar los máximos!",
  store_game_main_1: "¡Error! Te has quedado sin premios.",
  store_game_main_2: "¡Error! Lamentablemente, esta oferta ha terminado.",
  store_game_main_3: "¡Nuevo nivel de galleta! ",
  store_game_core_10: "No hay espacio libre",
  store_game_tutorial_battle_1: "¡Bienvenid@ a la batalla de entrenamiento, aquí te enfrentarás a nuestro oponente de entrenamiento!",
  store_game_tutorial_battle_2: "Frente a ti está el campo de juego.",
  store_game_tutorial_battle_3: "El objetivo del juego es fusionar más galletas que el oponente en 60 segundos.",
  store_game_tutorial_battle_4: "El tiempo de juego y el número de fusiones se muestran arriba.",
  store_game_tutorial_battle_5: "Inicialmente, tienes 3500 monedas de plata para comprar galletas de nivel 1 a 100 monedas de plata cada una.",
  store_game_tutorial_battle_6: "¡Comienza a fusionar galletas!",
  store_game_tutorial_battle_7: "¡Es hora de usar la lluvia de galletas!",
  store_game_tutorial_battle_8: "La lluvia de galletas gasta 1 galleta de tu apuesta, disminuyendo así la recompensa obtenida, pero da una buena ventaja sobre el oponente, facilitando la victoria.",
  store_main_main_loading: "cargando...",
  store_profile_profile_1: "Escribe tu comentario sobre el regalo",
  store_profile_profile_2: "Regalos",
  store_profile_profile_3: "Regalar",
  store_profile_profile_4: "¡El regalo ha sido enviado con éxito!",
  store_profile_profile_5: "Regalar a un amigo",
  store_profile_profile_6: "Hacer un regalo",
  store_profile_profile_7: "regalar",
  store_profile_profile_grade_1: "Común",
  store_profile_profile_grade_2: "Ordinario",
  store_profile_profile_grade_3: "Raro",
  store_profile_profile_grade_4: "¡Súper raro!",
  store_rating_1: "En 24 horas",
  store_rating_2: "Desde el lunes",
  store_rating_3: "Desde el 1º del mes",
  store_rating_4: "Todo el tiempo",
  store_shop_1: "Nos disculpamos, hasta que termine la moderación, las compras están temporalmente no disponibles.",
  store_shop_2: "Algo salió mal, por favor intenta de nuevo más tarde.",
  store_shop_3: "\"Triple beneficio\"",
  store_shop_4: "¡En la primera compra, obtén tres veces más galletas al precio normal!",
  store_shop_5: "Multiplicamos las galletas X3",
  store_shop_6: "¡No tienes suficientes galletas!",
  store_shop_7: "Error. ¡Por favor, contacta con soporte!",
  store_shop_8: "en oferta",
  store_shop_9: "de regalo",
  store_shop_10: "y además",
  store_shop_11: "Has recibido",
  store_shop_12: "¡Disfruta el juego!",
  store_shop_processing_popup: "¡Tu compra todavía está en proceso!",
  store_user_user_1: "Únete al grupo",
  store_user_user_2: "Suscríbete a notificaciones",
  store_user_user_3: "Añadir a favoritos",
  store_user_user_4: "Suscríbete a mensajes privados del grupo",
  store_user_user_5: "¡Escribe \"Hola\" en el grupo!",
  store_user_user_6: "Comparte en tu muro",
  store_wheel_1: "¡Felicidades!",
  store_wheel_2: "¡Hurra!",
  store_wheel_3: "¡Súper!",
  store_wheel_4: "¡Genial!",
  store_wheel_5: "¡Increíble!",
  store_wheel_6: "¡Éxito!",
  store_wheel_7: "¡Suerte!",
  store_wheel_8: "¡Fantástico!",
  store_wheel_9: "¡Maravilloso!",
  store_wheel_10: "¡Impresionante!",
  store_wheel_11: "¡Jackpot! ",
  store_wheel_12: "Ingresos de plata por 1 hora",
  store_wheel_13: "las monedas se acreditarán después de iniciar el juego",
  store_wheel_14: "Lluvia de galletas gratis",
  store_wheel_15: "los intentos ganados se suman",
  store_wheel_16: "Premio pequeño: +",
  store_wheel_17: "+1 al nivel de ingresos offline",
  store_wheel_18: "Ingreso de plata por 2 horas",
  store_wheel_19: "+50 conexiones en el juego",
  store_wheel_20: "conquista ligas, obtén premios",
  store_wheel_21: "Gran premio: +",
  store_wheel_22: "Impulsor de ingresos gratis",
  store_wheel_23: "Ingreso de plata por 30 minutos",
  store_wheel_24: "Regalo para la colección",
  store_wheel_25: "puedes dárselo a alguien",
  store_wheel_26: "Ingreso de plata por 4 horas",
  store_wheel_27: "¡Parece que no te quedan billetes gratis!",
  welcome_but_proceed: "Continuar",
  welcome_text: "¡Obtén una galleta gratis y descubre cuándo aparecen nuevas!",
  wheel_1: "¡Prueba tu suerte, gana el gran premio!",
  wheel_2: "Ganadores:",
  wheel_ad_play_button_1: "Jugar",
  wheel_ad_play_button_2: "¡Gratis!",
  wheel_btn_1: "¡Jugar!",
  wheel_btn_2: "La Rueda de la Fortuna aún no está disponible.",
  wheel_btn_3: "¡Vuelve mañana para jugar!",
  wheel_play_1: "Jugar por",
  wheel_title: "Rueda de la Fortuna",
  wheel_winner_list_item_hour: " h.",
  wheel_winner_list_item_min: " min.",
  wheel_winner_list_item_sec: " seg.",
  wheel_winner_spin_1: "Has ganado",
  wheel_winner_spin_2: "Obtener",
  app_emo_status_title: '¡Elige tu estado emoji!',
  app_emo_status_1: 'Aparecerá a la derecha de tu nombre y será visible para todos en ',
  app_emo_status_remove: 'eliminar estado',
  app_emo_status_done: 'Listo',
  app_loading_offline_title: 'Mantenimiento técnico',
  app_loading_offline_message: 'Se están realizando trabajos técnicos en la aplicación, disculpa las molestias.\n\nVuelve un poco más tarde.',
  app_loading_agreement_header_1: '¡Esto es importante!',
  app_loading_agreement_header_2: 'Antes de empezar a jugar, por favor lee y acepta los términos:',
  app_loading_agreement_checkbox_default: 'Acepto los términos del acuerdo',
  app_loading_agreement_accept: 'Jugar',
  app_loading_agreement_decline: 'Salir del juego',  
  chapter_level: 'nivel',
  chapter_difficulty_easy: 'Fácil',
  chapter_difficulty_medium: 'Medio',
  chapter_difficulty_hard: 'Difícil',
  chapter_until_refresh: 'Hasta la actualización:',
  chapter_chapter_rank: 'Rango:',
  chapter_chapter_ended: 'Hasta el final:',
  chapter_chapter_of: 'de',
  chapter_chapter_difficulty_1: 'Obtén',
  chapter_chapter_difficulty_2: ', para avanzar al nuevo rango!',
  chapter_chapter_difficulty_3: ', para permanecer en este rango!',
  chapter_chapter_completed_1: '¡Las aventuras de esta temporada han terminado!',
  chapter_chapter_completed_2: 'Vuelve más tarde cuando comience la nueva temporada.',
  chapter_tasks_hourly: 'Tareas de galletas',
  chapter_tasks_daily: 'Tareas diarias',
  chapter_tasks_weekly: 'Tareas semanales',
  chapter_hint_m1: 'Ve al juego y compra algunas galletas en la mesa a través del menú "Compra rápida" o en el "Mercado".',
  chapter_hint_m2: 'Combina dos galletas iguales en tu mesa de juego.',
  chapter_hint_m3: 'Activa el acelerador de ingresos de monedas, que se encuentra en la pestaña "Mejoras" en el juego.',
  chapter_hint_m4: 'Inicia una lluvia de galletas en el juego. Está en la pestaña "Mejoras".',
  chapter_hint_m5: 'Combina galletas en el juego y aumenta el nivel de tu galleta máxima.',
  chapter_hint_m6: 'Mejora tu nivel de ingresos offline en el juego, que se encuentra en la pestaña "Mejoras".',
  chapter_hint_m7: 'Ve a la sección de mejoras de platos (pestaña "Mejoras") y sube de nivel tu plato.',
  chapter_hint_m8: 'Al finalizar tu liga en el juego, debes estar en el puesto 20 o superior.',
  chapter_hint_m9: 'Ingresa al juego con un intervalo de más de 24 horas para aumentar el progreso de la tarea.',
  chapter_hint_m10: 'Al regresar al juego, recoge tus monedas de ingresos offline.',
  chapter_hint_m11: 'Consulta tu posición en la liga del juego, verifica tu posición nuevamente, debe haber cambiado.',
  chapter_hint_m12: 'Inicia una lluvia de galletas y no dejes que ninguna galleta pase de largo de la mesa de juego, atrapándolas todas.',
  chapter_hint_m13: 'Coloca en tu mesa de juego la cantidad necesaria de galletas con niveles en orden.',
  chapter_hint_m14: 'En tu mesa de juego debe haber la cantidad necesaria de galletas con niveles en orden, de tu galleta más grande a la más pequeña.',
  chapter_hint_m15: 'Activa el "acelerador de ingresos de monedas" del premio, debe indicar "Premio" en el costo. Se encuentra en la pestaña "Mejoras" en el juego.',
  chapter_hint_m16: 'Inicia la lluvia de galletas del premio en el juego. Debe indicar "Premio" en el costo.',
  chapter_hint_c1: 'Ve a tu ciudad y crea algunos ladrillos en la "Fábrica de ladrillos".',
  chapter_hint_c2: 'Visita tu ciudad, elige cualquier edificio en el mapa y añade galletas.',
  chapter_hint_c3: 'Visita tu ciudad, abre cualquier edificio en el mapa y añade ladrillos.',
  chapter_hint_c4: 'Usa cualquier acción para obtener una cantidad de puntos para el ranking de los habitantes de la ciudad.',
  chapter_hint_c5: '',
  chapter_hint_c6: 'Regresa a la ciudad, ve a la pestaña del chat y envía cualquier mensaje en el chat de la ciudad.',
  chapter_hint_c7: 'Para aumentar el progreso, ingresa a tu ciudad con un intervalo de más de 24 horas.',
  chapter_hint_f1: 'Abre las batallas en el juego y realiza cualquier batalla no de entrenamiento.',
  chapter_hint_f2: 'Juega una batalla y termínala, venciendo a tu oponente.',
  chapter_hint_f3: 'Juega una batalla, combina galletas y termínala haciendo más de 60 combinaciones.',
  chapter_hint_f4: 'Participa en una batalla y termínala teniendo una galleta de al menos nivel 7 en la mesa de batalla.',
  chapter_hint_f5: 'Juega en diferentes batallas y compra galletas para la mesa con monedas, cada moneda gastada cuenta.',
  chapter_hint_p1: 'Obtén una predicción rompiendo una galleta en cualquier categoría.',
  chapter_hint_p2: 'Elige cualquier categoría de predicción, excepto "Diaria", y rompe una galleta.',
  chapter_hint_p3: 'Obtén cualquier predicción y compártela en cualquier forma disponible.',
  chapter_hint_p4: 'Abre cualquier predicción y califícala pulsando el botón "Pulgar arriba" o "Pulgar abajo".',
  chapter_hint_q1: 'Completa cualquier tarea de aventuras y pulsa el botón "Recoger" para obtener estrellas de experiencia.',
  chapter_hint_q2: 'Completa cualquier "Tarea de galletas" en la aventura pulsando el botón "Recoger".',
  chapter_hint_q3: 'Pulsa el botón "Recoger" en cualquier "Tarea diaria" de aventuras completada.',
  chapter_hint_q4: 'Completa cualquier tarea de aventuras y recoge estrellas de experiencia para aumentar tu nivel.',
  chapter_hint_q5: 'Acelera las "Tareas de galletas" pulsando el botón "Acelerar", usa todos los aceleradores posibles en un día para aumentar el progreso en una unidad.',
  chapter_hint_d1: 'Abre la "Rueda de la Fortuna" y gírala, probando tu suerte. Cuenta el hecho de girar.',
  chapter_hint_d2: 'Visita la sección de tu perfil desde cualquier lugar en la aplicación.',
  chapter_hint_d3: 'Envía un regalo a alguien utilizando los botones: en el perfil de otro - "Regalar" o en tu propio perfil - "Regalar a un amigo".',
  chapter_hint_d4: 'Puedes pedirle a alguien que te envíe un regalo, por ejemplo: un amigo, un habitante de la ciudad o tú mismo envía un regalo y espera una respuesta.',
  chapter_hint_d5: 'Mira cualquier anuncio con recompensa, por ejemplo: "Aceleración de tarea", "Rueda de la fortuna", "+1 galleta", etc.',
  chapter_hint_d6: 'Ingresa a la aplicación con un intervalo de más de 24 horas para aumentar el progreso.',
  chapter_hint_d7: 'No cierres la aplicación durante el tiempo necesario. Quédate con nosotros un poco más.',
  chapter_hint_d8: 'Gasta galletas en cualquier objetivo: bonos, mejoras, predicciones..., cada galleta gastada cuenta.',
  chapter_hint_d9: 'Obtén galletas para tu saldo, por ejemplo: en "Aventuras", recoge las "Gratis", gana en la "Rueda de la Fortuna", etc., cada galleta cuenta.',
  chapter_hint_w2: 'Gira la "Rueda de la Fortuna" usando un intento gratis por anuncio. Solo se cuenta el giro por anuncio.',
  chapter_hint_w3: 'Prueba tu suerte en la "Rueda de la Fortuna". Gana "Monedas" para aumentar el progreso de esta tarea.',
  chapter_hint_w4: 'Abre la "Rueda de la Fortuna", juega, si ganas un "Regalo", el progreso aumentará.',
  chapter_next_level_greetings: '¡Felicidades!',
  chapter_next_level_proceed: 'Continuar',
  chapter_next_level_reward: 'Tu premio',
  chapter_next_level_great: '¡Genial!',
  chapter_next_level_vip_active: 'Estado activo',
  chapter_next_level_vip_offer_1: 'El estado te permitirá',
  chapter_next_level_vip_offer_2: 'recoger todos los premios',
  chapter_next_level_missed: 'Premios perdidos',
  chapter_next_level_more: 'más',
  chapter_next_level_get_vip_1: 'Obtén el estado',
  chapter_next_level_get_vip_2: 'para recoger',
  chapter_task_item_reward: 'Premio',
  chapter_task_item_take: 'Recoger',
  chapter_task_item_completed: 'Completado',
  chapter_task_item_speedup: 'Acelerar',
  chapter_task_item_next: 'Siguiente tarea en:',
  chapter_timer_d: 'd.',
  chapter_timer_h: 'h.',
  chapter_timer_m: 'm.',
  chapter_vip_reward_granted: '¡Estado obtenido!',
  chapter_vip_reward_available: 'Disponibles',
  chapter_vip_reward_missed: 'premios perdidos',
  chapter_vip_reward_hint: 'Mientras el estado esté activo, recibes todos los premios.',
  chapter_vip_reward_take: '¡Recoger!',
  chapter_refresh_title: 'Reemplazar tarea',
  chapter_refresh_message: 'Si no te gusta esta tarea, puedes reemplazarla por otra seleccionada aleatoriamente.',
  chapter_refresh_actions_1: '¿Quieres probar suerte?',
  chapter_refresh_button: 'Reemplazar por',
  chapter_refresh_back: 'Atrás',
  city_control_members_term_s: ' s.',
  city_control_members_term_m: ' m.',
  city_control_members_term_h: ' h.',
  city_control_members_term_d: ' d.',
  city_control_requests_term_d: 'd.',
  free_cookies_promo_codes_empty_1: 'Aún no tienes códigos de promoción :(',
  free_cookies_promo_codes_empty_2: '¡Abre predicciones para recibir agradables regalos!',
  free_cookies_promo_codes_activate: 'Activa en',
  free_cookies_promo_codes_show_1: 'Muestra el código en la tienda,',
  free_cookies_promo_codes_show_2: 'para recoger el regalo',
  free_cookies_promo_codes_gift_1: 'Activa este código promocional',
  free_cookies_promo_codes_gift_2: 'y recibe como regalo',
  free_cookies_promo_codes_condition: '[condiciones]',
  game_counter_soft_vip: 'Del estado VIP',
  game_battle_result_exit_title: 'Descalificación',
  game_battle_result_exit_message: 'Saliste de la batalla antes de tiempo y perdiste:',
  game_task_tracker_season: 'La temporada ha terminado. No hay tareas por ahora.',
  game_task_tracker_until_next: 'Hasta la próxima tarea:',
  game_market_title: 'Mercado',
  game_market_cookies: 'Galletas',
  game_market_coins: 'Monedas',
  main_app_banner_promo: 'Código promocional',
  main_app_banner_reward: 'Recompensa por activación',
  main_categories_title_1: 'ELIGE UNA CATEGORÍA',
  main_categories_title_2: 'PREDICCIONES',
  main_categories_back: 'Atrás',
  main_crush_button_more_wishes: 'Más deseos',
  main_crush_button_crush_wishes: 'Romper',
  main_crush_button_want_wishes: '¡Quiero deseos!',
  main_crush_button_view_wishes: 'Ver lista',
  main_crush_button_prize_crush: 'Romper',
  main_crush_button_prizes: 'Gratis:',
  main_crush_tutorial_share_1: 'Comparte predicciones',
  main_crush_tutorial_share_2: 'con amigos enviando el widget',
  main_crush_tutorial_share_3: 'de la aplicación en los chats!',
  main_footer_promo: 'Tus códigos promocionales',
  main_footer_chapter_1: 'Tareas',
  main_footer_chapter_2: 'de aventuras',
  main_main_cookie_complaint: '[queja]',
  main_main_cookie_empty_wishes: 'No hay nuevos deseos.',
  main_main_cookie_count_wishes: 'Tienes',
  main_share_buttons_sender: '¿Quién lo envió?',
  main_share_buttons_reveal: 'Descubrir por',
  main_share_buttons_view_1: 'Ver',
  main_share_buttons_view_2: 'deseos',
  main_share_buttons_to_chat: 'Enviar al chat',
  modals_complaint_complaint: 'Quejarse',
  modals_complaint_attention: 'Todos los deseos recibidos de este remitente serán eliminados y no podrá enviarte nuevos deseos.',
  modals_complaint_blocking_1: 'Bloquear al autor',
  modals_complaint_blocking_2: 'y eliminar los deseos',
  modals_onboarding_header_1: 'Abre galletas con predicciones con amigos a través de diálogos y chats',
  modals_onboarding_header_2: 'Tus amigos pueden compartir sus predicciones en el chat',
  modals_onboarding_content_1: 'Comparte las predicciones recibidas a través de la historia y el muro',
  modals_onboarding_content_2: 'Y tú puedes enviar las tuyas en respuesta',
  modals_onboarding_ok: 'De acuerdo',
  modals_promo_code_bonus_1: 'Regalo por activación:',
  modals_promo_code_bonus_ya_1: 'Recibe un regalo por la activación del código de promoción',
  modals_promo_code_bonus_ya_2: '(el plazo de entrega de las galletas es de 4 días)',
  modals_promo_code_great: '¡Genial!',
  modals_promo_code_footer_btn_1: '¡Tuyos!',
  modals_promo_code_footer_btn_2: '¡códigos de promoción!',
  modals_tester_settings_tutor_mode: 'Modo tutorial de prueba en el juego',
  modals_tester_settings_skip_ad: 'Saltar anuncios por recompensa',
  profile_profile_page_vip_until: 'Activo hasta:',
  profile_profile_page_emo_status_1: 'Emoji',
  profile_profile_page_emo_status_2: 'estado',
  profile_profile_page_register: 'Ya con una galleta:',
  shop_pack_item_page_sale: 'Oferta',
  shop_pack_item_page_status: 'Estado',
  shop_pack_item_page_until_vip: 'Activo hasta',
  shop_pack_item_page_unsubscribe: 'Darse de baja',
  shop_pack_item_page_unsubscribed: 'Dado de baja',
  shop_pack_item_page_unavailable: 'Mientras el estado VIP esté activo, este paquete no estará disponible.',
  shop_pack_item_page_cost: 'Costo',
  shop_pack_item_page_privacy: 'Al hacer clic en "Obtener", aceptas el',
  shop_pack_item_page_agreement: 'Acuerdo de usuario',
  shop_pack_item_page_processing: 'Procesando la compra',
  shop_sales_container_bonus_success_1: '¡Hurra! Regalo recibido.',
  shop_sales_container_bonus_success_2: 'Visita la tienda para no perderte nuevos regalos y ofertas.',
  shop_sales_container_bonus_take: 'Recoger',
  shop_sales_container_left: 'Quedan: ',
  shop_shop_page_title: 'Tienda',
  shop_shop_page_cookies: 'Galletas',
  shop_shop_page_vip: 'Estado VIP',
  shop_shop_page_boosters: 'Paquetes de refuerzo',
  shop_shop_page_hit: 'HIT',
  shop_shop_page_active: 'Activo',
  wishes_received_empty_new: '¡Rompe una galleta para conocer tu primer deseo!',
  wishes_received_empty: 'Lamentablemente, tu lista de deseos está vacía por ahora :(',
  wishes_received_more: 'Más',
  wishes_received_list_1: 'Deseos',
  wishes_received_list_2: 'lista',
  wishes_received_sender: '[quién lo envió]',
  wishes_received_reveal: 'Revelar identidad por',
  wishes_received_complaint: '[queja]',
  wishes_wishes_hint: 'Introduce el texto del deseo',
  wishes_wishes_todo_1: 'Escribe',
  wishes_wishes_todo_2: 'un deseo sincero',
  wishes_wishes_result_1: 'Deseo',
  wishes_wishes_result_2: 'para',
  wishes_wishes_result_3: '¡Enviado!',
  wishes_wishes_wish: 'Desear',
  wishes_wishes_get_predict: 'Obtener predicción',
  store_ad_limit: '¡Límite de visualizaciones alcanzado!',
  store_ad_tests: 'Saltando la visualización de anuncios. La configuración está habilitada en las pruebas.',
  store_ad_task_reward_error: '¡No se pudo encontrar la tarea para acelerar!',
  store_ad_speed_count: 'Aceleraciones usadas:',
  store_ad_survey_closed: 'La encuesta publicitaria no se completó, inténtalo de nuevo más tarde.',
  store_chapter_info_name: 'Aventuras',
  store_chapter_wt: '¡Se recibió una ID de tarea inexistente!',
  store_chapter_er_pr: '¡Algo salió mal al registrar el progreso de las tareas!',
  store_chapter_task_ready: '¡Tarea completada!\n¡Date prisa en recoger las estrellas de experiencia!',
  store_chapter_new_task: '¡Nueva tarea disponible!',
  store_chapter_sw: 'Hm... ¡Algo salió mal!',
  store_chapter_sb: '¡Algo se rompió!',
  store_shop_eb_header: 'OFERTAS',
  store_shop_eb_text: 'Pronto habrá nuevas ofertas y regalos. ¡Visita la tienda con frecuencia para no perderte nada!',
  store_shop_buy_pack: 'Obtener paquete',
  store_shop_pack_contains: 'CONTENIDO DEL PAQUETE',
  store_shop_vip_contains: 'VENTAJAS',
  store_shop_vip_info_chapter: 'desbloquea recompensas de aventuras',
  store_shop_vip_info_free: '+1 galleta gratis al día',
  store_shop_vip_info_fc: '+1 galleta al día por tareas sociales',
  store_shop_vip_info_main_ad: '+5 anuncios con recompensa al día',
  store_shop_vip_info_soft: 'x2 a los ingresos de monedas en el juego',
  store_shop_vip_info_icon: 'icono VIP en el ranking',
  store_shop_vip_info_no_ad: 'desactivación de anuncios a pantalla completa y banners',
  store_shop_receive_vip: 'Obtener estado',
  store_shop_prolong_vip: 'Prolongar estado',
  store_shop_prolonged_vip_1: '¡Felicidades!\nTu estado VIP ha sido prolongado por',
  store_shop_prolonged_vip_2: 'días.\n\nDisfruta del juego.',
  store_shop_received_vip_1: '¡Felicidades!\nHas recibido el estado VIP por',
  store_shop_received_vip_2: 'días.\n\nDisfruta del juego.',
  store_shop_received_vip_3: '¡Felicidades! Has recibido:\n',
  store_shop_received_vip_4: 'días.\n\nDisfruta del juego.',
  store_shop_bu_error: '¡Este regalo ya ha sido recibido!',
  store_shop_b_error: 'Algo salió mal, no se pudo recoger el regalo.',
  store_shop_sbe: 'Algo se rompió, inténtalo más tarde.',
  store_shop_unsbce: 'No se pudo cancelar la suscripción, algo salió mal.',
  store_shop_unsbce_vk: 'No se pudo cancelar la suscripción, error de VK',
  store_shop_pack_bonus: ' (regalo)',
  store_shop_pack_sale: ' (oferta)',
  store_shop_pack_vip: 'Estado VIP por ',
  store_wishes_category_name: 'Deseos',
  store_wishes_category_hint: 'Rompe una galleta y descubre lo que te desean otras personas',
  store_wishes_e_empty: 'Hm, ¡no hay más deseos nuevos!',
  store_wishes_e_bad: '¡Por favor, usa texto adecuado para el deseo!',
  store_wishes_e_no_user_1: 'Desafortunadamente,',
  store_wishes_e_no_user_2: 'no ha ingresado a la Galleta desde hace tiempo y no está en la base de datos.',
  store_wishes_e_already_sent: '¡ya recibió un deseo tuyo hoy!',
  store_wishes_e_black: '¡no acepta deseos tuyos!',
  store_wishes_e_no_hard: '¡No hay suficientes galletas!',
  store_wishes_e_def: '¡Error!',
  store_wishes_butt_e: 'Botón no añadido, algo salió mal',
  store_wishes_butt_suc: '¡Ahora puedes recibir deseos!',
  store_wishes_butt_ue: 'Botón no añadido, ocurrió algún error.',
  store_wishes_e_sender_uid: '¡No puedes enviarte un deseo a ti mismo!',
  store_wishes_ue: 'Error desconocido: ',
  store_wishes_complaint: 'Tu queja ha sido recibida, el autor ha sido bloqueado y todos sus deseos eliminados.',
  store_game_main_es: '¡Error al guardar el juego!',
  store_game_main_esw: '¡Algo salió mal!',
  store_game_main_esb: '¡Algo se rompió!',
  store_game_plates_su: 'Plato mejorado con éxito a x',
  store_main_no_prize: 'Te has quedado sin predicciones gratis.',
  store_main_esw: 'Hm, algo salió mal, inténtalo más tarde o contáctanos.',
  store_user_friends_evk: '¡Error al obtener la lista de amigos!',
  store_user_status_not_allowed: 'Sin acceso al estado :(',
  store_user_status_eu: '¡Ocurrió algún error!',
  store_user_status_e_empty: '¡No hay estados disponibles!',
  store_user_status_e_not_set: 'No se pudo establecer el estado, parece que algo salió mal.',
  store_user_status_e_not_select: 'No se pudo seleccionar el estado, algo salió mal.',
  store_user_status_e_not_remove: 'No se pudo eliminar el estado, algo salió mal.',
  store_user_recommend_app: 'Recomienda la aplicación',
  store_user_reward_received: '¡Hurra! Recompensa recibida:',
  store_user_esw_recommend: '¡Algo salió mal, contacta al soporte!',
  store_user_esb_recommend: 'Algo se rompió, inténtalo más tarde.',
  store_app_invite_text: 'Te invito a romper galletas con predicciones.',
  store_app_invite_button: 'Obtener predicciones',
  store_app_invite_title: '¡Invita a tus amigos a romper galletas!',
  store_share_error: '¡Uy! ¡Algo salió mal!',  
  share_story_predict_title_1: 'La galleta',
  share_story_predict_title_2: 'me predijo:',
  share_story_special_title_1: 'Recibe',
  share_story_special_title_2: 'la predicción del día',
  share_story_special_title_3: 'de la galleta',
  share_story_biggest_title_1: 'Tengo un nuevo',
  share_story_biggest_title_2: 'nivel',
  share_story_biggest_title_3: 'de galleta',
  share_story_biggest_title_4: 'Un juego genial -',
  share_story_biggest_title_5: '¡únete también!',
  share_story_special_button: 'Obtén tu predicción',
  share_story_predict_button: 'Obtén tu predicción',
  share_story_biggest_button: 'Entrar',
  share_wall_predict_title_1: 'La galleta',
  share_wall_predict_title_2: 'me predijo:',
  share_wall_special_title_1: 'Recibe',
  share_wall_special_title_2: 'predicciones',
  share_wall_special_title_3: 'de la galleta',
  share_wall_biggest_title_1: 'Tengo un nuevo',
  share_wall_biggest_title_2: 'nivel',
  share_wall_biggest_title_3: 'de galleta!',
  share_wall_biggest_title_4: 'Un juego genial -',
  share_wall_biggest_title_5: '¡únete también!',
  share_wall_special_footer_1: '¿Qué te espera hoy?',
  share_wall_special_footer_2: '¡Abre la galleta ahora!',
  share_wall_predict_footer_1: '¿Qué te espera hoy?',
  share_wall_predict_footer_2: '¡Abre la galleta ahora!',
  share_wall_biggest_footer_1: 'Juega el juego, fusiona las galletas',
  share_wall_biggest_footer_2: 'Obtén predicciones',
  share_wall_biggest_footer_3: 'de la Galleta!',
  special_predict: 'Serás feliz',
  achievement_name_1: 'Fanático',
  achievement_description_1: 'Ingresa a la aplicación',
  achievement_hint_1: 'Para aumentar el progreso del logro, simplemente ingresa a la aplicación, pero no muy seguido.',
  achievement_name_2: 'Panadero',
  achievement_description_2: 'Recoge ingresos offline',
  achievement_hint_2: 'Ingresa al juego y recoge los ingresos offline acumulados durante tu ausencia.',
  achievement_name_3: 'Pastelero',
  achievement_description_3: 'Compra galletas para la mesa',
  achievement_hint_3: 'Ingresa al juego y compra galletas para tu mesa de juego, cada galleta cuenta.',
  achievement_name_4: 'Cocinero',
  achievement_description_4: 'Conecta galletas',
  achievement_hint_4: 'Conecta galletas iguales en tu mesa de juego para aumentar el progreso.',
  achievement_name_5: 'Imparable',
  achievement_description_5: 'Activa aceleradores',
  achievement_hint_5: 'Activa el acelerador de ingresos de monedas, que se encuentra en la pestaña "Mejoras" del juego.',
  achievement_name_6: 'Thor',
  achievement_description_6: 'Lanza lluvias de galletas',
  achievement_hint_6: 'Lanza lluvias de galletas en el juego. El botón se encuentra en la pestaña "Mejoras".',
  achievement_name_7: 'Alfarero',
  achievement_description_7: 'Mejora los platos',
  achievement_hint_7: 'Ve a la sección de mejora de platos (pestaña "Mejoras") y sube de nivel los platos.',
  achievement_name_8: 'Oráculo',
  achievement_description_8: 'Abre predicciones',
  achievement_hint_8: 'Rompe galletas en cualquier categoría y obtén tus predicciones para aumentar el progreso del logro.',
  achievement_name_9: 'Reportero',
  achievement_description_9: 'Haz reposts',
  achievement_hint_9: 'Comparte en tu página una predicción, un nuevo nivel de galleta o un logro obtenido. No más de una vez cada pocas horas.',
  achievement_name_10: 'Santa Claus',
  achievement_description_10: 'Regala obsequios',
  achievement_hint_10: 'Envía obsequios a alguien utilizando los botones: en el perfil de otro - "Regalar" o en tu propio perfil - "Regalar a un amigo".',
  achievement_name_11: 'Sector Premio',
  achievement_description_11: 'Gira la Rueda de la Fortuna',
  achievement_hint_11: 'Abre la "Rueda de la Fortuna" y simplemente gírala. Cada giro cuenta.',
  achievement_name_12: 'Afortunado',
  achievement_description_12: 'Gana un "Premio" con galletas',
  achievement_hint_12: 'Gira la "Rueda de la Fortuna" - si obtienes un Premio Menor, Premio Mayor o el Premio Gordo, el progreso aumentará.',
  achievement_name_13: 'Gran Premio',
  achievement_description_13: 'Gana el Premio Gordo',
  achievement_hint_13: 'Gira la "Rueda de la Fortuna", atrapa la suerte y gana el Premio Gordo.',
  achievement_name_14: 'Albañil',
  achievement_description_14: 'Crea ladrillos',
  achievement_hint_14: 'Crea ladrillos en la "Fábrica de ladrillos" de tu ciudad. Cada ladrillo cuenta.',
  achievement_name_15: 'Capitalista',
  achievement_description_15: 'Gana galletas',
  achievement_hint_15: 'Juega en la "Rueda de la Fortuna", gana galletas y el progreso aumentará según la cantidad de galletas ganadas.',
  achievement_name_16: 'Recaudador',
  achievement_description_16: 'Recoge bolsas de monedas',
  achievement_hint_16: 'Usa tu ingenio y atrapa la bolsa de monedas que cae en el campo de juego, recoge sus monedas y el progreso aumentará.',
  achievement_name_17: 'Aventurero',
  achievement_description_17: 'Llega al nivel 45 en aventuras',
  achievement_hint_17: 'Participa en "Aventuras", gana experiencia y sube de nivel para completar este logro.',
  achievement_name_18: 'Exigente',
  achievement_description_18: 'Reemplaza tareas',
  achievement_hint_18: 'Abre "Aventuras" y reemplaza cualquier tarea que no te guste.',
  achievement_name_19: 'Astrónomo',
  achievement_description_19: 'Recoge estrellas de aventuras',
  achievement_hint_19: 'Completa cualquier tarea de "Aventuras" y haz clic en "Recoger" para obtener estrellas de experiencia.',
  achievement_name_20: 'Medallista',
  achievement_description_20: 'Gana un premio en el ranking',
  achievement_hint_20: 'Abre predicciones y ocupa cualquier lugar premiado en el ranking de "¿Quién comió más?", el progreso aumentará después de la "premiación".',
  achievements_congratulations_bronze: 'Bronce',
  achievements_congratulations_silver: 'Plata',
  achievements_congratulations_gold: 'Oro',
  achievements_congratulations_brilliant: 'Diamante',
  achievements_page_title_other: 'Logros',
  achievements_page_title_my: 'Mis logros',
  achievements_page_all_progress: 'Progreso total',
  achievements_my_have: 'Tienen',
  achievements_my_take: 'Recoger',
  achievements_my_reward: 'Recompensa',
  achievements_my_from: 'de',
  achievements_my_gallery: 'Vitrina',
  achievements_my_slot: 'En la ranura',
  achievements_gallery_heading: 'Elige un lugar en la vitrina',
  achievements_gallery_pick: 'Elegir',
  achievements_gallery_switch: 'Reemplazar',
  achievements_gallery_delete: 'Eliminar',
  achievements_gallery_show: 'mostrar todo',
  achievements_gallery_empty: 'Vacío',
  achievements_congratulations_great: '¡Genial!',
  achievements_congratulations_achiev: 'logro',
  achievements_congratulations_cool: 'Genial',
  achievements_congratulations_times: 'veces',
  store_user_achievements_error: 'Logros. ¡Algo salió mal!',
  achievements_story_have: 'TENGO',
  achievements_story_achievement: '¡LOGRO!',
  achievements_story_want: '¿Quieres uno?',
  achievements_story_hurryup: '¡Apresúrate a la galleta!',
  achievements_story_button: 'Por logros',
};

export {spanish};